Repository hicommonwealth/commonwealth, pull requests merged in 2020-04, with the labels that each got.

#3 Updating democracy module for Substrate PR #5294.
  client/scripts/controllers/app/web_wallet.ts
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/identity.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/phragmen_elections.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/models/models.ts
  client/scripts/views/components/header.ts
  client/scripts/views/components/proposal_row.ts
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/components/settings/send_edg_well.ts
  client/scripts/views/components/widgets/account_balance.ts
  client/scripts/views/modals/proposals/new_proposal_form.ts
  client/scripts/views/modals/tx_signing_modal.ts
  client/scripts/views/pages/admin.ts
  client/scripts/views/pages/proposals.ts
  package.json
  server.ts
  server/scripts/resetServer.ts
  shared/adapters/chain/substrate/subscriptions.ts
  shared/adapters/chain/substrate/types.ts
  yarn.lock
Labels: A0-please QA, A0-please review

#6 Invite Links show commonwealth.im instead of localhost (bug fix)
  client/scripts/views/pages/admin.ts
Labels: A0-please review

#10 Fix chain switching from edgeware to kusama.
  client/scripts/controllers/chain/substrate/shared.ts
Labels: A0-please review

#15 Add tests for UpdateTags Route
  server/router.ts
  test/unit/api/tags.spec.ts
  test/util/modelUtils.ts
Labels: A0-please review

#16 Add prerender flag
  server.ts
Labels: A0-please review, A3-needs resolving

#18 Adding Privacy Features to Threads
  client/scripts/controllers/server/threads.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/views/components/inline_thread_composer.ts
  client/scripts/views/pages/threads/index.ts
  client/scripts/views/pages/view_proposal.ts
  server-test.ts
  server/migrations/20200414143124-add-privacy-features-to-threads.js
  server/models/offchain_thread.ts
  server/models/role.ts
  server/router.ts
  server/routes/bulkThreads.ts
  server/routes/createThread.ts
  server/routes/editThread.ts
  test/unit/api/threads.spec.ts
  test/util/modelUtils.ts
Labels: A0-please review, A3-needs resolving

#23 Switch CircleCI tests to API only.
  .circleci/config.yml
Labels: A0-please review

#22 Comment/Thread edit bug fixed when no change occurs
  client/scripts/views/pages/view_proposal.ts
Labels: A0-please QA, A0-please review

#25 Fix count and remove dispatch queue proposals from page.
  client/scripts/views/components/header.ts
  client/scripts/views/pages/proposals.ts
Labels: A7-looks good

#26 Separate chainAdapterReady from chainModuleReady.
  client/scripts/app.ts
  client/scripts/controllers/chain/cosmos/account.ts
  client/scripts/controllers/chain/cosmos/main.ts
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/ethereum/main.ts
  client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  client/scripts/controllers/chain/near/main.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/mithril.ts
  client/scripts/state.ts
Labels: A0-please review

#17 Stores global lockdrop stats and serves them instead of using INFURA
  client/scripts/views/stats/edgeware.ts
  client/scripts/views/stats/stats_helpers.ts
  package.json
  server.ts
  server/migrations/20200414195212-add_edgeware_lockdrop_summary_everything.js
  server/models/edgeware_lockdrop_everything.ts
  server/router.ts
  server/routes/getEdgewareLockdropLookup.ts
  server/routes/getEdgewareLockdropStats.ts
Labels: A0-please QA, A0-please review

#33 Fix reaction tooltip for offchain communities
  client/scripts/controllers/server/reactions.ts
  client/scripts/models/OffchainReaction.ts
  client/scripts/views/components/reaction_button.ts
Labels: A0-please QA, A0-please review

#47 Bug Fix: Add server check to prevent comment creation on "read only" threads
  server/routes/createComment.ts
Labels: A0-please review

#9 Emit user notifications from chain events.
  .circleci/config.yml
  .eslintrc.json
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/models/ChainEvent.ts
  client/scripts/models/ChainEventType.ts
  client/scripts/models/Notification.ts
  client/scripts/models/index.ts
  client/scripts/views/components/header.ts
  client/scripts/views/components/settings/send_edg_well.ts
  client/scripts/views/pages/subscriptions.ts
  client/styles/pages/subscriptions.scss
  eventSubscriber.ts
  package.json
  server-test.ts
  server.ts
  server/database.ts
  server/eventHandlers/edgeware.ts
  server/migrations/20200415152936-add-chain-events.js
  server/migrations/20200417182339-add-notif-category.js
  server/models/chain_event.ts
  server/models/chain_event_type.ts
  server/models/chain_node.ts
  server/models/notification.ts
  server/models/subscription.ts
  server/routes/createComment.ts
  server/routes/createCommunity.ts
  server/routes/createThread.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
  server/routes/viewNotifications.ts
  server/scripts/resetServer.ts
  server/scripts/setupChainEventListeners.ts
  shared/adapters/chain/substrate/subscriptions.ts
  shared/adapters/currency.ts
  shared/events/README.md
  shared/events/edgeware/filters/enricher.ts
  shared/events/edgeware/filters/labeler.ts
  shared/events/edgeware/filters/titler.ts
  shared/events/edgeware/filters/type_parser.ts
  shared/events/edgeware/index.ts
  shared/events/edgeware/poller.ts
  shared/events/edgeware/processor.ts
  shared/events/edgeware/subscriber.ts
  shared/events/edgeware/types.ts
  shared/events/interfaces.ts
  shared/types.ts
  test/mocha.opts
  test/unit/events/edgeware/enricher.spec.ts
  test/unit/events/edgeware/eventHandler.spec.ts
  test/unit/events/edgeware/poller.spec.ts
  test/unit/events/edgeware/processor.spec.ts
  test/unit/events/edgeware/subscriber.spec.ts
  test/unit/events/edgeware/testUtil.ts
  yarn.lock
Labels: A7-looks good

#51 Fix errors from Kusama chain upgrade.
  client/scripts/app.ts
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/views/components/proposal_row.ts
  client/scripts/views/modals/view_voters_modal.ts
  package.json
  shared/adapters/chain/substrate/subscriptions.ts
  yarn.lock
Labels: A0-please review, A7-looks good

#91 Edit Tags from Discussion Row
  client/scripts/views/components/tag_editor.ts
  client/scripts/views/pages/discussions/discussion_row.ts
Labels: A0-please review

#88 Alphabetical Tags & Tag Page w/ Title + Description
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/index.ts
Labels: A0-please review

#111 Edit, Delete, Reply added to carat menu
  client/scripts/controllers/server/comments.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
Labels: A0-please review

#134 Fixes signaling voting actions and display bug
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/pages/new_signaling.ts
  client/scripts/views/pages/proposals.ts
Labels: A0-please QA, A0-please review

#108 Fixes test script cmd, fixes edit comment
  client/scripts/controllers/server/comments.ts
  server/models/subscription.ts
  server/routes/updateCommunity.ts
  server/routes/viewReactions.ts
  server/util/lookupAddressIsOwnedByUser.ts
  server/util/lookupCommunityIsVisibleToUser.ts
  test/unit/adapters/index.spec.ts
  test/unit/api/invites.spec.ts
  test/unit/api/threads.spec.ts
  test/util/api.spec.ts
  test/util/modelUtils.ts
Labels: A0-please QA, A0-please review

#144 Fix Kusama preimage due to chain upgrade.
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  shared/adapters/chain/substrate/subscriptions.ts
Labels: A0-please review
