Repository hicommonwealth/commonwealth, pull requests merged in 2020-07, with the labels that each got.

#418 Discussion Drafts
  client/scripts/app.ts
  client/scripts/controllers/server/drafts.ts
  client/scripts/controllers/server/reactions.ts
  client/scripts/controllers/server/tags.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/controllers/server/user/base.ts
  client/scripts/models/DiscussionDraft.ts
  client/scripts/models/index.ts
  client/scripts/stores/DraftStore.ts
  client/scripts/stores/ReactionStore.ts
  client/scripts/stores/TagStore.ts
  client/scripts/stores/index.ts
  client/scripts/views/components/autocomplete_tag_form.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/modals/new_thread_modal.ts
  client/scripts/views/pages/new_thread.ts
  client/scripts/views/pages/threads/index.ts
  client/styles/components/new_thread_form.scss
  client/styles/modals/new_thread_modal.scss
  client/styles/pages/new_thread.scss
  package.json
  server/migrations/20200608192629-add-discussion-drafts.js
  server/migrations/20200622214214-switch-author-id-to-address-id.js
  server/models/discussion_draft.ts
  server/models/offchain_thread.ts
  server/router.ts
  server/routes/bulkThreads.ts
  server/routes/createComment.ts
  server/routes/createThread.ts
  server/routes/deleteComment.ts
  server/routes/deleteCommunity.ts
  server/routes/deleteReaction.ts
  server/routes/deleteThread.ts
  server/routes/drafts/createDraft.ts
  server/routes/drafts/deleteDraft.ts
  server/routes/drafts/editDraft.ts
  server/routes/drafts/getDrafts.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
  server/routes/status.ts
  server/routes/updateTags.ts
  test/unit/api/drafts.spec.ts
Labels: 13, A0-please QA, A0-please review, bug, enhancement

#467 'Edit Tag' modal now closes
  client/scripts/views/components/tag_editor.ts
  client/scripts/views/pages/view_proposal/index.ts
Labels: 1, bug

#453 Latest design iteration of validator page with responsive preheaders and table along with addition of validator sorting, Twitter like on-chain identity tooltip, APR calculations for validators
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/staking.ts
  client/scripts/controllers/server/chain_events.ts
  client/scripts/views/pages/validators/index.ts
  client/scripts/views/pages/validators/substrate/card_summary.ts
  client/scripts/views/pages/validators/substrate/identity.ts
  client/scripts/views/pages/validators/substrate/preheader.ts
  client/scripts/views/pages/validators/substrate/presentation_component.ts
  client/scripts/views/pages/validators/substrate/recent_block.ts
  client/scripts/views/pages/validators/substrate/validator_row.ts
  client/scripts/views/pages/validators/substrate/validator_row_waiting.ts
  client/styles/pages/validators.scss
  package.json
  server/router.ts
  server/routes/deleteAddress.ts
  server/routes/getOffences.ts
  server/routes/getRewards.ts
  shared/events/edgeware/filters/enricher.ts
  test/unit/api/events.spec.ts
  yarn.lock
Labels: A0-please QA, Phase 1, enhancement, needs design

#482 Community Website & Chat Attributes
  client/scripts/app.ts
  client/scripts/helpers/index.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/modals/create_community_modal.ts
  client/scripts/views/modals/manage_community_modal/chain_metadata_management_table.ts
  client/scripts/views/modals/manage_community_modal/community_metadata_management_table.ts
  client/scripts/views/modals/manage_community_modal/metadata_rows.ts
  server/migrations/20200714174038-add-website-and-chat-columns-to-communities.js
  server/models/chain.ts
  server/models/offchain_community.ts
  server/routes/updateChain.ts
  server/routes/updateCommunity.ts
  shared/helpers.ts
  test/unit/api/updatecommunity.spec.ts
Labels: 5, A3-needs resolving, bug

#466 Fix saving threads and comments to localStorage
  client/scripts/views/components/empty_channel_placeholder.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/inline_thread_composer.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/components/tag_editor.ts
  client/scripts/views/components/tag_selector.ts
  client/scripts/views/modals/manage_community_modal/chain_metadata_management_table.ts
  client/scripts/views/modals/manage_community_modal/community_metadata_management_table.ts
  client/scripts/views/modals/new_tag_modal.ts
  client/scripts/views/modals/new_thread_modal.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/new_thread.ts
  client/scripts/views/pages/threads/index.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/components/new_thread_form.scss
  client/styles/components/tag_selector.scss
  client/styles/modals/manage_community_modal.scss
  client/styles/pages/view_proposal/index.scss
  server/migrations/20200608192629-add-discussion-drafts.js
  server/routes/updateChain.ts
  server/routes/updateCommunity.ts
Labels: A3-needs resolving, bug

#458 Split server and chain loading logic to defer chain load.
  client/scripts/app.ts
  client/scripts/controllers/chain/cosmos/main.ts
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/ethereum/main.ts
  client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  client/scripts/controllers/chain/ethereum/moloch/governance.ts
  client/scripts/controllers/chain/near/main.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/layout.ts
  client/scripts/views/pages/finish_near_login.ts
  client/scripts/views/pages/settings/settings_well.ts
  shared/events/substrate/subscriber.ts
Labels: 5, 8, A0-please QA, A0-please review, A2-in progress, construct-ui, enhancement

#494 Chain-scoped Settings
  client/scripts/app.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/pages/login.ts
Labels: bug

#495 Fix ShowRole bug.
  client/scripts/views/components/widgets/user.ts
Labels: 1, bug

#483 Profile URL update
  client/scripts/views/components/widgets/substrate_identity.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/profile/profile_comment_group.ts
  client/scripts/views/pages/profile/profile_content.ts
  client/scripts/views/pages/profile/profile_header.ts
  client/scripts/views/pages/profile/profile_proposal.ts
  server/router.ts
  server/routes/getProfile.ts
Labels: 8, A3-needs resolving, enhancement

#504 Community Visibility Boolean
  client/scripts/app.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/views/modals/create_community_modal.ts
  client/scripts/views/pages/home/community_cards.ts
  server/migrations/20200723192319-add-visibility-boolean-to-communities-and-manually-set.js
  server/models/offchain_community.ts
  server/routes/createCommunity.ts
Labels: 1, enhancement

#503 Allow profile page without ?base query when scoped to chain
  client/scripts/views/pages/profile/index.ts
Labels: 1, A0-please QA, bug

#505 Use new version of Chain Events library.
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/edgeware/signaling_proposal.ts
  client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  client/scripts/controllers/chain/ethereum/moloch/governance.ts
  client/scripts/controllers/chain/ethereum/moloch/proposal.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/collective_proposal.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/controllers/chain/substrate/treasury_proposal.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/models/ChainEntity.ts
  client/scripts/models/ChainEvent.ts
  client/scripts/models/ChainEventType.ts
  client/scripts/stores/ChainEntityStore.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/pages/notification-settings.ts
  client/scripts/views/pages/subscriptions.ts
  package.json
  server-test.ts
  server/eventHandlers/entityArchival.ts
  server/eventHandlers/migration.ts
  server/eventHandlers/notifications.ts
  server/eventHandlers/storage.ts
  server/scripts/resetServer.ts
  server/scripts/setupChainEventListeners.ts
  server/util/proposalIdToEntity.ts
  test/unit/events/entityArchivalHandler.spec.ts
  test/unit/events/migrationHandler.spec.ts
  test/unit/events/notificationHandler.spec.ts
  test/unit/events/storageHandler.spec.ts
  yarn.lock
Labels: 2, A0-please review, cleanup

#501 Proposal Reactions
  client/scripts/controllers/server/reactions.ts
  client/scripts/models/OffchainReaction.ts
  client/scripts/stores/ReactionStore.ts
  client/scripts/views/components/reaction_button.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
  server/migrations/20200721141800-add-proposal-id-to-reactions.js
  server/models/chain_entity.ts
  server/models/offchain_reaction.ts
  server/routes/createReaction.ts
  server/util/proposalIdToEntity.ts
Labels: 8, enhancement

#508 Show proposal author in the "replies" column
  client/scripts/controllers/server/comments.ts
  client/scripts/views/pages/discussions/discussion_row.ts
Labels: 1, enhancement

#520 Present login modal from reactions if not logged in
  client/scripts/views/components/reaction_button.ts
Labels: enhancement
