Repository hicommonwealth/commonwealth, pull requests merged in 2020-11, with the labels that each got.

#919 Bug: Chain event listener sends duplicate emails when running on dev
  server/scripts/emails.ts
Labels: 2, bug

#920 Allow community admins to self-demote
  client/scripts/controllers/server/user/roles.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/views/modals/create_invite_modal.ts
  client/scripts/views/modals/manage_community_modal/index.ts
  client/scripts/views/modals/manage_community_modal/metadata_rows.ts
  server/routes/upgradeMember.ts
  test/unit/api/roles.spec.ts
Labels: 5, bug, enhancement

#924 Remove eqeqeq from metadata_rows
  client/scripts/views/modals/manage_community_modal/metadata_rows.ts
Labels: 1, A0-please review

#927 Upgrade versions and add error handling for entity fetch.
  client/scripts/controllers/server/chain_entities.ts
  package.json
  server/scripts/migrateChainEntities.ts
  server/scripts/migrateIdentities.ts
  server/scripts/setupChainEventListeners.ts
  tsconfig.json
  yarn.lock
Labels: 1, A0-please QA, A0-please review

#912 Improve forum thread-fetching
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/identifiers.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/stores/ProposalStore.ts
  client/scripts/stores/TopicScopedThreadStore.ts
  client/scripts/stores/index.ts
  client/scripts/views/pages/admin.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/view_proposal/index.ts
  server/migrations/20201021172024-Remove corrupt root_ids.js
  server/migrations/20201104170708-ensure-legacy-threads-do-not-double-community-and-chain.js
  server/router.ts
  server/routes/bulkOffchain.ts
  server/routes/bulkThreads.ts
  server/routes/getThread.ts
Labels: 13, A0-please QA, A0-please review, enhancement

#936 RecentActivity Optimization
  client/scripts/app.ts
  client/scripts/controllers/app/recent_activity.ts
  client/scripts/controllers/chain/community/main.ts
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/pages/discussions/sidebar.ts
  client/scripts/views/pages/home/community_cards.ts
  server/routes/bulkOffchain.ts
  server/routes/status.ts
Labels: 5, A0-please QA, A0-please review, enhancement

#939 Ensure pinned discussion rows feature a full user gallery
  server/routes/bulkOffchain.ts
Labels: A0-please QA, A0-please review, bug

#944 Ensure clearLocalStorage is properly scoped
  client/scripts/views/components/new_thread_form.ts
Labels: 1, A0-please review, bug

#947 Fix notifications bug
  client/scripts/views/components/header/notifications_menu.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/pages/view_proposal/index.ts
Labels: 3, A0-please QA, A0-please review, bug

#949 Fix buggy batched email notifications
  server/scripts/emails.ts
  shared/notificationFormatter.ts
Labels: 1, bug

#950 Fix ambiguous confirmation modal
  client/scripts/views/modals/link_new_address_modal.ts
Labels: A0-please review

#946 Re-enables preimage display for Democracy entities.
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/helpers/index.ts
  client/scripts/models/IChainAdapter.ts
  server/eventHandlers/storage.ts
  server/migrations/20201119171517-truncate-preimages.js
  server/routes/bulkEntities.ts
  shared/adapters/chain/substrate/types.ts
  test/unit/events/storageHandler.spec.ts
Labels: 8, A0-please QA, A0-please review, bug, enhancement

#942 Ensure user mentions link to correct thread
  server/routes/createComment.ts
Labels: 2, A0-please QA, A0-please review, bug

#933 Voter Card
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/components/proposals/voting_results.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/components/proposals/voting_results.scss
Labels: A0-please QA, A0-please review, enhancement

#943 Ensure subscription deletions cascades
  server/models/subscription.ts
Labels: 1, A0-please QA, A0-please review, bug

#951 Update chain selector
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/settings/settings_well.ts
  client/styles/components/chain_status_indicator.scss
  client/styles/components/sidebar/index.scss
Labels: 5, 8, enhancement

#963 Add OnDelete constraint to Notifications table
  server/migrations/20201124003059-add-on-delete-to-subs.js
Labels: 1, A0-please QA, A0-please review

#962 Ensure ActiveMembers module displays proper user info and roles
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/pages/discussions/sidebar.ts
  client/styles/pages/discussions/sidebar.scss
Labels: 3, A0-please QA, A0-please review, P1, bug

#965 Store Last Active Date on Address Model, add to view
  client/scripts/controllers/app/recent_activity.ts
  client/scripts/controllers/server/profiles.ts
  client/scripts/models/Profile.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/pages/profile/index.ts
  client/styles/components/quill_editor.scss
  server/migrations/20201124224946-add-last-active-to-address.js
  server/models/address.ts
  server/routes/createComment.ts
  server/routes/createReaction.ts
  server/routes/createThread.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
  server/routes/setDefaultRole.ts
Labels: 5, A0-please QA, enhancement

#964 "Join Community" Profile Banner
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/profile/profile_banner.ts
  client/scripts/views/pages/profile/profile_header.ts
  client/styles/pages/profile.scss
Labels: 2, A0-please QA, A0-please review, enhancement
