Repository hicommonwealth/commonwealth, pull requests merged in 2020-10, with the labels that each got.

#859 Optimize recentActivity /status call
  client/scripts/controllers/app/recent_activity.ts
  client/scripts/controllers/server/reactions.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/models/AbridgedThread.ts
  client/scripts/models/index.ts
  client/scripts/stores/ActivityStore.ts
  client/scripts/stores/ReactionStore.ts
  client/scripts/views/pages/discussions/sidebar.ts
  client/scripts/views/pages/home/community_cards.ts
  server/routes/status.ts
Labels: 5, A0-please QA, A0-please review, enhancement

#853 Bump API, chain-events, node-types versions.
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/kulupu/main.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/phragmen_election.ts
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/modals/council_voting_modal.ts
  client/scripts/views/modals/tx_signing_modal.ts
  package.json
  server/routes/createReaction.ts
  yarn.lock
Labels: 1, A0-please QA, A0-please review

#847 Transfer users to their chain profile to set on-chain identity
  client/scripts/controllers/app/login.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/profile/profile_header.ts
Labels: 5, A0-please QA, A0-please review, enhancement

#866 Update setActiveAccount invocation to async
  client/scripts/app.ts
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/chain/ethereum/main.ts
  client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/pages/finish_near_login.ts
Labels: 1, A0-please review

#863 Ungroup unread notifications
  client/scripts/helpers/notifications.ts
Labels: 1, A0-please QA, bug

#880 Add timeout flag to Substrate chain.
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/views/pages/council/index.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/proposals.ts
  client/scripts/views/pages/referenda.ts
  client/scripts/views/pages/treasury.ts
Labels: 3, A0-please QA, A0-please review, cleanup, enhancement

#878 Add per-module Substrate loading.
  client/scripts/app.ts
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/edgeware/shared.ts
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  client/scripts/controllers/chain/ethereum/moloch/chain.ts
  client/scripts/controllers/chain/ethereum/moloch/governance.ts
  client/scripts/controllers/chain/kulupu/main.ts
  client/scripts/controllers/chain/kusama/main.ts
  client/scripts/controllers/chain/plasm/main.ts
  client/scripts/controllers/chain/polkadot/main.ts
  client/scripts/controllers/chain/stafi/main.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/identities.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/phragmen_elections.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/identifiers.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/ProposalModule.ts
  client/scripts/views/layout.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/pages/council/index.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/new_signaling.ts
  client/scripts/views/pages/proposals.ts
  client/scripts/views/pages/referenda.ts
  client/scripts/views/pages/treasury.ts
  client/scripts/views/pages/view_proposal/index.ts
  package.json
  yarn.lock
Labels: 8, A3-needs resolving, cleanup, enhancement

#864 Community Switcher
  client/scripts/controllers/server/user/base.ts
  client/scripts/controllers/server/user/roles.ts
  client/scripts/models/RoleInfo.ts
  client/scripts/views/components/sidebar/community_selector.ts
  client/styles/components/sidebar/community_selector.scss
Labels: 3, A3-needs resolving, enhancement

#883 Ensure User popover is hoverable
  client/scripts/views/components/notification_row.ts
  client/scripts/views/components/proposal_row.ts
  client/scripts/views/components/proposals/voting_results.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/components/widgets/user_gallery.ts
  client/scripts/views/modals/manage_community_modal/metadata_rows.ts
  client/scripts/views/modals/view_voters_modal.ts
  client/scripts/views/pages/council/council_row.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/sidebar.ts
  client/scripts/views/pages/profile/profile_comment_group.ts
  client/scripts/views/pages/settings/linked_addresses_well.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/styles/components/sidebar/notification_row.scss
  client/styles/components/widgets/user.scss
Labels: 2, A0-please QA, A0-please review, bug

#885 Fix duplicate Sublayouts on New Proposal pages
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/views/pages/loading.ts
  client/scripts/views/pages/new_proposal/index.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
Labels: bug

#886 Treasury Bond Fix
  shared/adapters/currency.ts
Labels: bug

#884 Pass author link to SendGrid
  server/scripts/emails.ts
  shared/notificationFormatter.ts
Labels: 1, enhancement

#887 Un-starring causes weird cascade of un-starring
  client/scripts/controllers/server/communities.ts
  client/scripts/controllers/server/user/base.ts
  client/scripts/views/components/sidebar/community_selector.ts
Labels: 2, A0-please QA, bug

#905 Bug fix: double roles on hot-reload
  client/scripts/controllers/server/user/base.ts
Labels: 1, A0-please QA, bug

#904 Disable "name" field in Edit Profile modal if user has set an on-chain identity
  client/scripts/views/modals/edit_profile_modal.ts
Labels: 1, A0-please QA, bug

#900 Add disabled state to Notification settings dropdowns
  client/scripts/views/pages/notifications.ts
Labels: 2, A0-please QA, bug

#901 Add chain event types underneath each chain event category
  client/scripts/views/pages/notifications.ts
  client/styles/pages/notifications.scss
Labels: 1, A0-please QA, enhancement

#903 Add confirmation modal on deleting draft
  client/scripts/views/components/new_thread_form.ts
Labels: enhancement

#902 Clearable Chain Event Notifications
  client/scripts/controllers/server/notifications.ts
  client/scripts/views/components/header/notifications_menu.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/pages/notificationsList.ts
  client/styles/components/sidebar/notification_row.scss
  server/router.ts
  server/routes/clearNotifications.ts
Labels: 2, A0-please review, enhancement

#910 Ensure chain notifications send a full label in the email
  server/models/subscription.ts
  server/scripts/emails.ts
Labels: 1, A0-please QA, bug

#918 Fix non-persisting selection in Create Invite Modal
  client/scripts/views/modals/create_invite_modal.ts
Labels: 1, bug

#917 Fix Discussion Drafts copy & button functionality
  client/scripts/views/components/new_thread_form.ts
Labels: 1, bug
