Repository hicommonwealth/commonwealth, pull requests merged in 2020-05, with the labels that each got.

#143 Add Tags on Tag Page
  client/scripts/controllers/chain/community/main.ts
  client/scripts/controllers/server/tags.ts
  client/scripts/views/components/sidebar/tag_selector.ts
  client/scripts/views/modals/input_modal.ts
  client/scripts/views/pages/subscriptions.ts
  server/router.ts
  server/routes/createTag.ts
  test/unit/api/tags.spec.ts
Labels: A0-please review

#140 Feature tag button on tags page
  client/scripts/views/components/sidebar/tag_selector.ts
  client/scripts/views/pages/tags.ts
  client/styles/components/sidebar/tag_selector.scss
  server/routes/updateCommunity.ts
  server/scripts/resetServer.ts
Labels: A0-please QA

#57 Emit events for chain notifications (re-posted after revert)
  .circleci/config.yml
  .eslintrc.json
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/models/ChainEvent.ts
  client/scripts/models/ChainEventType.ts
  client/scripts/models/Notification.ts
  client/scripts/models/index.ts
  client/scripts/views/components/header.ts
  client/scripts/views/components/settings/send_edg_well.ts
  client/scripts/views/pages/subscriptions.ts
  client/styles/pages/subscriptions.scss
  eventSubscriber.ts
  package.json
  server-test.ts
  server.ts
  server/database.ts
  server/eventHandlers/edgeware.ts
  server/migrations/20200415152936-add-chain-events.js
  server/migrations/20200417182339-add-notif-category.js
  server/models/chain_event.ts
  server/models/chain_event_type.ts
  server/models/chain_node.ts
  server/models/notification.ts
  server/models/subscription.ts
  server/routes/createComment.ts
  server/routes/createCommunity.ts
  server/routes/createReaction.ts
  server/routes/createThread.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
  server/routes/viewNotifications.ts
  server/scripts/resetServer.ts
  server/scripts/setupChainEventListeners.ts
  shared/adapters/currency.ts
  shared/events/README.md
  shared/events/edgeware/filters/enricher.ts
  shared/events/edgeware/filters/labeler.ts
  shared/events/edgeware/filters/titler.ts
  shared/events/edgeware/filters/type_parser.ts
  shared/events/edgeware/index.ts
  shared/events/edgeware/poller.ts
  shared/events/edgeware/processor.ts
  shared/events/edgeware/subscriber.ts
  shared/events/edgeware/types.ts
  shared/events/interfaces.ts
  shared/types.ts
  test/mocha.opts
  test/unit/events/edgeware/enricher.spec.ts
  test/unit/events/edgeware/eventHandler.spec.ts
  test/unit/events/edgeware/poller.spec.ts
  test/unit/events/edgeware/processor.spec.ts
  test/unit/events/edgeware/subscriber.spec.ts
  test/unit/events/edgeware/testUtil.ts
Labels: A0-please QA, A0-please review

#158 Fixes editThread read_only switching on edit
  client/scripts/controllers/server/threads.ts
  server/routes/editThread.ts
  test/unit/api/index.spec.ts
  test/unit/api/subscriptions.spec.ts
  test/unit/api/threads.spec.ts
Labels: A0-please QA, A0-please review

#170 Remove unnecessary console logs
  client/scripts/controllers/server/tags.ts
Labels: A0-please review

#168 Subscription Button in Thread Carat on Discussion Page
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/thread_carat_menu.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/pages/view_proposal/header.scss
Labels: A0-please QA, A0-please review

#196 Fixes create invite logic and adds many tests
  server/passport.ts
  server/routes/createCommunity.ts
  server/routes/createInvite.ts
  server/routes/webhooks/errors.ts
  test/unit/api/invites.spec.ts
  test/unit/api/threads.spec.ts
  test/unit/api/webhooks.spec.ts
  test/util/modelUtils.ts
Labels: A0-please QA, A0-please review

#58 Community Management Panel for Admins
  client/scripts/models/ChainInfo.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/views/components/admin_panel/admin_panel_contents.ts
  client/scripts/views/components/admin_panel/admin_tab_panel.ts
  client/scripts/views/components/admin_panel/chain_metadata_management_table.ts
  client/scripts/views/components/admin_panel/community_metadata_management_table.ts
  client/scripts/views/components/admin_panel/index.ts
  client/scripts/views/components/admin_panel/input_property_row.ts
  client/scripts/views/components/admin_panel/manage_roles_row.ts
  client/scripts/views/components/admin_panel/toggle_property_row.ts
  client/scripts/views/components/admin_panel/upgrade_roles_form.ts
  client/scripts/views/components/admin_panel/webhooks_tab.ts
  client/scripts/views/components/sidebar/index.ts
  client/styles/components/admin_panel.scss
  server/models/role.ts
  server/routes/updateChain.ts
  server/routes/updateCommunity.ts
  server/routes/upgradeMember.ts
Labels: A0-please review, A5-seems ok

#189 Adds lazy payout modal to validator pages and support with Kusama/Edgeware
  client/scripts/app.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/views/components/header.ts
  client/scripts/views/pages/validators/index.ts
  client/scripts/views/pages/validators/substrate.ts
  client/scripts/views/pages/validators/substrate/action_form.ts
  client/scripts/views/pages/validators/substrate/claim_payout.ts
  client/scripts/views/pages/validators/substrate/controller_form.ts
  client/scripts/views/pages/validators/substrate/index.ts
  client/scripts/views/pages/validators/substrate/manage_staking.ts
  client/scripts/views/pages/validators/substrate/new_stash_form.ts
  client/scripts/views/pages/validators/substrate/preheader.ts
  client/scripts/views/pages/validators/substrate/presentation_component.ts
  client/scripts/views/pages/validators/substrate/stash_form.ts
  client/scripts/views/pages/validators/substrate/validator_row.ts
Labels: A0-please review

#197 Fixes accept invite logic and adds more tests
  server/routes/acceptInvite.ts
  test/unit/api/invites.spec.ts
  test/util/modelUtils.ts
Labels: A0-please QA, A0-please review

#190 Community Switcher Account Change Bug
  client/scripts/views/components/community_switcher.ts
Labels: A0-please QA

#191 Fix "New Post" Button
  client/scripts/views/components/new_proposal_button.ts
Labels: A0-please QA, A0-please review

#194 Comment Refresh Bug Fix
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
Labels: A0-please QA

#202 Proper Tag Scoping
  client/scripts/controllers/chain/community/main.ts
  client/scripts/controllers/server/tags.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/views/components/sidebar/tag_selector.ts
  server/router.ts
Labels: A0-please review, A3-needs resolving

#221 Construct Modal Phaseout
  client/scripts/app.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/modals/proposals/index.ts
  client/scripts/views/modals/proposals/new_proposal_form.ts
  client/scripts/views/pages/council.ts
  client/scripts/views/pages/new_proposal/index.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/new_thread.ts
  client/scripts/views/pages/proposals.ts
  client/styles/pages/new_proposal_page.scss
Labels: cleanup

#219 Adds more tests for discussion routes and fixes up some style
  server/routes/createComment.ts
  server/routes/createThread.ts
  server/routes/editThread.ts
  test/unit/api/subscriptions.spec.ts
  test/unit/api/threads.spec.ts
  test/unit/api/webhooks.spec.ts
  test/util/modelUtils.ts
Labels: A0-please review

#236 Update Substrate node URLs
  server/migrations/20200522152856-update-substrate-urls.js
Labels: bug

#217 Notification Deduplication and NotificationMenu Refactor
  client/scripts/helpers/notifications.ts
  client/scripts/views/components/header.ts
  client/scripts/views/components/notifications_dropdown_menu.ts
  client/scripts/views/components/sidebar/notification_row.ts
  test/unit/api/subscriptions.spec.ts
Labels: A0-please review, enhancement

#244 commission api integrated for validators screen
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/views/pages/validators/index.ts
  client/scripts/views/pages/validators/substrate/presentation_component.ts
  client/scripts/views/pages/validators/substrate/validator_row.ts
Labels: A0-please QA, A2-in progress

#269 Refactor identity calls to use module with cache.
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/identities.ts
  client/scripts/controllers/chain/substrate/identity.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/modals/edit_identity_modal.ts
  client/scripts/views/pages/profile/profile_header.ts
Labels: 1, A0-please QA, A0-please review, bug, enhancement

#263 Unit Tests for Roles, Invites, Subscriptions-related Routes.
  server/routes/createInviteLink.ts
  server/routes/createRole.ts
  server/routes/deleteRole.ts
  server/routes/upgradeMember.ts
  test/unit/api/invites.spec.ts
  test/unit/api/roles.spec.ts
  test/unit/api/subscriptions.spec.ts
  test/unit/api/tags.spec.ts
  test/unit/api/threads.spec.ts
Labels: A0-please review, A5-seems ok, testing

#245 /editTag Tests
  client/scripts/controllers/server/tags.ts
  server/routes/editComment.ts
  server/routes/editTag.ts
  test/unit/api/invites.spec.ts
  test/unit/api/tags.spec.ts
  test/util/modelUtils.ts
Labels: A3-needs resolving, testing

#278 Fix app.comments.refreshAll
  client/scripts/controllers/chain/community/main.ts
  client/scripts/controllers/server/comments.ts
  client/scripts/models/IChainAdapter.ts
Labels: 1, bug

#215 nv3: Immediate Emails and Name Change
  client/scripts/app.ts
  client/scripts/controllers/server/notifications.ts
  client/scripts/models/NotificationSubscription.ts
  client/scripts/views/components/community_menu.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/components/sidebar/subscription_button.ts
  client/scripts/views/pages/notification_list.ts
  client/scripts/views/pages/notifications.ts
  client/styles/pages/subscriptions.scss
  server/migrations/20200511160035-add-immediate-email-column-to-subscription-model.js
  server/models/subscription.ts
  server/router.ts
  server/routes/subscription/createSubscription.ts
  server/routes/subscription/deleteSubscription.ts
  server/routes/subscription/disableImmediateEmails.ts
  server/routes/subscription/disableSubscriptions.ts
  server/routes/subscription/enableImmediateEmails.ts
  server/routes/subscription/enableSubscriptions.ts
  server/routes/subscription/errors.ts
  server/routes/subscription/viewSubscriptions.ts
  server/scripts/emails.ts
  server/scripts/resetServer.ts
  test/unit/api/subscriptions.spec.ts
  test/unit/api/threads.spec.ts
Labels: A0-please review
