Repository hicommonwealth/commonwealth, pull requests merged in 2020-09, with the labels that each got.

#713 Add title-editing capabilities to thread
  client/scripts/controllers/server/threads.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/pages/view_proposal/index.scss
  server/routes/editThread.ts
  test/unit/api/threads.spec.ts
Labels: 2, enhancement

#695 Near Accounts not loading
  client/scripts/app.ts
Labels: 2, A0-please review, bug

#669 Bug Fix: Cannot add immediate email notifications for new threads in a community
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/pages/subscriptions/notificationSettings.ts
  server/migrations/20200826183259-add-subscriptions-for-roles.js
Labels: 3, A0-please QA, bug

#711 Fix nonce error for CLI signing.
  client/scripts/controllers/chain/substrate/shared.ts
Labels: 1, A0-please QA, A0-please review, bug

#700 Update Invite Members module to support chains
  client/scripts/views/components/sidebar/community_info_module.ts
  client/scripts/views/modals/create_invite_modal.ts
  client/styles/modals/create_invite_modal.scss
  server/routes/addMember.ts
Labels: 2, A0-please review, enhancement

#715 Extend scroll-saving logic to proposal pages
  client/scripts/views/components/proposal_row.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/proposals.ts
Labels: 2, A0-please QA, A0-please review, enhancement

#716 Load Treasury Proposal on Proposal Page
  client/scripts/controllers/chain/substrate/treasury.ts
Labels: 3, enhancement

#717 Update user's lastVisited timestamp on thread & comment creation
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/views/components/new_thread_form.ts
Labels: 1, A0-please QA, enhancement

#727 [WIP] Use on-chain identities from server.
  client/scripts/controllers/chain/substrate/identity.ts
  client/scripts/controllers/server/profiles.ts
  client/scripts/models/Profile.ts
  client/scripts/views/components/widgets/substrate_identity.ts
  client/scripts/views/pages/profile/index.ts
Labels: 2, A0-please QA, A2-in progress, cleanup, enhancement

#722 Add email invite to chain community
  client/scripts/views/modals/create_invite_modal.ts
  server/migrations/20200902215741-add-chain-info-to-invite-code.js
  server/models/invite_code.ts
  server/routes/createInvite.ts
Labels: 3, A0-please review

#728 Correct runners-up count in council stats
  client/scripts/views/pages/council/index.ts
Labels: A0-please review, bug

#710 Added Migration for imonline events enriched in chain-events-#17
  server/migrations/20200901134439-add-imonline-event.js
Labels: A0-please review, enhancement

#739 Un-batch certain notifications
  client/scripts/helpers/notifications.ts
Labels: 3

#748 New Threads batched notif has space typo
  client/scripts/views/components/notification_row.ts
Labels: 1, bug

#749 Batched Notification unread count fix
  client/scripts/views/components/header/notifications_menu.ts
Labels: 1, bug

#737 Admin Panel upgradeMembership UI improvements
  client/scripts/views/modals/manage_community_modal/admin_panel_tabs.ts
Labels: 1, cleanup, enhancement

#751 Extend localStorage to comment and thread editing
  client/scripts/views/components/inline_thread_composer.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
Labels: 5, A0-please QA, A0-please review, enhancement

#750 Profile Refreshes on Update
  client/scripts/views/components/widgets/user.ts
Labels: 1, A0-please QA, bug

#747 NewProposalMenu: Council Items
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/pages/council/index.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/sublayout.ts
  client/styles/pages/council.scss
Labels: A3-needs resolving, enhancement

#757 Make Entity Migration properly re-entrant.
  server/eventHandlers/entityArchival.ts
  server/scripts/migrateChainEntities.ts
  test/unit/events/entityArchivalHandler.spec.ts
Labels: 1, A0-please QA, A0-please review, bug, enhancement

#758 Bump API version for ApiPromise fix.
  client/scripts/views/components/notification_row.ts
  package.json
  server.ts
  server/routes/updateProfile.ts
  server/scripts/migrateChainEntities.ts
  server/scripts/migrateIdentities.ts
  server/scripts/resetServer.ts
  server/scripts/setupChainEventListeners.ts
  yarn.lock
Labels: 2, A0-please QA, A0-please review, bug, cleanup

#753 Add exclusion list for chain event db storage.
  server/eventHandlers/storage.ts
  server/scripts/setupChainEventListeners.ts
  test/unit/events/storageHandler.spec.ts
Labels: 1, A0-please QA, A0-please review, cleanup, enhancement

#606 Review Changes for #555 #556 #594
  client/scripts/controllers/server/chain_events.ts
  server/router.ts
  server/routes/getExposureOverTime.ts
  server/routes/getImOnline.ts
  server/routes/getNominatorsOverTime.ts
  server/routes/getOffences.ts
  server/routes/getOtherStakeOverTime.ts
  server/routes/getOwnStakeOverTime.ts
  server/routes/getRewards.ts
  server/routes/getTotalStakeOverTime.ts
  test/unit/api/events.spec.ts
Labels: A0-please review, A3-needs resolving

#772 Admins User Component not loading in Admin Panel
  client/scripts/views/modals/manage_community_modal/metadata_rows.ts
Labels: 1, A0-please QA

#756 Topicless forum posts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/modals/new_thread_modal.ts
  client/scripts/views/pages/new_thread.ts
  client/scripts/views/pages/threads/index.ts
  server/models/offchain_thread.ts
  server/routes/createThread.ts
  test/unit/api/threads.spec.ts
  test/unit/api/updatecommunity.spec.ts
  test/util/modelUtils.ts
Labels: 5, A0-please QA, A0-please review

#631 Manage Staking and Validator Groups
  client/scripts/app.ts
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/controllers/chain/substrate/staking.ts
  client/scripts/controllers/server/chain_events.ts
  client/scripts/lib/util.js
  client/scripts/views/pages/manage_staking/groups/group_list.ts
  client/scripts/views/pages/manage_staking/groups/new_group.ts
  client/scripts/views/pages/manage_staking/index.ts
  client/scripts/views/pages/manage_staking/substrate/address_info.ts
  client/scripts/views/pages/manage_staking/substrate/bond.ts
  client/scripts/views/pages/manage_staking/substrate/format_balance.ts
  client/scripts/views/pages/manage_staking/substrate/index.ts
  client/scripts/views/pages/manage_staking/substrate/list_nominees.ts
  client/scripts/views/pages/manage_staking/substrate/new_nominator.ts
  client/scripts/views/pages/manage_staking/substrate/new_validator.ts
  client/scripts/views/pages/manage_staking/substrate/nominate.ts
  client/scripts/views/pages/manage_staking/substrate/preheader.ts
  client/scripts/views/pages/manage_staking/substrate/presentation_component.ts
  client/scripts/views/pages/manage_staking/substrate/session_key.ts
  client/scripts/views/pages/manage_staking/substrate/set_nominators.ts
  client/scripts/views/pages/manage_staking/substrate/set_session_key.ts
  client/scripts/views/pages/manage_staking/substrate/set_validator.ts
  client/scripts/views/pages/manage_staking/substrate/stake_list.ts
  client/scripts/views/pages/manage_staking/substrate/stake_row.ts
  client/scripts/views/pages/manage_staking/substrate/stash_controller.ts
  client/scripts/views/pages/manage_staking/substrate/validate.ts
  client/scripts/views/pages/manage_staking/substrate/validate_amount.ts
  client/scripts/views/pages/manage_staking/substrate/validate_controller.ts
  client/scripts/views/pages/spinner.ts
  client/scripts/views/pages/validators/substrate/preheader.ts
  client/scripts/views/pages/validators/substrate/presentation_component.ts
  client/styles/layout.scss
  client/styles/modal.scss
  client/styles/pages/validators.scss
  server/migrations/20190510184156-setup.js
  server/migrations/20200725082952-chain_stake.js
  server/migrations/20200912095852-create-validator-group.js
  server/models/chain_stake.ts
  server/models/validator_group.ts
  server/router.ts
  server/routes/createChainStake.ts
  server/routes/createValidatorGroup.ts
  server/routes/getChainStake.ts
  server/routes/getValidatorGroup.ts
  test/unit/api/validatorGroup.spec.ts
Labels: A0-please QA, A0-please review, Phase 2, enhancement

#632 Added /getSlashes #628
  client/scripts/controllers/server/chain_events.ts
  server/router.ts
  server/routes/getExposureOverTime.ts
  server/routes/getSlashes.ts
  test/unit/api/events.spec.ts
Labels: A0-please review, A3-needs resolving

#786 Add callback to Voting Action button to re-enable onModalClose
  client/scripts/controllers/chain/cosmos/proposal.ts
  client/scripts/controllers/chain/edgeware/signaling_proposal.ts
  client/scripts/controllers/chain/substrate/collective_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/views/components/proposals/voting_actions.ts
Labels: 2, bug

#785 Display "Could not connect to chain" in login modal when chain fails to connect
  client/scripts/views/modals/link_new_address_modal.ts
Labels: 2, bug

#780 Display recent activity in homepage community cards
  client/scripts/app.ts
  client/scripts/state.ts
  client/scripts/views/components/widgets/user_gallery.ts
  client/scripts/views/pages/home/community_cards.ts
  client/styles/components/widgets/user_gallery.scss
  client/styles/pages/home/community_cards.scss
  server/routes/status.ts
Labels: 8, A0-please QA, A0-please review, enhancement

#778 Fix links to proposals via comments/threads on Profile Page
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/profile/profile_comment_group.ts
  client/scripts/views/pages/profile/profile_proposal.ts
Labels: 2, A0-please QA

#769 Webhooks upgrade
  client/scripts/helpers/chain_notification_types.ts
  client/scripts/models/Webhook.ts
  client/scripts/models/index.ts
  client/scripts/views/modals/manage_community_modal/admin_panel_tabs.ts
  client/scripts/views/modals/manage_community_modal/index.ts
  client/scripts/views/modals/webhook_settings_modal.ts
  client/styles/modals/manage_community_modal.scss
  client/styles/modals/webhook_settings_modal.scss
  server/eventHandlers/notifications.ts
  server/migrations/20200909001459-add-category-type-to-webhook-model.js
  server/models/webhook.ts
  server/router.ts
  server/routes/createComment.ts
  server/routes/createReaction.ts
  server/routes/createThread.ts
  server/routes/webhooks/updateWebhook.ts
  server/socket/index.ts
  server/webhookNotifier.ts
Labels: 8, A0-please QA, enhancement

#791 Profile page doesn't 404 but loads empty profile
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/profile/profile_header.ts
Labels: 2, A0-please QA

#622 tentative working version of better chain event emails
  server/models/subscription.ts
  server/scripts/emails.ts
Labels: A0-please QA, A1-reviewed not ready

#784 Add redraw to link new address modal
  client/scripts/views/modals/link_new_address_modal.ts
Labels: 1, bug

#767 Staking Calculator
  client/scripts/app.ts
  client/scripts/helpers/calculator_helper.ts
  client/scripts/models/AssetInfo.ts
  client/scripts/models/ChainConstant.ts
  client/scripts/views/components/staking_calculator_returns.ts
  client/scripts/views/pages/staking_calculator/chain_constants.ts
  client/scripts/views/pages/staking_calculator/staking_calculator.ts
  client/styles/pages/staking_calculator.scss
  client/styles/pages/validators.scss
  server/router.ts
  server/routes/getUSDvalue.ts
Labels: A0-please review, enhancement

#813 Fix Discord Template for Webhooks
  client/scripts/views/components/notification_row.ts
  client/scripts/views/components/quill_formatted_text.ts
  server/routes/createComment.ts
  server/routes/createReaction.ts
  server/routes/createThread.ts
  server/webhookNotifier.ts
  shared/helpers.ts
Labels: 1, A0-please QA, bug

#815 Update unread threads on discussions index
  client/scripts/views/pages/discussions/index.ts
Labels: 1, A0-please QA, A0-please review, bug

#816 Updates chat application
  client/scripts/app.ts
  client/scripts/controllers/server/socket/chat.ts
  client/scripts/controllers/server/socket/index.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/chat.ts
  client/styles/pages/chat.scss
  server/socket/index.ts
  shared/types.ts
Labels: enhancement

#819 New Mention notification always includes thread title
  client/scripts/views/components/notification_row.ts
Labels: 1, A0-please QA, bug

#818 Optimize Chain/Community loading by fetching all Offchain data in a single query
  client/scripts/controllers/chain/community/main.ts
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/reactions.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/controllers/server/topics.ts
  client/scripts/models/IChainAdapter.ts
  server/router.ts
  server/routes/bulkOffchain.ts
Labels: 3, A0-please review, enhancement

#823 Fix missing comments bug
  client/scripts/views/pages/view_proposal/index.ts
Labels: 3, A0-please QA, A0-please review, bug

#814 Sidebar: Active Members Module
  client/scripts/app.ts
  client/scripts/controllers/app/recent_activity.ts
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/reactions.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/helpers/index.ts
  client/scripts/state.ts
  client/scripts/stores/ActivityStore.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/discussions/sidebar.ts
  client/scripts/views/pages/home/community_cards.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/components/right_sidebar.scss
  client/styles/components/sidebar/community_info_module.scss
  client/styles/pages/discussions/sidebar.scss
  server/routes/deleteComment.ts
  server/routes/status.ts
Labels: 8, A3-needs resolving, enhancement

#817 Discussions sidebar: Active threads module
  client/scripts/controllers/app/recent_activity.ts
  client/scripts/stores/ActivityStore.ts
  client/scripts/views/pages/discussions/sidebar.ts
  client/styles/components/right_sidebar.scss
  client/styles/pages/discussions/sidebar.scss
Labels: 5, enhancement

#838 Filter out preimages from default /bulkEntities
  server/routes/bulkEntities.ts
Labels: 2, A0-please review, enhancement

#841 High priority notification settings fixes
  client/scripts/views/pages/notifications.ts
  client/styles/pages/notifications.scss
Labels: 2, A0-please QA, bug

#781 getRewards route to return rewards earned by validators over a period of time
  server/routes/getRewards.ts
Labels: A0-please review, enhancement

#782 Event handlers for #552, #553
  server/eventHandlers/bondEvents.ts
  server/eventHandlers/computeStats.ts
  server/eventHandlers/heartbeatEvents.ts
  server/eventHandlers/imOnlineEvents.ts
  server/eventHandlers/newSessionEvents.ts
  server/eventHandlers/offenceEvents.ts
  server/eventHandlers/rewardEvents.ts
  server/eventHandlers/slashEvents.ts
  server/scripts/setupChainEventListeners.ts
Labels: A0-please review, enhancement

#783 Implemented /getOffences route
  server/routes/getOffences.ts
Labels: A0-please review, enhancement

#839 Get bonded and unbonded stashes for manage staking
  client/scripts/controllers/chain/substrate/staking.ts
  client/scripts/controllers/server/chain_events.ts
  client/scripts/views/pages/manage_staking/substrate/new_nominator.ts
  server/migrations/20200924173758-drop-chain-stake.js
  server/models/chain_stake.ts
  server/router.ts
  server/routes/createChainStake.ts
  server/routes/getChainStake.ts
  test/unit/api/events.spec.ts
Labels: enhancement

#844 Create NewComment/Reaction subscriptions for all NewThread subscribers
  server/routes/createThread.ts
Labels: 2, A0-please QA, enhancement

#848 Removed thread privacy from the repo
  client/scripts/controllers/server/threads.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/views/components/inline_thread_composer.ts
  client/scripts/views/pages/discussions/discussion_row_menu.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/threads/index.ts
  client/scripts/views/pages/view_proposal/header.ts
  server/migrations/20200414143124-add-privacy-features-to-threads.js
  server/migrations/20200929202011-remove-privacy-from-threads.js
  server/models/offchain_thread.ts
  server/models/role.ts
  server/routes/bulkOffchain.ts
  server/routes/bulkThreads.ts
  server/routes/createThread.ts
  server/routes/setPrivacy.ts
  test/unit/api/threads.spec.ts
  test/unit/api/user.spec.ts
  test/util/modelUtils.ts
Labels: 3, A0-please review, enhancement

#849 Remove wallet selection step
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/pages/web3login.ts
Labels: 3, enhancement

#850 Move chain events listener into separate process.
  Procfile
  package.json
  server.ts
  server/scripts/emails.ts
  server/scripts/resetServer.ts
  server/util/eventPoller.ts
  test/unit/events/entityArchivalHandler.spec.ts
Labels: 1, A0-please QA, A0-please review, enhancement
