Repository hicommonwealth/commonwealth, pull requests merged in 2020-12, with the labels that each got.

#971 Ensure proper spinner behavior
  client/scripts/views/pages/discussions/index.ts
Labels: 1, bug

#972 Switch out thread count for const
  client/scripts/views/pages/discussions/index.ts
Labels: A0-please review

#973 Ensure activeAccount is updated on profile editing
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/sublayout.ts
Labels: 2, A0-please QA, A0-please review, bug

#974 Add user flags for councillor and validator.
  client/scripts/controllers/server/profiles.ts
  client/scripts/models/Profile.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/pages/discussions/sidebar.ts
  client/scripts/views/pages/profile/index.ts
  client/styles/components/widgets/user.scss
  package.json
  server-test.ts
  server.ts
  server/eventHandlers/userFlags.ts
  server/migrations/20201202211421-add-councillor-validator-flags.js
  server/models/address.ts
  server/scripts/migrateCouncillorValidatorFlags.ts
  server/scripts/setupChainEventListeners.ts
  test/unit/events/userFlagsHandler.spec.ts
  yarn.lock
Labels: 8, A0-please QA, A0-please review, enhancement

#978 Add new events via migration and handle democracy voted.
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  package.json
  server/eventHandlers/entityArchival.ts
  server/eventHandlers/notifications.ts
  server/eventHandlers/storage.ts
  server/migrations/20201204162137-add-new-chain-events.js
  yarn.lock
Labels: 1, A0-please QA, A0-please review, enhancement

#980 Bug: Sidebars disappear when on new & empty topic discussion page
  client/scripts/views/pages/discussions/index.ts
Labels: 2, bug

#983 Create empty profiles on important events.
  client/scripts/views/pages/profile/index.ts
  server/eventHandlers/profileCreation.ts
  server/models/address.ts
  server/scripts/setupChainEventListeners.ts
Labels: 3, 5, A0-please QA, A0-please review, enhancement

#970 Community switcher race conditions
  client/scripts/app.ts
  client/scripts/controllers/chain/community/main.ts
  client/scripts/controllers/server/comments.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/ICommunityAdapter.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/layout.ts
  client/scripts/views/pages/discussions/index.ts
Labels: 5, A0-please QA, A0-please review, bug

#984 Switch New Proposal select elements to Construct UI CustomSelect components
  client/scripts/views/components/edgeware_function_picker.ts
  client/scripts/views/components/forms.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/styles/components/forms.scss
Labels: 2, 5, A0-please QA, A0-please review, bug

#987 Ensure threads update upon editing
  client/scripts/controllers/server/threads.ts
  client/scripts/stores/IdStore.ts
  client/scripts/stores/ProposalStore.ts
  client/scripts/stores/TopicScopedThreadStore.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
Labels: 2, A0-please QA, A0-please review, bug

#988 Bump chain events and debug entity handler.
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/ethereum/moloch/governance.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/controllers/server/profiles.ts
  package.json
  yarn.lock
Labels: 2, A0-please QA, A0-please review, bug

#989 Prevent Quill from saving to LocalStorage if disabled
  client/scripts/views/components/quill_editor.ts
Labels: 1, bug

#996 Bump API and remove tx signing verification from substrate.
  client/scripts/controllers/chain/community/account.ts
  client/scripts/models/Account.ts
  package.json
  server/models/address.ts
  server/routes/verifyAddress.ts
  yarn.lock
Labels: 1, A0-please QA, A0-please review, enhancement

#998 Ensure transaction modal timer is properly set
  client/scripts/views/modals/tx_signing_modal.ts
Labels: bug

#1002 Update email copy to show address of unnamed profiles
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/controllers/chain/substrate/treasury_proposal.ts
  client/scripts/helpers/index.ts
  client/scripts/models/Profile.ts
  client/scripts/views/components/widgets/substrate_identity.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/modals/select_address_modal.ts
  client/scripts/views/modals/view_voters_modal.ts
  client/scripts/views/pages/profile/profile_banner.ts
  client/scripts/views/pages/profile/profile_header.ts
  client/scripts/views/pages/validators/cosmos.ts
  client/scripts/views/pages/validators/index.ts
  client/scripts/views/pages/validators/substrate/claim_payout.ts
  client/scripts/views/pages/validators/substrate/manage_staking.ts
  server/webhookNotifier.ts
  shared/notificationFormatter.ts
  shared/utils.ts
Labels: 2, A0-please QA, A0-please review, enhancement

#995 Refactor ProposalStore and TopicScopedThreadStore "update" methods
  client/scripts/controllers/server/threads.ts
  client/scripts/stores/IdStore.ts
  client/scripts/stores/ProposalStore.ts
  client/scripts/stores/TopicScopedThreadStore.ts
  client/scripts/views/pages/view_proposal/body.ts
Labels: 1, A0-please review, cleanup

#1007 Ensure threads are appropriately updated when a topic is deleted
  client/scripts/controllers/server/topics.ts
  client/scripts/stores/TopicScopedThreadStore.ts
  client/scripts/views/modals/edit_topic_modal.ts
  server/routes/deleteTopic.ts
Labels: 3, 5, A0-please QA, A0-please review, bug

#1011 Ensure chain initialization does not occur more than once
  client/scripts/views/modals/link_new_address_modal.ts
Labels: A0-please QA, A0-please review, bug

#1013 Add a check for existing addresses to LinkNewAddress webwallet modal
  client/scripts/views/modals/link_new_address_modal.ts
  server/router.ts
  server/routes/getAddressStatus.ts
Labels: 5, A0-please QA, A0-please review, enhancement

#1042 Complete passed referenda if chain height beyond dispatch block. (#1006)
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
Labels: 1, A0-please QA, A0-please review, bug

#1041 Add exclude parameter to NotificationHandler. (#1040)
  server/eventHandlers/notifications.ts
  server/scripts/setupChainEventListeners.ts
  test/unit/events/notificationHandler.spec.ts
Labels: 1, A0-please QA, A0-please review, enhancement

#1033 Switch Profile Content pagination system to an infinite scroll
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/modals/preview_modal.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/profile/profile_comment_group.ts
  client/scripts/views/pages/profile/profile_content.ts
  client/scripts/views/pages/search.ts
  client/styles/pages/profile.scss
  server/webhookNotifier.ts
  shared/notificationFormatter.ts
Labels: 2, A0-please QA, A0-please review, enhancement
