Repository hicommonwealth/commonwealth, pull requests merged in 2020-08, with the labels that each got.

#524 Introduce a UserGallery component that displays a truncated gallery of avatars
  client/scripts/controllers/server/comments.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/components/widgets/user_gallery.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/notifications.ts
  client/styles/components/sidebar/notification_row.scss
  client/styles/components/widgets/user_gallery.scss
  client/styles/pages/discussions/discussion_row.scss
Labels: enhancement

#533 Refactor api and node url init code.
  client/scripts/controllers/chain/substrate/shared.ts
  package.json
  server.ts
  server/scripts/migrateChainEntities.ts
  server/scripts/migrateIdentities.ts
  server/scripts/setupChainEventListeners.ts
  shared/substrate.ts
  yarn.lock
Labels: 2, A0-please QA, A0-please review, cleanup

#538 Restrict argument length in proposal title.
  client/scripts/controllers/chain/substrate/collective_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/views/components/proposal_row.ts
  shared/adapters/chain/substrate/types.ts
Labels: 1, A0-please QA, A0-please review, cleanup

#529 Clean up log output in files with tests.
  server/eventHandlers/entityArchival.ts
  server/eventHandlers/migration.ts
  server/eventHandlers/notifications.ts
  server/eventHandlers/storage.ts
  server/util/eventPoller.ts
  server/webhookNotifier.ts
Labels: 1, A0-please QA, A0-please review, cleanup

#462 Notification UI refresh
  client/scripts/app.ts
  client/scripts/helpers/chain_notification_types.ts
  client/scripts/helpers/notifications.ts
  client/scripts/models/NotificationSubscription.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/error.ts
  client/scripts/views/pages/notification-settings.ts
  client/scripts/views/pages/notification-settings/chain-event-settings.ts
  client/scripts/views/pages/notification-settings/notification-settings.ts
  client/styles/pages/error.scss
  client/styles/pages/subscriptions.scss
  server/migrations/20200708183925-subscription-model-upgrade.js
  server/migrations/20200729212319-prune-orphaned-subscriptions.js
  server/models/subscription.ts
  server/router.ts
  server/routes/acceptInvite.ts
  server/routes/createComment.ts
  server/routes/createRole.ts
  server/routes/createThread.ts
  server/routes/deleteComment.ts
  server/routes/deleteThread.ts
  server/routes/setDefaultRole.ts
  server/routes/subscription/createSubscription.ts
  server/routes/subscription/deleteSubscription.ts
  server/routes/subscription/errors.ts
  server/routes/subscription/viewSubscriptions.ts
  server/routes/viewNotifications.ts
  server/routes/viewSubscriptions.ts
  test/unit/api/subscriptions.spec.ts
  test/util/modelUtils.ts
Labels: 13, A0-please QA, A0-please review, A2-in progress, enhancement

#565 Fix refresh bug on comment deletion
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
Labels: 1, A0-please QA, bug

#572 Add redraw after account switch in login selector.
  client/scripts/views/components/header/login_selector.ts
Labels: 1, A0-please QA, A0-please review, bug, cleanup

#571 Move initial Substrate API connect to modal.
  client/scripts/app.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/views/modals/link_new_address_modal.ts
Labels: 1, A0-please QA, A0-please review, cleanup

#567 Single Notification Row for Chain Events, filter
  client/scripts/helpers/notifications.ts
  client/scripts/views/components/header/notifications_menu.ts
  client/scripts/views/pages/notifications.ts
Labels: 1, bug

#530 SetPrivacy Route now handles all things privacy
  client/scripts/controllers/server/threads.ts
  client/scripts/views/pages/discussions/discussion_row_menu.ts
  client/scripts/views/pages/view_proposal/header.ts
  server/router.ts
  server/routes/editThread.ts
  server/routes/setPrivacy.ts
  test/unit/api/threads.spec.ts
Labels: 5, enhancement

#577 Bump internal project versions.
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/edgeware/signaling_proposal.ts
  client/scripts/views/components/proposals/voting_results.ts
  package.json
  server/scripts/migrateChainEntities.ts
  server/scripts/migrateIdentities.ts
  server/scripts/setupChainEventListeners.ts
  shared/adapters/chain/edgeware/types.ts
  tsconfig.json
  yarn.lock
Labels: 2, A0-please QA, A0-please review, cleanup

#578 Removes client-side checks for TX errors.
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/edgeware/signaling_proposal.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/controllers/chain/substrate/identities.ts
  client/scripts/controllers/chain/substrate/identity.ts
  client/scripts/controllers/chain/substrate/phragmen_election.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/views/modals/tx_signing_modal.ts
  client/scripts/views/pages/new_signaling.ts
Labels: 1, A0-please QA, A0-please review, cleanup

#581 Fix tests
  client/scripts/views/pages/notification-settings/notification-settings.ts
  server/router.ts
  test/unit/api/roles.spec.ts
  test/unit/api/subscriptions.spec.ts
Labels: 1, bug

#591 New Thread Form: Updates to Save Draft button
  client/scripts/controllers/server/drafts.ts
  client/scripts/models/DiscussionDraft.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/quill_editor.ts
  server/models/discussion_draft.ts
Labels: 3, A0-please review, enhancement

#545 Governance, Council, & Discussion Pages: Redesign & Refactor
  client/scripts/app.ts
  client/scripts/controllers/chain/edgeware/signaling_proposal.ts
  client/scripts/controllers/chain/substrate/collective_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/controllers/chain/substrate/treasury_proposal.ts
  client/scripts/controllers/server/reactions.ts
  client/scripts/helpers/index.ts
  client/scripts/views/components/countdown.ts
  client/scripts/views/components/listing_header.ts
  client/scripts/views/components/listing_row.ts
  client/scripts/views/components/proposal_row.ts
  client/scripts/views/components/row_header.ts
  client/scripts/views/modals/view_voters_modal.ts
  client/scripts/views/pages/council.ts
  client/scripts/views/pages/council/council_row.ts
  client/scripts/views/pages/council/index.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/listing.ts
  client/scripts/views/pages/loading.ts
  client/scripts/views/pages/proposals.ts
  client/scripts/views/sublayout.ts
  client/styles/components/listing.scss
  client/styles/components/listing_header.scss
  client/styles/components/listing_row.scss
  client/styles/components/proposal_row.scss
  client/styles/pages/council.scss
  client/styles/pages/council_row.scss
  client/styles/pages/discussions/discussion_row.scss
  client/styles/pages/discussions/index.scss
  client/styles/pages/proposals.scss
  client/styles/shared.scss
Labels: A3-needs resolving, enhancement

#597 Pinned Threads
  client/scripts/controllers/server/threads.ts
  client/scripts/views/components/listing_row.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/discussion_row_menu.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/discussions/pinned_listing.ts
  client/scripts/views/pages/discussions/weekly_listing.ts
  client/styles/components/listing_row.scss
  server/router.ts
  server/routes/pinThread.ts
  test/unit/api/threads.spec.ts
Labels: 5

#595 Notification Code Review
  client/scripts/app.ts
  client/scripts/helpers/chain_notification_types.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/subscriptions.ts
  client/scripts/views/pages/subscriptions/chainEventSettings.ts
  client/scripts/views/pages/subscriptions/notificationSettings.ts
  client/styles/pages/notification_subscriptions.scss
Labels: 5, A0-please review, enhancement

#601 Pinned Thread UI Bugs
  client/scripts/views/pages/discussions/index.ts
Labels: 3, A0-please review, bug

#633 Bug fix: Pinned threads are not showing in topic pages.
  client/scripts/views/pages/discussions/index.ts
Labels: 1, A0-please review

#636 Edit Profile Modal populates with existing information
  client/scripts/views/modals/edit_profile_modal.ts
  client/scripts/views/pages/discussions/discussion_row.ts
Labels: 2, A0-please QA, enhancement

#642 Notify user of email update success with toast on link redirect
  client/scripts/app.ts
  client/scripts/views/modals/confirm_invite_modal.ts
  server/routes/finishEmailLogin.ts
  server/routes/updateEmail.ts
Labels: 2, A0-please QA, enhancement

#638 Bug Fix: Switch Profiles while on Profile Page, edit profile
  client/scripts/views/pages/profile/index.ts
Labels: 2, A0-please QA, enhancement

#654 Remove category_id from OffchainThreads
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  server/migrations/20200825164046-remove-thread-category-ids.js
Labels: 1, A0-please review, bug

#663 Bug fix: Invite modal opens with url even if no invites
  client/scripts/app.ts
Labels: 1, A0-please QA

#637 Prompt the user to save or discard changes when leaving the new thread form
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/modals/confirm_modal.ts
  client/scripts/views/pages/threads/index.ts
Labels: 5, A0-please QA, A0-please review, enhancement

#665 Bug Fix: Discussion Row Pin misaligns rest of row slightly
  client/scripts/views/components/listing_row.ts
  client/styles/components/listing_row.scss
Labels: 1, A0-please QA, enhancement

#666 Bug Fix: Multiple Invites generated by infinite invite link
  server/routes/acceptInviteLink.ts
Labels: 1, A0-please QA

#658 Bug fix: Edit Profile prepopulated data not rehydrating
  client/scripts/views/modals/edit_profile_modal.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/profile/profile_header.ts
Labels: 1, A0-please QA

#667 Topic-scope the New Thread Form when navigating from a topic-scoped page
  client/scripts/views/components/new_thread_form.ts
Labels: 2, A0-please review, enhancement

#623 Added Migration for new session event enriched in chain-events-#11
  server/migrations/20200821080425-add-new-session-event.js
Labels: A0-please review, enhancement

#625 Add CHAIN_EVENTS configuration variable.
  README.md
  client/scripts/views/pages/subscriptions/chainEventSettings.ts
  package.json
  server.ts
  server/scripts/setupChainEventListeners.ts
  yarn.lock
Labels: 1, A0-please QA, A0-please review, cleanup, enhancement

#621 Adds KLP as a chain
  client/scripts/app.ts
  client/scripts/controllers/chain/kulupu/main.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/phragmen_election.ts
  client/scripts/helpers/chain_notification_types.ts
  client/scripts/models/types.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/subscriptions/chainEventSettings.ts
  report.20200821.225728.18738.0.001.json
  server/migrations/20200826024003-add-kulupu-chain.js
  server/models/address.ts
  server/scripts/resetServer.ts
  static/img/protocols/klp.png
Labels: A0-please QA, A0-please review

#673 Update API and fix preimage loading issue.
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/stores/ChainEntityStore.ts
  client/scripts/stores/Store.ts
  package.json
  yarn.lock
Labels: 2, A0-please QA, A0-please review, bug, enhancement

#687 Fix args for submit candidacy.
  client/scripts/controllers/chain/substrate/phragmen_election.ts
Labels: 1, A0-please QA, A0-please review, bug

#686 Fix Invite Form button bug
  client/scripts/views/modals/create_invite_modal.ts
Labels: 2, bug

#690 Populate existing onchain profile info properly
  client/scripts/views/modals/edit_identity_modal.ts
Labels: 3, A0-please review

#680 Consistency between "New Comments" and "New Comments and Reactions"
  client/scripts/views/pages/discussions/discussion_row_menu.ts
  server/migrations/20200827191721-create-missing-reaction-subscriptions.js
  server/routes/subscription/createSubscription.ts
Labels: 3, A0-please QA, enhancement

#692 Voting modal for Edgeware should auto-populate with existing council voting lock
  client/scripts/views/modals/council_voting_modal.ts
Labels: 1, A0-please review, enhancement
