Repository hicommonwealth/commonwealth, pull requests merged in 2020-06, with the labels that each got.

#297 Update Email Route and Email Interval Model/Migration Route
  server/migrations/20200527155244-add-notif-email-to-user-model.js
  server/models/user.ts
  server/router.ts
  server/routes/updateEmail.ts
  server/routes/updateUserEmailInterval.ts
  test/unit/api/user.spec.ts
Labels: A0-please review, enhancement

#298 Add @types/sequelize and split models into Attributes/Instance/Model interfaces.
  package.json
  server/database.ts
  server/models/address.ts
  server/models/chain.ts
  server/models/chain_entity.ts
  server/models/chain_event.ts
  server/models/chain_event_type.ts
  server/models/chain_node.ts
  server/models/chat_message.ts
  server/models/contract_category.ts
  server/models/contract_item.ts
  server/models/edgeware_lockdrop_balance.ts
  server/models/edgeware_lockdrop_event.ts
  server/models/edgeware_lockdrop_everything.ts
  server/models/hedgehog_authentication.ts
  server/models/hedgehog_user.ts
  server/models/invite_code.ts
  server/models/invite_link.ts
  server/models/login_token.ts
  server/models/membership.ts
  server/models/notification.ts
  server/models/notification_category.ts
  server/models/offchain_attachment.ts
  server/models/offchain_comment.ts
  server/models/offchain_community.ts
  server/models/offchain_profile.ts
  server/models/offchain_reaction.ts
  server/models/offchain_tag.ts
  server/models/offchain_thread.ts
  server/models/offchain_viewcount.ts
  server/models/role.ts
  server/models/social_account.ts
  server/models/subscription.ts
  server/models/tagged_threads.ts
  server/models/user.ts
  server/models/waitlist_registration.ts
  server/models/webhook.ts
  yarn.lock
Labels: 3, A7-looks good, cleanup

#264 Community Admin Panel Bugs and Design Revisions
  client/scripts/views/components/admin_panel/admin_panel_contents.ts
  client/scripts/views/components/admin_panel/admin_panel_tabs.ts
  client/scripts/views/components/admin_panel/admin_tab_panel.ts
  client/scripts/views/components/admin_panel/chain_metadata_management_table.ts
  client/scripts/views/components/admin_panel/community_metadata_management_table.ts
  client/scripts/views/components/admin_panel/index.ts
  client/scripts/views/components/admin_panel/input_property_row.ts
  client/scripts/views/components/admin_panel/manage_roles_row.ts
  client/scripts/views/components/admin_panel/metadata_rows.ts
  client/scripts/views/components/admin_panel/toggle_property_row.ts
  client/scripts/views/components/admin_panel/upgrade_roles_form.ts
  client/styles/components/admin_panel.scss
  server/routes/updateChain.ts
  server/routes/updateCommunity.ts
  test/unit/api/updatecommunity.spec.ts
Labels: A0-please review, enhancement

#271 Refactors small tag logic into TagController
  client/scripts/controllers/server/tags.ts
  client/scripts/views/pages/discussions/tag_selector.ts
Labels: 1, A0-please QA, A0-please review, cleanup

#275 Global statistics and separate controller for staking-ui
  client/scripts/app.ts
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/staking.ts
  client/scripts/stores/StakingStore.ts
  client/scripts/stores/index.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/validators/index.ts
  client/scripts/views/pages/validators/substrate/card_summary.ts
  client/scripts/views/pages/validators/substrate/preheader.ts
  client/scripts/views/pages/validators/substrate/presentation_component.ts
  client/scripts/views/pages/validators/substrate/validator_row.ts
Labels: A3-needs resolving, Phase 1, enhancement

#303 Featured Tags in Sidebar Update with Pin/Unpin
  client/scripts/models/ChainInfo.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/views/components/sidebar/tag_selector.ts
Labels: 2, A0-please QA, bug

#279 Add PersistentStore type to store SubstrateIdentities in localStorage.
  client/scripts/controllers/chain/cosmos/proposal.ts
  client/scripts/controllers/chain/substrate/identities.ts
  client/scripts/controllers/chain/substrate/identity.ts
  client/scripts/controllers/server/notifications.ts
  client/scripts/identifiers.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/Identity.ts
  client/scripts/models/Proposal.ts
  client/scripts/models/mithril.ts
  client/scripts/stores/IdStore.ts
  client/scripts/stores/PersistentStore.ts
  client/scripts/stores/Store.ts
  client/scripts/stores/index.ts
  client/scripts/stores/interfaces.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/modals/edit_identity_modal.ts
  client/scripts/views/pages/profile/profile_header.ts
Labels: 5, A5-seems ok, enhancement

#321 Permit signaling proposal vote fetch even if completed.
  client/scripts/controllers/chain/edgeware/signaling_proposal.ts
Labels: 1, A0-please review, bug

#225 Construct: Better 404 Pages
  client/scripts/views/pages/404.ts
  client/scripts/views/pages/profile/index.ts
  client/styles/components/inline_thread_composer.scss
  client/styles/pages/404.scss
Labels: A0-please review, A3-needs resolving, bug, enhancement

#310 TODOs for renaming routes and state properties
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/controllers/server/chain_objects.ts
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/notifications.ts
  client/scripts/controllers/server/profiles.ts
  client/scripts/controllers/server/reactions.ts
  client/scripts/controllers/server/tags.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/helpers/index.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/state.ts
  client/scripts/views/components/admin_panel/admin_panel_tabs.ts
  client/scripts/views/components/admin_panel/index.ts
  client/scripts/views/components/avatar_upload.ts
  client/scripts/views/components/dropzone_textarea.ts
  client/scripts/views/components/membership_button.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/components/tag_editor.ts
  client/scripts/views/modals/create_community_modal.ts
  client/scripts/views/modals/create_invite_modal.ts
  client/scripts/views/modals/manage_community_modal.ts
  client/scripts/views/modals/upgrade_member_modal.ts
  client/scripts/views/pages/admin.ts
  client/scripts/views/pages/discussions/roles.ts
  client/scripts/views/pages/notifications.ts
  client/scripts/views/pages/subscriptions.ts
  server/router.ts
Labels: A0-please review, qa or code review

#312 Thread Tags Update: Frontend, Backend, the Whole Schebang
  client/scripts/controllers/server/tags.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/views/components/autocomplete_input.ts
  client/scripts/views/components/autocomplete_tag_form.ts
  client/scripts/views/components/forms.ts
  client/scripts/views/components/inline_thread_composer.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/components/sidebar/tag_selector.ts
  client/scripts/views/components/tag_editor.ts
  client/scripts/views/modal.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/discussions/thread_carat_menu.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/new_thread.ts
  client/scripts/views/pages/tags.ts
  client/scripts/views/pages/threads/index.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/components/autocomplete_tag_form.scss
  client/styles/components/header/community_selector.scss
  client/styles/components/sidebar/index.scss
  client/styles/layout.scss
  client/styles/modal.scss
  client/styles/modals/new_thread_modal.scss
  client/styles/pages/tags.scss
  client/styles/shared.scss
  server/migrations/20200529141657-add-tag-id-to-threads.js
  server/migrations/20200529143006-switch-off-tagged-threads-joins-table.js
  server/migrations/20200603210325-remove-tagged-threads-joins-table.js
  server/models/offchain_tag.ts
  server/models/offchain_thread.ts
  server/routes/bulkReactions.ts
  server/routes/bulkThreads.ts
  server/routes/createComment.ts
  server/routes/createReaction.ts
  server/routes/createThread.ts
  server/routes/deleteThread.ts
  server/routes/editThread.ts
  server/routes/updateTags.ts
  server/routes/viewReactions.ts
  test/unit/api/subscriptions.spec.ts
  test/unit/api/tags.spec.ts
  test/unit/api/threads.spec.ts
  test/unit/api/webhooks.spec.ts
  test/util/modelUtils.ts
Labels: A0-please QA, A0-please review, bug, cleanup, enhancement

#351 Add showRole conditional to User Widget
  client/scripts/controllers/chain/community/main.ts
  client/scripts/helpers/roles.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/RoleInfo.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/styles/components/widgets/user.scss
Labels: A0-please QA, A0-please review, enhancement

#361 Convert polkadot extension validation to signRaw.
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/views/modals/link_new_address_modal.ts
  package.json
  server/models/address.ts
  yarn.lock
Labels: 2, A0-please QA, A0-please review, bug

#360 Add data to each validator table item
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/staking.ts
  client/scripts/views/pages/validators/index.ts
  client/scripts/views/pages/validators/substrate/card_summary.ts
  client/scripts/views/pages/validators/substrate/presentation_component.ts
  client/scripts/views/pages/validators/substrate/recent_block.ts
  client/scripts/views/pages/validators/substrate/validator_row.ts
Labels: Phase 1, enhancement

#372 Discussion Row Carat overflow bugfix
  client/scripts/views/pages/discussions/thread_carat_menu.ts
Labels: 1, A0-please QA, A0-please review, bug

#370 Add pagination for validator list
  client/scripts/views/components/widgets/tabs.ts
  client/scripts/views/pages/validators/substrate/presentation_component.ts
Labels: Phase 1, enhancement

#362 Add address verification checks to routes (and Error refactor)
  server/routes/acceptInvite.ts
  server/routes/addChainNode.ts
  server/routes/addChainObjectQuery.ts
  server/routes/addMember.ts
  server/routes/bulkComments.ts
  server/routes/bulkEntities.ts
  server/routes/bulkTags.ts
  server/routes/bulkThreads.ts
  server/routes/createAddress.ts
  server/routes/createHedgehogAuthentication.ts
  server/routes/createHedgehogUser.ts
  server/routes/createMembership.ts
  server/routes/createReaction.ts
  server/routes/createTag.ts
  server/routes/deleteAddress.ts
  server/routes/deleteChain.ts
  server/routes/deleteChainNode.ts
  server/routes/deleteChainObjectQuery.ts
  server/routes/deleteComment.ts
  server/routes/deleteCommunity.ts
  server/routes/deleteGithubAccount.ts
  server/routes/deleteMembership.ts
  server/routes/deleteReaction.ts
  server/routes/deleteTag.ts
  server/routes/deleteThread.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
  server/routes/getEdgewareLockdropStats.ts
  server/routes/getHedgehogAuthentication.ts
  server/routes/getInviteLinks.ts
  server/routes/getInvites.ts
  server/routes/getUploadSignature.ts
  server/routes/markNotificationsRead.ts
  server/routes/refreshChainObjects.ts
  server/routes/registerWaitingList.ts
  server/routes/selectAddress.ts
  server/routes/selectNode.ts
  server/routes/sendFeedback.ts
  server/routes/starCommunity.ts
  server/routes/startEmailLogin.ts
  server/routes/updateChain.ts
  server/routes/updateCommunity.ts
  server/routes/updateProfile.ts
  server/routes/updateTags.ts
  server/routes/upgradeMember.ts
  server/routes/verifyAddress.ts
  server/routes/viewChainObjectQueries.ts
  server/routes/viewChainObjects.ts
  server/routes/viewComments.ts
  server/routes/viewCount.ts
  server/routes/viewNotifications.ts
  server/routes/viewReactions.ts
  server/routes/viewSubscriptions.ts
  server/routes/webhooks/createWebhook.ts
  server/routes/webhooks/deleteWebhook.ts
  server/routes/webhooks/getWebhooks.ts
  server/routes/writeUserSetting.ts
  server/util/lookupCommunityIsVisibleToUser.ts
  test/unit/api/subscriptions.spec.ts
  test/unit/api/threads.spec.ts
Labels: 5, A7-looks good, cleanup, enhancement

#381 Fix readonly toggle button silent failure
  client/scripts/controllers/server/threads.ts
  client/scripts/views/pages/view_proposal/header.ts
  server/router.ts
  test/unit/api/threads.spec.ts
Labels: 1, A0-please QA, A0-please review, bug

#380 Add tooltip to User component in discussion row
  client/scripts/views/pages/discussions/discussion_row.ts
Labels: 1, A0-please review, bug

#378 Add descriptions on-hover and load spinner while first paginated validator data loads
  client/scripts/views/pages/validators/substrate/im_online.ts
  client/scripts/views/pages/validators/substrate/presentation_component.ts
Labels: Phase 1, enhancement

#375 Nominations API fixes for waiting validators and refactoring
  client/scripts/controllers/chain/substrate/staking.ts
  client/scripts/views/pages/validators/index.ts
  client/scripts/views/pages/validators/substrate/identity.ts
  client/scripts/views/pages/validators/substrate/im_online.ts
  client/scripts/views/pages/validators/substrate/presentation_component.ts
  client/scripts/views/pages/validators/substrate/validator_row.ts
  client/scripts/views/pages/validators/substrate/validator_row_waiting.ts
Labels: A7-looks good, Phase 1, enhancement, qa or code review

#411 Direct Batch-Notification Path of Threads to Discussions not Thread
  client/scripts/views/components/notification_row.ts
  shared/utils.ts
Labels: 1, A0-please QA, bug

#428 Wait for identity to enable buttons on profile.
  client/scripts/views/pages/profile/profile_header.ts
Labels: 1, A0-please QA, A0-please review, bug

#422 Get total offences for a validator
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/controllers/server/chain_events.ts
  client/scripts/lib/util.js
  client/scripts/state.ts
  client/scripts/views/pages/validators/substrate/preheader.ts
  server/migrations/20200620111058-add-offences-chain-event-types.js
  server/migrations/20200621093623-add-imonline-chain-event-types.js
  server/router.ts
  server/routes/getOffences.ts
  server/scripts/setupChainEventListeners.ts
  shared/events/edgeware/filters/enricher.ts
  shared/events/edgeware/filters/labeler.ts
  shared/events/edgeware/filters/titler.ts
  shared/events/edgeware/filters/type_parser.ts
  shared/events/edgeware/types.ts
  test/unit/events/edgeware/enricher.spec.ts
  test/unit/events/edgeware/testUtil.ts
Labels: Phase 1

#438 Rename Edgeware events to Substrate.
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/edgeware/signaling_proposal.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/collective_proposal.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/controllers/chain/substrate/treasury_proposal.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/models/ChainEventType.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/pages/notification-settings.ts
  client/scripts/views/pages/subscriptions.ts
  server-test.ts
  server/eventHandlers/entityArchival.ts
  server/migrations/20200415152936-add-chain-events.js
  server/migrations/20200610192842-add-kusama-chain-event-types.js
  server/scripts/resetServer.ts
  server/scripts/setupChainEventListeners.ts
  server/util/proposalIdToEntity.ts
  shared/events/README.md
  shared/events/interfaces.ts
  shared/events/substrate/filters/enricher.ts
  shared/events/substrate/filters/labeler.ts
  shared/events/substrate/filters/titler.ts
  shared/events/substrate/filters/type_parser.ts
  shared/events/substrate/index.ts
  shared/events/substrate/poller.ts
  shared/events/substrate/processor.ts
  shared/events/substrate/storageFetcher.ts
  shared/events/substrate/subscriber.ts
  shared/events/substrate/types.ts
  test/integration/events/moloch.spec.ts
  test/unit/events/edgeware/enricher.spec.ts
  test/unit/events/edgeware/poller.spec.ts
  test/unit/events/edgeware/processor.spec.ts
  test/unit/events/edgeware/storageFetcher.spec.ts
  test/unit/events/edgeware/subscriber.spec.ts
  test/unit/events/entityArchivalHandler.spec.ts
  test/unit/events/migrationHandler.spec.ts
  test/unit/events/notificationHandler.spec.ts
  test/unit/events/storageHandler.spec.ts
Labels: 1, A0-please review

#446 Sign-in/Sign-up distinct emails and factor out template ids to shared/types
  server/routes/createInvite.ts
  server/routes/startEmailLogin.ts
  server/routes/updateEmail.ts
  server/routes/verifyAddress.ts
  server/scripts/emails.ts
  shared/types.ts
Labels: 1, 2, enhancement

#433 Auto-Subscribe user to New Threads when joining community
  client/scripts/views/pages/discussions/thread_carat_menu.ts
  server/routes/acceptInvite.ts
  server/routes/createRole.ts
  test/unit/api/invites.spec.ts
  test/unit/api/roles.spec.ts
Labels: 1

#439 Add Polkadot chain.
  client/scripts/app.ts
  client/scripts/controllers/chain/kusama/main.ts
  client/scripts/controllers/chain/polkadot/main.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/identifiers.ts
  client/scripts/models/types.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/pages/proposals.ts
  client/scripts/views/pages/validators/index.ts
  server/migrations/20200623205113-add-polkadot.js
  server/models/address.ts
  server/scripts/resetServer.ts
  shared/events/substrate/filters/labeler.ts
  shared/events/substrate/types.ts
Labels: 3, A0-please QA, A0-please review

#435 Infinite Scroll: Spinner Edition
  client/scripts/views/pages/discussions/index.ts
  client/styles/pages/discussions/index.scss
Labels: A0-please review, A3-needs resolving, enhancement

#451 Restore meaningful webpack chunking behavior.
  .madgerc
  client/scripts/app.ts
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/app/modals.ts
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/ethereum/main.ts
  client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  client/scripts/controllers/chain/ethereum/moloch/governance.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/identifiers.ts
  client/scripts/lib/moment.min.js
  client/scripts/models/IChainAdapter.ts
  client/scripts/state.ts
  client/scripts/views/components/create_invite_link.ts
  client/scripts/views/components/header/index.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/login.ts
  client/scripts/views/components/membership_button.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/components/quill_formatted_text.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/components/widgets/substrate_identity.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/modals/confirm_invite_modal.ts
  client/scripts/views/modals/create_invite_modal.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/modals/select_address_modal.ts
  client/scripts/views/pages/admin.ts
  client/scripts/views/pages/finish_near_login.ts
  client/scripts/views/pages/notification-settings.ts
  client/scripts/views/pages/settings/accounts_well.ts
  client/scripts/views/pages/subscriptions.ts
  client/scripts/views/pages/view_proposal/index.ts
  madge.sh
  shared/events/moloch/index.ts
  webpack/webpack.common.js
Labels: 8, A0-please QA, A0-please review, bug, cleanup

#445 Edit Tag Button bug fixes
  client/scripts/controllers/server/user/roles.ts
  client/scripts/views/components/autocomplete_tag_form.ts
  client/scripts/views/components/tag_editor.ts
  client/scripts/views/pages/discussions/thread_carat_menu.ts
  client/styles/layout.scss
Labels: 5

#460 Ensure comments refresh
  client/scripts/views/pages/view_proposal/index.ts
Labels: bug

#457 Lock Quill editor + form buttons while saving post
  client/scripts/views/pages/new_thread.ts
  client/scripts/views/pages/threads/index.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/pages/view_proposal/header.scss
  client/styles/pages/view_proposal/index.scss
Labels: enhancement

#461 Quill Mentions: Keybinding Fix
  client/scripts/views/components/quill_editor.ts
  package.json
  yarn.lock
Labels: A0-please review, bug
