Repository hicommonwealth/commonwealth, pull requests merged in 2021-02, with the labels that each got.

#1080 Magic.link login integration.
  client/scripts/controllers/app/login.ts
  client/scripts/models/AddressInfo.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/login.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/modals/manage_community_modal/metadata_rows.ts
  client/scripts/views/modals/select_address_modal.ts
  client/scripts/views/pages/settings/email_well.ts
  client/scripts/views/pages/settings/linked_addresses_well.ts
  client/styles/components/login.scss
  client/styles/modals/link_new_address_modal.scss
  client/styles/modals/select_address_modal.scss
  package.json
  server/config.ts
  server/migrations/20210127181912-add-magic-fields.js
  server/models/address.ts
  server/models/user.ts
  server/passport.ts
  server/router.ts
  server/routes/deleteAddress.ts
  server/routes/startEmailLogin.ts
  server/routes/updateEmail.ts
  yarn.lock
Labels: 13, 8, A0-please QA, A0-please review, enhancement

#1082 Add sequelize transactions to routes.
  server/routes/clearReadNotifications.ts
  server/routes/markNotificationsRead.ts
  server/routes/subscription/disableImmediateEmails.ts
  server/routes/subscription/disableSubscriptions.ts
  server/routes/subscription/enableImmediateEmails.ts
  server/routes/subscription/enableSubscriptions.ts
Labels: 1, A0-please QA, A0-please review, enhancement

#1081 Ensure thread readOnly state updates globally
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
Labels: 1, A0-please QA, A0-please review, bug

#1084 Notification Pip
  client/scripts/views/components/notification_row.ts
  client/styles/components/sidebar/notification_row.scss
Labels: 2, A0-please QA, A0-please review, enhancement

#1072 Ensure thread form topics update properly from drafts & localStorage
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/topic_selector.ts
Labels: 1, 2, A0-please QA, A0-please review, bug

#1071 Move mention-parsing to backend
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/helpers/threads.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  server/routes/createComment.ts
  server/routes/createThread.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
  server/scripts/resetServer.ts
  server/util/parseUserMentions.ts
  test/unit/api/threads.spec.ts
  test/util/modelUtils.ts
Labels: 5, A0-please QA, A0-please review, cleanup

#1088 Add ChainBase finder and support arbitrary ETH address.
  client/scripts/models/ChainInfo.ts
  client/scripts/models/types.ts
  client/scripts/views/pages/profile/index.ts
Labels: 1, 2, A0-please QA, A0-please review, enhancement

#1089 API test fixes.
  server/passport.ts
  server/routes/addEditors.ts
  server/routes/addMember.ts
  server/routes/bulkAddresses.ts
  server/routes/bulkComments.ts
  server/routes/bulkMembers.ts
  server/routes/bulkOffchain.ts
  server/routes/bulkReactions.ts
  server/routes/bulkThreads.ts
  server/routes/bulkTopics.ts
  server/routes/communityStats.ts
  server/routes/createComment.ts
  server/routes/createInvite.ts
  server/routes/createInviteLink.ts
  server/routes/createMembership.ts
  server/routes/createReaction.ts
  server/routes/createRole.ts
  server/routes/createThread.ts
  server/routes/createTopic.ts
  server/routes/deleteEditors.ts
  server/routes/deleteMembership.ts
  server/routes/deleteRole.ts
  server/routes/deleteTopic.ts
  server/routes/drafts/createDraft.ts
  server/routes/drafts/deleteDraft.ts
  server/routes/drafts/editDraft.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
  server/routes/editTopic.ts
  server/routes/getThread.ts
  server/routes/search.ts
  server/routes/setDefaultRole.ts
  server/routes/starCommunity.ts
  server/routes/startEmailLogin.ts
  server/routes/updateChain.ts
  server/routes/updateThreadPinned.ts
  server/routes/updateThreadStage.ts
  server/routes/upgradeMember.ts
  server/routes/viewComments.ts
  server/routes/viewReactions.ts
  server/routes/webhooks/createWebhook.ts
  server/routes/webhooks/deleteWebhook.ts
  server/routes/webhooks/getWebhooks.ts
  server/routes/webhooks/updateWebhook.ts
  server/util/lookupAddressIsOwnedByUser.ts
  server/util/lookupCommunityIsVisibleToUser.ts
  test/unit/api/invites.spec.ts
  test/unit/api/roles.spec.ts
  test/unit/api/threads.spec.ts
  test/unit/api/updatecommunity.spec.ts
  test/unit/api/webhooks.spec.ts
  test/util/modelUtils.ts
Labels: 2, A0-please QA, A0-please review, bug

#1092 Add polkadot magic support.
  client/scripts/controllers/app/login.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/views/pages/admin.ts
  package.json
  server/config.ts
  server/migrations/20210217161948-add-chain-base-and-ss58-prefix.js
  server/models/chain.ts
  server/models/offchain_community.ts
  server/passport.ts
  server/routes/addChainNode.ts
  server/routes/startEmailLogin.ts
  server/scripts/resetServer.ts
  yarn.lock
Labels: 3, 5, A0-please QA, A0-please review, enhancement

#1096 Ensure New Proposal Form dropdowns render
  client/styles/pages/new_proposal_page.scss
Labels: 1, bug

#1099 Always generate both an eth and substrate address on magic login.
  client/scripts/controllers/app/login.ts
  server/passport.ts
Labels: 1, 2, A0-please QA, A0-please review, enhancement

#1098 Convert all RxJS usage to Promise.
  .eslintrc.json
  client/scripts/app.ts
  client/scripts/controllers/chain/cosmos/account.ts
  client/scripts/controllers/chain/cosmos/chain.ts
  client/scripts/controllers/chain/cosmos/governance.ts
  client/scripts/controllers/chain/cosmos/proposal.ts
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/edgeware/signaling_proposal.ts
  client/scripts/controllers/chain/ethereum/account.ts
  client/scripts/controllers/chain/ethereum/chain.ts
  client/scripts/controllers/chain/ethereum/commonwealth/adapter.ts
  client/scripts/controllers/chain/ethereum/commonwealth/member.ts
  client/scripts/controllers/chain/ethereum/main.ts
  client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  client/scripts/controllers/chain/ethereum/moloch/member.ts
  client/scripts/controllers/chain/ethereum/moloch/proposal.ts
  client/scripts/controllers/chain/near/account.ts
  client/scripts/controllers/chain/near/chain.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/collective_proposal.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/controllers/chain/substrate/identities.ts
  client/scripts/controllers/chain/substrate/identity.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/phragmen_election.ts
  client/scripts/controllers/chain/substrate/phragmen_elections.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/controllers/chain/substrate/treasury_proposal.ts
  client/scripts/models/Account.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/Profile.ts
  client/scripts/models/Proposal.ts
  client/scripts/models/ProposalModule.ts
  client/scripts/models/interfaces.ts
  client/scripts/models/mithril.ts
  client/scripts/state.ts
  client/scripts/stores/IdStore.ts
  client/scripts/views/components/proposals/balance_info.ts
  client/scripts/views/components/proposals/voting_results.ts
  client/scripts/views/components/sending_from.ts
  client/scripts/views/components/widgets/account_balance.ts
  client/scripts/views/components/widgets/substrate_identity.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/modals/edit_identity_modal.ts
  client/scripts/views/modals/tx_signing_modal.ts
  client/scripts/views/pages/admin.ts
  client/scripts/views/pages/profile/profile_header.ts
  client/scripts/views/pages/settings/send_edg_well.ts
  client/scripts/views/pages/validators/index.ts
  client/scripts/views/pages/validators/substrate/claim_payout.ts
  client/scripts/views/pages/validators/substrate/manage_staking.ts
  client/scripts/views/pages/validators/substrate/preheader.ts
  server/socket/index.ts
  shared/adapters/chain/cosmos/api.ts
  shared/adapters/shared.ts
Labels: 13, 8, A0-please QA, A0-please review, cleanup
