Repository hicommonwealth/commonwealth, pull requests merged in 2021-05, with the labels that each got.

#1165 Bug address (substrate/ethereum) checksum fix
  client/scripts/controllers/chain/ethereum/account.ts
  client/scripts/controllers/chain/ethereum/accounts.ts
  client/scripts/controllers/chain/ethereum/commonwealth/members.ts
  client/scripts/controllers/chain/ethereum/contractApi.ts
  client/scripts/controllers/chain/ethereum/marlin/api.ts
  client/scripts/controllers/chain/ethereum/marlin/holder.ts
  client/scripts/controllers/chain/ethereum/moloch/governance.ts
  client/scripts/controllers/chain/ethereum/moloch/member.ts
  client/scripts/controllers/chain/ethereum/moloch/members.ts
  client/scripts/controllers/chain/ethereum/moloch/proposal.ts
  client/scripts/controllers/server/profiles.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/pages/profile/index.ts
  server/migrations/20210429022658-fix-substrate-address.js
  server/migrations/20210506034237-fix-ethereum-address.js
  server/routes/linkExistingAddressToChain.ts
  server/routes/updateProfile.ts
  server/util/addressSwapper.ts
Labels: A0-please QA, A0-please review, bug

#1157 Social sharing button
  client/scripts/views/components/social_sharing_carat.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/pages/view_proposal/index.scss
  server/scripts/resetServer.ts
Labels: A2-in progress

#1173 Fix types and factor substrate module loading.
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/phragmen_election.ts
  client/scripts/controllers/chain/substrate/phragmen_elections.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/ProposalModule.ts
  client/scripts/views/components/load_substrate_modules.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/bounties.ts
  client/scripts/views/pages/council.ts
  client/scripts/views/pages/proposals.ts
  client/scripts/views/pages/referenda.ts
  client/scripts/views/pages/treasury.ts
  client/scripts/views/pages/validators.ts
  package.json
  shared/adapters/chain/clover/spec.ts
  shared/adapters/chain/darwinia/spec.ts
  shared/substrate.ts
  yarn.lock
Labels: 2, A0-please QA, A0-please review, bug, cleanup

#1176 New implementation of arbitrary token forums.
  README.md
  client/scripts/app.ts
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/chain/ethereum/main.ts
  client/scripts/controllers/chain/ethereum/token/adapter.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/controllers/server/user/roles.ts
  client/scripts/helpers/index.ts
  client/scripts/models/Account.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/types.ts
  client/scripts/state.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/proposal_card.ts
  client/scripts/views/components/reaction_button.ts
  client/scripts/views/layout.ts
  client/scripts/views/modals/create_community_modal.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/profile/profile_comment_group.ts
  client/scripts/views/pages/profile/profile_proposal.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  server-test.ts
  server.ts
  server/migrations/20210513234950-fix-eth-again.js
  server/models/address.ts
  server/passport.ts
  server/router.ts
  server/routes/createAddress.ts
  server/routes/createComment.ts
  server/routes/createCommunity.ts
  server/routes/createReaction.ts
  server/routes/createRole.ts
  server/routes/createThread.ts
  server/routes/getAddressStatus.ts
  server/routes/getTokenForum.ts
  server/routes/getTokensFromLists.ts
  server/routes/linkExistingAddressToChain.ts
  server/routes/verifyAddress.ts
  server/scripts/resetServer.ts
  server/util/tokenBalanceCache.ts
  server/util/tokenListCache.ts
  shared/types.ts
  shared/utils.ts
  test/unit/api/tokenForum.spec.ts
  test/util/modelUtils.ts
Labels: 13, A7-looks good, enhancement, high priority, major project

#1184 Offchain Polling
  client/scripts/app.ts
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/helpers/index.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/models/OffchainComment.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/models/OffchainVote.ts
  client/scripts/models/index.ts
  client/scripts/models/types.ts
  client/scripts/views/components/poll_editor.ts
  client/scripts/views/modals/create_community_modal.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/components/poll_editor.scss
  client/styles/pages/discussions/discussion_row.scss
  client/styles/pages/view_proposal/index.scss
  server/migrations/20210302015110-add-offchain-polls.js
  server/migrations/20210421181754-remove-heartbeat-events.js
  server/models/offchain_thread.ts
  server/models/offchain_vote.ts
  server/router.ts
  server/routes/bulkOffchain.ts
  server/routes/bulkThreads.ts
  server/routes/updateOffchainVote.ts
  server/routes/updateThreadPolling.ts
  server/routes/viewOffchainVotes.ts
  shared/utils.ts
Labels: enhancement

#1151 Search 2.0
  client/scripts/app.ts
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/chain/ethereum/account.ts
  client/scripts/helpers/search.ts
  client/scripts/state.ts
  client/scripts/views/components/chain_icon.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/components/markdown_formatted_text.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/components/quill_formatted_text.ts
  client/scripts/views/components/search_bar.ts
  client/scripts/views/components/sidebar/community_selector.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/components/sidebar/mobile.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/mobile/mobile_header.ts
  client/scripts/views/mobile/mobile_icons.ts
  client/scripts/views/mobile/mobile_sidebar.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/modals/select_address_modal.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/search.ts
  client/scripts/views/sublayout.ts
  client/styles/components/chain_icon.scss
  client/styles/components/header/login_selector.scss
  client/styles/components/sidebar/community_selector.scss
  client/styles/components/sidebar/index.scss
  client/styles/layout.scss
  client/styles/mobile/mobile_header.scss
  client/styles/mobile/mobile_sidebar.scss
  client/styles/pages/search.scss
  client/styles/shared.scss
  client/styles/sublayout.scss
  server/database.ts
  server/models/address.ts
  server/router.ts
  server/routes/bulkAddresses.ts
  server/routes/getAddressStatus.ts
  server/routes/getCommunitiesAndChains.ts
  server/routes/linkExistingAddressToChain.ts
  server/routes/search.ts
  server/scripts/migrateChainEntities.ts
  server/util/lookupAddressIsOwnedByUser.ts
  server/webhookNotifier.ts
Labels: 13, enhancement

#1192 Landing page fixes + Search 2.0 integration
  client/scripts/helpers/search.ts
  client/scripts/views/components/search_bar.ts
  client/scripts/views/pages/landing/chains_slider.ts
  client/scripts/views/pages/landing/creators_card_section.ts
  client/scripts/views/pages/landing/find_your_token_input.ts
  client/scripts/views/pages/landing/index.ts
  client/scripts/views/pages/landing/input_token_option.ts
  client/scripts/views/pages/landing/input_tokens_lists.ts
  client/scripts/views/pages/landing/landing_page_footer.ts
  client/scripts/views/pages/landing/landing_page_header.ts
  client/scripts/views/pages/landing/landing_page_pre_footer.ts
  client/scripts/views/pages/landing/tokens_community_hero.ts
  server/routes/getTokensFromLists.ts
  server/util/tokenBalanceCache.ts
Labels: 5, A0-please QA, A0-please review

#1195 Favicons + footer links links
  180.png
  192.png
  512.png
  client/index.html
  client/scripts/views/pages/commonwealth/index.ts
  client/scripts/views/pages/landing/index.ts
  favicon.ico
  favicon.svg
  manifest.webmanifest
  static/img/logo.png
Labels: 2

#1198 Fix token forum tests and front-end token balance gating.
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/chain/ethereum/token/adapter.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/sublayout.ts
  server-test.ts
  server/models/address.ts
  server/util/tokenBalanceCache.ts
  test/unit/api/index.spec.ts
  test/unit/api/tokenForum.spec.ts
  test/util/modelUtils.ts
Labels: 1, 2, A0-please QA, A0-please review, bug, cleanup

#1206 Ensure thread and comment reactions are fetched for all discussion pages
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/stores/ReactionStore.ts
  client/scripts/views/components/reaction_button.ts
  server/models/offchain_comment.ts
  server/models/offchain_thread.ts
  server/routes/getThread.ts
  server/routes/viewComments.ts
Labels: 2

#1177 Add Crust Network Support (No Chain Events)
  client/scripts/app.ts
  client/scripts/controllers/chain/crust/main.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/models/types.ts
  client/scripts/views/pages/validators.ts
  server/migrations/20210512232604-add-crust.js
  server/scripts/resetServer.ts
  shared/adapters/chain/crust/spec.ts
  shared/substrate.ts
  static/img/protocols/crust.png
Labels: 5, A7-looks good
