Repository hicommonwealth/commonwealth, pull requests merged in 2021-08, with the labels that each got.

#1264 Made favourite community sidebar scrollable
  client/scripts/views/components/sidebar/index.ts
  client/styles/components/sidebar/index.scss
Labels: qa or code review

#1283 TOS close button
  client/scripts/views/sublayout.ts
  client/styles/sublayout.scss
Labels: A0-please QA, A0-please review, enhancement

#1284 Bring image and new line support to markdown editor
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/quill_editor.ts
  client/styles/components/markdown_formatted_text.scss
Labels: 3, 5

#1293 Fix keplr web3 login.
  client/scripts/models/types.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/pages/profile/index.ts
  shared/utils.ts
Labels: 3, A0-please QA, A0-please review, A2-in progress, bug

#1295 Dynamic MD table formatting; better RichText and MD image placement; initial steps toward full image support
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/styles/components/markdown_formatted_text.scss
Labels: 5

#1304 Clean up and deprecate resetServer script.
  package.json
  server.ts
  server/scripts/resetServer.ts
Labels: A0-please QA, A0-please review, 1

#1307 Aave Proposal Card Fixes
  client/scripts/views/components/proposals/aave_proposal_card_detail.ts
  client/styles/components/proposal_card.scss
  client/styles/components/proposals/aave_detail.scss
  client/styles/shared.scss
  client/styles/sublayout.scss
Labels: 2

#1309 Ensure link posts are fully editable
  client/scripts/controllers/server/threads.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  server/routes/editThread.ts
Labels: enhancement, A0-please QA, A0-please review, 3

#1308 Fix Offchain Community Creation
  client/scripts/app.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/modals/create_community_modal.ts
  client/scripts/views/modals/manage_community_modal/metadata_rows.ts
  client/scripts/views/sublayout.ts
  client/styles/components/empty_topic_placeholder.scss
  client/styles/pages/landing/community_cards.scss
  client/styles/sublayout.scss
  server/routes/createCommunity.ts
Labels: bug, A0-please QA, A0-please review

#1265 Change Manage Address Modal to show correct chain base rather than chain name
  client/scripts/views/modals/select_address_modal.ts
Labels: bug, A0-please QA, A0-please review

#1238 Move token lists into the database, rather than fetching them on server init
  package.json
  server-test.ts
  server.ts
  server/database.ts
  server/migrations/20210813153444-create-tokens-table.js
  server/models/token.ts
  server/router.ts
  server/routes/getTokenForum.ts
  server/routes/getTokensFromLists.ts
  server/scripts/loadDatabaseFromTokenLists.ts
  server/util/addTokenListsToDatabase.ts
  server/util/tokenBalanceCache.ts
  server/util/tokenListCache.ts
  test/unit/api/tokenForum.spec.ts
Labels: breaking change

#1298 Ctrl click for Notification
  client/scripts/helpers/index.ts
  client/scripts/views/components/notification_row.ts
  client/styles/components/sidebar/notification_row.scss
Labels: enhancement, A0-please QA, A0-please review

#1331 Add emitChainEvents script.
  package.json
  server/eventHandlers/storage.ts
  server/scripts/emails.ts
  server/scripts/emitChainEvents.ts
  server/scripts/setupChainEventListeners.ts
  server/scripts/testChainEvent.json
Labels: A0-please QA, A0-please review, 1, 2

#1333 Fix line breaks; linter fixes
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/modals/webhook_settings_modal.ts
Labels: bug, A0-please QA, A0-please review, 1, 2

#1340 Default template for topic
  client/scripts/controllers/server/topics.ts
  client/scripts/models/OffchainTopic.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/modals/edit_topic_modal.ts
  client/scripts/views/modals/new_topic_modal.ts
  client/scripts/views/pages/discussions/index.ts
  client/styles/modals/edit_topic_modal.scss
  client/styles/modals/new_topic_modal.scss
  server/migrations/20210823024949-topic-default-template.js
  server/models/offchain_topic.ts
  server/routes/createTopic.ts
  server/routes/editTopic.ts
Labels: A0-please QA, A0-please review
