Repository hicommonwealth/commonwealth, pull requests merged in 2021-11, with the labels that each got.

#1463 Improves chain-events logging in `dbNodes.ts` and all the event handlers
  Procfile.ce
  README.md
  package.json
  server/eventHandlers/entityArchival.ts
  server/eventHandlers/identity.ts
  server/eventHandlers/notifications.ts
  server/eventHandlers/pgIdentity.ts
  server/eventHandlers/profileCreation.ts
  server/eventHandlers/storage.ts
  server/migrations/20211011042849-add-ceVerbose-to-chainNodes.js
  server/models/chain_node.ts
  server/scripts/chainEventsConsumer.ts
  server/scripts/dbNode.ts
  shared/logging.ts
  tsconfig.consumer.json
  yarn.lock
Labels: enhancement

#1485 Migrate off Infura to Alchemy.
  README.md
  client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  client/scripts/controllers/chain/ethereum/aave/adapter.ts
  client/scripts/controllers/chain/ethereum/chain.ts
  client/scripts/views/modals/create_community_modal.ts
  client/scripts/views/stats/stats_helpers.ts
  package.json
  server-test.ts
  server/config.ts
  server/migrations/20211102132939-infura-to-alchemy.js
  server/routes/createChain.ts
  server/routes/getEdgewareLockdropLookup.ts
  server/routes/getTokenForum.ts
  server/routes/status.ts
  server/scripts/dbNode.ts
  server/scripts/resetServer.ts
  server/util/tokenBalanceCache.ts
  test/integration/chain-events-nodes.spec.ts
  yarn.lock
Labels: A0-please QA, A0-please review, 5

#1487 Bump chain events for logging.
  package.json
  yarn.lock
Labels: enhancement, 1

#1488 Ensure execution timestamp is interpreted as unix.
  client/scripts/controllers/chain/ethereum/aave/proposal.ts
Labels: bug, A0-please review, 1

#1489 Restores add existing Sputnik DAO functionality.
  client/scripts/views/modals/create_community_modal.ts
Labels: bug, A0-please review, 1

#1490 Return db logging to trace.
  server/database.ts
Labels: bug, A0-please review, 1

#1497 Ensure oversized tables in comments, threads are horizontally scrollabe
  client/styles/pages/view_proposal/index.scss
Labels: A0-please QA, A0-please review, 1

#1502 Ensure all db chains are fetched
  client/scripts/helpers/search.ts
  client/scripts/views/components/search_bar.ts
  server/router.ts
  server/routes/getCommunitiesAndChains.ts
Labels: A0-please QA, A0-please review

#1503 Add agoric chain.
  server/migrations/20211105154130-add-agoric.js
  static/img/protocols/agoric.png
Labels: enhancement, A0-please QA, A0-please review, 1

#1506 Migrate ts-loader to esbuild.
  client/scripts/models/index.ts
  client/scripts/stores/index.ts
  package.json
  webpack/webpack.common.js
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review, 1

#1501 Community Summary View Toggle
  client/scripts/app.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/views/modals/manage_community_modal/chain_metadata_management_table.ts
  client/scripts/views/modals/manage_community_modal/community_metadata_management_table.ts
  client/scripts/views/pages/discussions/index.ts
  server/migrations/20211105162821-add-discussion-summary-view-to-chains.js
  server/models/chain.ts
  server/models/offchain_community.ts
  server/routes/createCommunity.ts
  server/routes/updateChain.ts
  server/routes/updateCommunity.ts
Labels: A0-please QA, A0-please review

#1512 Add typecheck step to CI.
  .github/workflows/CI.yml
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/identities.ts
  client/scripts/controllers/chain/substrate/shared.ts
  package.json
  server/types.ts
  test/tsconfig.node.json
  tsconfig.consumer.json
  tsconfig.json
  yarn.lock
Labels: A0-please QA, A0-please review, 1, 2

#1486 Support arbitrary ethereum chains.
  client/scripts/app.ts
  client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  client/scripts/controllers/chain/ethereum/chain.ts
  client/scripts/models/NodeInfo.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/modals/create_community_modal.ts
  client/scripts/views/pages/admin.ts
  package.json
  server-test.ts
  server/migrations/20211102194022-add-eth-chain-id.js
  server/migrations/20211102200834-set-token-network-erc20-again.js
  server/migrations/20211105163851-add-ideamarket-testnet.js
  server/models/address.ts
  server/models/chain_node.ts
  server/models/token.ts
  server/router.ts
  server/routes/addChainNode.ts
  server/routes/createChain.ts
  server/routes/createComment.ts
  server/routes/createReaction.ts
  server/routes/createThread.ts
  server/routes/getSupportedEthChains.ts
  server/routes/getTokenForum.ts
  server/scripts/dbNode.ts
  server/util/addTokenListsToDatabase.ts
  server/util/supportedEthChains.ts
  server/util/tokenBalanceCache.ts
  shared/utils.ts
  test/unit/api/tokenForum.spec.ts
  test/util/modelUtils.ts
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review, 8, 13

#1523 Remove console.log for topics.
  client/scripts/controllers/server/topics.ts
Labels: A0-please review, 1

#1524 Update snapshot versioning and storage type.
  client/scripts/helpers/snapshot_utils.ts
  client/scripts/views/modals/confirm_snapshot_vote_modal.ts
  client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  client/scripts/views/pages/snapshot_proposals/proposal_row.ts
  client/scripts/views/pages/view_snapshot_proposal/index.ts
  package.json
  server/migrations/20211110181205-increase-snapshot-link-length.js
  yarn.lock
Labels: bug, A0-please QA, A0-please review, 3, 2

#1526 Ensure app.chain exists before querying decimals.
  client/scripts/views/modals/edit_topic_thresholds_modal.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
Labels: bug, A0-please review, 1

#1532 updateLinkedThread route improvements, bug fix
  client/scripts/controllers/server/threads.ts
  server/routes/updateLinkedThreads.ts
Labels: bug, A0-please QA, A0-please review

#1479 Facelift Component & Style Kit
  client/scripts/helpers/search.ts
  client/scripts/views/components/component_kit.ts
  client/scripts/views/components/component_kit/buttons.ts
  client/scripts/views/components/component_kit/component_listing.ts
  client/scripts/views/components/component_kit/forms.ts
  client/scripts/views/components/component_kit/icons.ts
  client/scripts/views/components/search_bar.ts
  client/scripts/views/components/sidebar/icons.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/mobile/mobile_header.ts
  client/scripts/views/pages/components.ts
  client/scripts/views/pages/landing/landing_page_button.ts
  client/scripts/views/pages/search.ts
  client/styles/components/component_kit/buttons.scss
  client/styles/components/component_kit/component_listing.scss
  client/styles/components/component_kit/forms.scss
  client/styles/components/component_kit/icons.scss
  client/styles/facelift.scss
  package.json
  yarn.lock
Labels: A0-please QA, A0-please review, 8, 13

#1536 Fix threshold check and only support token forum balance.
  server/util/tokenBalanceCache.ts
Labels: bug, A0-please QA, A0-please review, 1

#1534 Remove wsToHttp and support custom URL in createCommunity.
  client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  client/scripts/views/modals/create_community_modal.ts
  server/routes/createChain.ts
  server/routes/getTokenForum.ts
  server/util/tokenBalanceCache.ts
  shared/utils.ts
Labels: enhancement, A0-please QA, A0-please review, 1

#1537 Add support for cosmos decimals and tally view.
  client/scripts/controllers/chain/cosmos/account.ts
  client/scripts/controllers/chain/cosmos/chain.ts
  client/scripts/controllers/chain/cosmos/governance.ts
  client/scripts/controllers/chain/cosmos/proposal.ts
  client/scripts/controllers/chain/cosmos/types.ts
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/components/proposals/voting_results.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  server/migrations/20211118184310-add-cosmos-decimals.js
Labels: enhancement, A0-please QA, A0-please review, 2

#1543 Clean up near currency and dao list page.
  client/scripts/controllers/chain/near/chain.ts
  client/scripts/controllers/chain/near/sputnik/proposal.ts
  client/scripts/views/components/sputnik_dao_row.ts
  client/scripts/views/pages/sputnikdaos.ts
  client/styles/components/sputnik_dao_row.scss
  client/styles/pages/sputnikdaos.scss
  shared/adapters/chain/near/types.ts
Labels: A0-please QA, A0-please review, cleanup, 1

#1544 Remove extraneous subscribe to reduce ETH usage.
  client/scripts/controllers/chain/ethereum/chain.ts
Labels: A0-please review, cleanup, 1

#1547 Remove duplicate "Moderators" tab in Chain Metadata Table
  client/scripts/views/pages/manage_community/chain_metadata_management_table.ts
Labels: bug, A0-please review

#1535 Support Solana chain base.
  client/scripts/app.ts
  client/scripts/controllers/app/webWallets/phantom_web_wallet.ts
  client/scripts/controllers/app/web_wallets.ts
  client/scripts/controllers/chain/solana/account.ts
  client/scripts/controllers/chain/solana/accounts.ts
  client/scripts/controllers/chain/solana/chain.ts
  client/scripts/controllers/chain/solana/main.ts
  client/scripts/controllers/chain/solana/types.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/pages/profile/index.ts
  package.json
  server/migrations/20211118222022-add-solana.js
  server/models/address.ts
  shared/adapters/currency.ts
  shared/types.ts
  static/img/protocols/solana.png
  webpack/webpack.common.js
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review, 8

#1552 Ensure correct address is fetched for upgrading member.
  server/routes/upgradeMember.ts
  test/unit/api/roles.spec.ts
Labels: bug, A0-please QA, A0-please review, cleanup, 1
