Repository hicommonwealth/commonwealth, pull requests merged in 2021-09, with the labels that each got.

#1359 Threaded comments
  client/scripts/controllers/server/comments.ts
  client/scripts/models/OffchainComment.ts
  client/scripts/views/components/reaction_button.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/components/quill_editor.scss
  client/styles/components/reaction_button.scss
  client/styles/pages/search.scss
  client/styles/pages/view_proposal/create_comment.scss
  client/styles/pages/view_proposal/index.scss
  server/routes/viewComments.ts
Labels: A1-reviewed not ready, A3-needs resolving

#1376 Sticky sidebar, sticky header
  client/styles/components/sidebar/index.scss
  client/styles/pages/search.scss
  client/styles/sublayout.scss
Labels: enhancement, A0-please QA, A0-please review, 1, 2

#1246 Admin address invite flow
  client/scripts/state.ts
  client/scripts/views/modals/create_invite_modal.ts
  client/styles/modals/create_invite_modal.scss
Labels: bug, A0-please QA, A0-please review

#1231 Encode substrate address on the server side
  client/scripts/controllers/app/login.ts
  client/scripts/views/modals/link_new_address_modal.ts
  server/migrations/20210907192911-add-cosmos-chain-prefixes.js
  server/migrations/20210907192912-fix-substrate-and-cosmos-address.js
  server/models/address.ts
  server/models/chain.ts
  server/routes/createAddress.ts
  server/routes/verifyAddress.ts
  test/util/modelUtils.ts
Labels: A0-please QA, A0-please review

#1389 Decouple Address Profiles
  client/scripts/controllers/server/profiles.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/styles/pages/view_proposal/create_comment.scss
  server/routes/updateProfile.ts
Labels: A0-please QA, A0-please review

#1400 Support > 2 voting options on Snapshot Proposals
  client/scripts/helpers/index.ts
  client/scripts/views/modals/confirm_snapshot_vote_modal.ts
  client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  client/scripts/views/pages/view_snapshot_proposal/index.ts
  client/styles/components/new_thread_form.scss
  client/styles/components/proposals/voting_actions.scss
  client/styles/components/proposals/voting_results.scss
Labels: enhancement, A0-please QA, A0-please review, 3

#1197 Add prettier library and CI.
  .eslintrc.json
  .prettierrc.json
  package.json
  yarn.lock
Labels: enhancement, A0-please review, cleanup, 1, 2

#1411 Add synopsis view to offchain polling
  client/scripts/models/OffchainThread.ts
  client/scripts/views/modals/offchain_voting_modal.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/styles/modals/offchain_voting_modal.scss
  client/styles/pages/view_proposal/index.scss
Labels: enhancement, A0-please QA, A0-please review, 1, 2

#1429 Ensure the discussion Summary view displays a complete listing of recent activity
  client/scripts/controllers/app/recent_activity.ts
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/discussions/summary_listing.ts
  client/styles/pages/discussions/summary_listing.scss
  server/router.ts
  server/routes/activeThreads.ts
  server/routes/createThread.ts
  server/routes/status.ts
Labels: bug, 5

#1426 Upgrade Cosmos support to Stargate.
  client/scripts/controllers/app/webWallets/injective_web_wallet.ts
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  client/scripts/controllers/chain/cosmos/README.md
  client/scripts/controllers/chain/cosmos/account.ts
  client/scripts/controllers/chain/cosmos/accounts.ts
  client/scripts/controllers/chain/cosmos/chain.ts
  client/scripts/controllers/chain/cosmos/governance.ts
  client/scripts/controllers/chain/cosmos/main.ts
  client/scripts/controllers/chain/cosmos/proposal.ts
  client/scripts/controllers/chain/cosmos/types.ts
  client/scripts/helpers/index.ts
  client/scripts/models/types.ts
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/components/widgets/account_balance.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/view_proposal/index.ts
  package.json
  server/migrations/20210910144904-update-cosmos-node-urls.js
  server/migrations/20210913145825-add-injective-testnet.js
  server/migrations/20210913200736-add-cosmos-local.js
  server/models/address.ts
  shared/adapters/chain/cosmos/keys.ts
  shared/utils.ts
  webpack/webpack.common.js
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review, 8, 13
