Repository hicommonwealth/commonwealth, pull requests merged in 2021-04, with the labels that each got.

#1138 Bump versions and handle createApi timeout.
  package.json
  server/scripts/migrateChainEntities.ts
  server/scripts/migrateCouncillorValidatorFlags.ts
  server/scripts/migrateIdentities.ts
  yarn.lock
Labels: 1, A0-please QA, A0-please review, enhancement

#1127 Unifying chainbase address linking
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/server/user/roles.ts
  client/scripts/models/RoleInfo.ts
  client/scripts/models/types.ts
  client/scripts/views/components/chain_icon.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/modals/select_address_modal.ts
  client/scripts/views/pages/profile/profile_comment_group.ts
  client/scripts/views/pages/profile/profile_proposal.ts
  client/scripts/views/pages/web3login.ts
  client/styles/components/widgets/user.scss
  server/models/address.ts
  server/router.ts
  server/routes/createAddress.ts
  server/routes/linkExistingAddressToChain.ts
  server/routes/updateProfile.ts
  static/img/protocols/cosmos.png
  static/img/protocols/ethereum.png
  static/img/protocols/substrate.png
Labels: A0-please QA, A0-please review, enhancement

#1100 Add claim address dropdown to profile.
  client/scripts/models/Profile.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/pages/profile/profile_header.ts
  client/styles/components/login_with_wallet_dropdown.scss
  client/styles/modals/link_new_address_modal.scss
  client/styles/pages/profile.scss
Labels: 1, 2, A0-please QA, A0-please review, A2-in progress, enhancement

#1121 Skip event storage if included addresses not found.
  package.json
  server/eventHandlers/storage.ts
  server/scripts/setupChainEventListeners.ts
  test/unit/events/entityArchivalHandler.spec.ts
  test/unit/events/storageHandler.spec.ts
  yarn.lock
Labels: 1, A0-please review, A2-in progress, enhancement

#1144 Skip heartbeat events.
  server/migrations/20210421181754-remove-heartbeat-events.js
  server/scripts/setupChainEventListeners.ts
Labels: 1
