Repository hicommonwealth/commonwealth, pull requests merged in 2021-03, with the labels that each got.

#1102 Auto-create ChainEventTypes.
  server/eventHandlers/storage.ts
  test/unit/events/storageHandler.spec.ts
Labels: 1, A0-please review, enhancement

#1106 Add selectSpec function for substrate chains.
  client/scripts/controllers/chain/stafi/main.ts
  server/scripts/migrateChainEntities.ts
  server/scripts/migrateCouncillorValidatorFlags.ts
  server/scripts/migrateIdentities.ts
  server/scripts/setupChainEventListeners.ts
  shared/adapters/chain/stafi/spec.ts
  shared/substrate.ts
Labels: 1, A0-please QA, A0-please review, enhancement

#1052 Remove signaling proposal logic.
  client/scripts/app.ts
  client/scripts/controllers/chain/centrifuge/main.ts
  client/scripts/controllers/chain/darwinia/main.ts
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/edgeware/signaling_proposal.ts
  client/scripts/controllers/chain/kulupu/main.ts
  client/scripts/controllers/chain/kusama/main.ts
  client/scripts/controllers/chain/phala/main.ts
  client/scripts/controllers/chain/plasm/main.ts
  client/scripts/controllers/chain/polkadot/main.ts
  client/scripts/controllers/chain/stafi/main.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/helpers/chain_notification_types.ts
  client/scripts/identifiers.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/components/proposals/voting_results.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/modals/tx_signing_modal.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/new_signaling.ts
  client/scripts/views/pages/notifications.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/proposals.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/pages/new_signaling.scss
  server/eventHandlers/profileCreation.ts
  server/util/proposalIdToEntity.ts
  shared/adapters/chain/edgeware/types.ts
  shared/types.ts
Labels: 1, A0-please QA, A0-please review, enhancement

#1108 Auto-disable Substrate modules and cleanup view module loading.
  client/scripts/controllers/chain/centrifuge/main.ts
  client/scripts/controllers/chain/darwinia/main.ts
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/plasm/main.ts
  client/scripts/controllers/chain/stafi/main.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/democracy.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/identities.ts
  client/scripts/controllers/chain/substrate/phragmen_elections.ts
  client/scripts/controllers/chain/substrate/treasury.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/ProposalModule.ts
  client/scripts/views/pages/council/index.ts
  client/scripts/views/pages/new_proposal/index.ts
  client/scripts/views/pages/proposals.ts
  client/scripts/views/pages/referenda.ts
  client/scripts/views/pages/treasury.ts
  client/scripts/views/pages/view_proposal/index.ts
Labels: 2, A0-please QA, A0-please review, cleanup

#1017 Add $ALEX Eth Token Forum
  client/scripts/app.ts
  client/scripts/controllers/chain/ethereum/account.ts
  client/scripts/controllers/chain/ethereum/accounts.ts
  client/scripts/controllers/chain/ethereum/token/adapter.ts
  client/scripts/controllers/chain/ethereum/token/api.ts
  client/scripts/controllers/chain/ethereum/token/chain.ts
  client/scripts/controllers/server/user/roles.ts
  client/scripts/models/types.ts
  client/scripts/views/components/empty_topic_placeholder.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/reaction_button.ts
  client/scripts/views/pages/admin.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  server-test.ts
  server.ts
  server/migrations/20210226030113-add-alex-token.js
  server/models/address.ts
  server/models/chain_node.ts
  server/router.ts
  server/routes/acceptInvite.ts
  server/routes/createComment.ts
  server/routes/createReaction.ts
  server/routes/createRole.ts
  server/routes/createThread.ts
  server/routes/createTopic.ts
  server/routes/drafts/getDrafts.ts
  server/routes/getInviteLinks.ts
  server/routes/getInvites.ts
  server/routes/getProfile.ts
  server/routes/updateTopics.ts
  server/routes/viewCount.ts
  server/routes/webhooks/getWebhooks.ts
  server/scripts/resetServer.ts
  server/util/cacheJobRunner.ts
  server/util/identityFetchCache.ts
  server/util/tokenBalanceCache.ts
  static/img/protocols/alex.png
  test/unit/api/roles.spec.ts
  test/unit/api/tokenForum.spec.ts
  test/util/modelUtils.ts
Labels: 13, A3-needs resolving, enhancement

#1111 Use new Chain properties in verifyAddress.
  server-test.ts
  server/migrations/20210225221835-add-clover-finance.js
  server/migrations/20210301230133-add-hydradx.js
  server/models/address.ts
Labels: 1, A0-please QA, A0-please review, enhancement

#916 Add Marlin Governance Integration (WIP)
  README.md
  client/scripts/app.ts
  client/scripts/controllers/chain/ethereum/marlin/adapter.ts
  client/scripts/controllers/chain/ethereum/marlin/api.ts
  client/scripts/controllers/chain/ethereum/marlin/chain.ts
  client/scripts/controllers/chain/ethereum/marlin/governance.ts
  client/scripts/controllers/chain/ethereum/marlin/holder.ts
  client/scripts/controllers/chain/ethereum/marlin/holders.ts
  client/scripts/controllers/chain/ethereum/marlin/proposal.ts
  client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  client/scripts/controllers/chain/ethereum/moloch/api.ts
  client/scripts/identifiers.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/Profile.ts
  client/scripts/models/types.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/components/proposal_row.ts
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/components/proposals/voting_results.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/delegate.ts
  client/scripts/views/pages/finish_near_login.ts
  client/scripts/views/pages/new_proposal/index.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/proposals.ts
  client/styles/components/widgets/user.scss
  client/styles/pages/proposals.scss
  eth/contracts/Marlin/GovernorAlpha.sol
  eth/contracts/Marlin/MPond.sol
  eth/contracts/Marlin/Timelock.sol
  eth/types/GovernorAlpha.d.ts
  eth/types/GovernorAlphaFactory.ts
  eth/types/MPond.d.ts
  eth/types/MPondFactory.ts
  eth/types/MPondInterface.d.ts
  eth/types/MPondInterfaceFactory.ts
  eth/types/Timelock.d.ts
  eth/types/TimelockFactory.ts
  eth/types/TimelockInterface.d.ts
  eth/types/TimelockInterfaceFactory.ts
  eth/types/index.d.ts
  server/database.ts
  server/migrations/20210304154722-add-marlin.js
  server/scripts/emails.ts
  server/scripts/resetServer.ts
  server/scripts/setupChainEventListeners.ts
  server/util/proposalIdToEntity.ts
  shared/adapters/chain/ethereum/types.ts
  shared/adapters/chain/marlin/types.ts
  static/img/protocols/klp.png
  static/img/protocols/lin.png
  yarn.lock
Labels: 13, A2-in progress, enhancement

#1119 Chain Entity Titles, pts 2+3
  client/scripts/controllers/chain/cosmos/proposal.ts
  client/scripts/controllers/chain/substrate/collective_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/democracy_proposals.ts
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/controllers/chain/substrate/phragmen_election.ts
  client/scripts/controllers/chain/substrate/treasury_proposal.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/models/ChainEntity.ts
  client/scripts/models/Proposal.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/pages/view_proposal/index.scss
  server/migrations/20190510184156-setup.js
  server/migrations/20210203200024-add-title-to-chain-entities.js
  server/models/chain_entity.ts
  server/router.ts
  server/routes/fetchEntityTitle.ts
  server/routes/updateChainEntityTitle.ts
Labels: A0-please QA, A0-please review, enhancement

#1095 Switch VersionHistory fetches from bulk endpoints to fetchThread & comment refresh calls
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/models/OffchainComment.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/views/modals/version_history_modal.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/modals/version_history_modal.scss
  server/migrations/20210225201634-ensure-all-threads-have-version-history.js
  server/migrations/20210315215127-ensure-all-comments-have-version-history.js
  server/routes/bulkOffchain.ts
  server/routes/bulkThreads.ts
  server/util/getLastEdited.ts
Labels: 3, 5, A0-please QA, A0-please review

#1117 Better Display of Linked Metadata in Twitter and other Webhooks
  client/index.html
  server/config.ts
  server/scripts/setupAppRoutes.ts
  server/webhookNotifier.ts
  shared/utils.ts
Labels: enhancement

#1049 Add Bounties
  client/scripts/app.ts
  client/scripts/controllers/chain/substrate/bounty.ts
  client/scripts/controllers/chain/substrate/bountyTreasury.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/identifiers.ts
  client/scripts/models/types.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/bounties.ts
  client/scripts/views/pages/delegate.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/treasury.ts
  package.json
  server-test.ts
  server/migrations/20210216224040-add-bounty-chain-event-types.js
  shared/adapters/chain/substrate/types.ts
  yarn.lock
Labels: 13, enhancement

#1125 User-set proposal titles, part 4: Author-setting
  client/scripts/controllers/chain/substrate/democracy_proposal.ts
  client/scripts/controllers/chain/substrate/treasury_proposal.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/views/pages/view_proposal/index.ts
  server/eventHandlers/entityArchival.ts
  server/routes/updateChainEntityTitle.ts
Labels: A3-needs resolving, enhancement

#1132 Remove console log from search
  client/scripts/views/components/quill_formatted_text.ts
Labels: A0-please review, bug

#1136 Hotfix for referenda loading.
  client/scripts/views/pages/referenda.ts
Labels: 1
