Repository hicommonwealth/commonwealth, pull requests merged in 2021-12, with the labels that each got.

#1551 Create community page updates, Cosmos/DAO support.
  client/scripts/app.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/views/components/avatar_upload.ts
  client/scripts/views/components/metadata_rows.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/modals/create_community_modal.ts
  client/scripts/views/pages/admin.ts
  client/scripts/views/pages/create_community/chain_input_rows.ts
  client/scripts/views/pages/create_community/cosmos_form.ts
  client/scripts/views/pages/create_community/erc20_form.ts
  client/scripts/views/pages/create_community/eth_dao_form.ts
  client/scripts/views/pages/create_community/index.ts
  client/scripts/views/pages/create_community/offchain_community_form.ts
  client/scripts/views/pages/create_community/sputnik_form.ts
  client/scripts/views/pages/create_community/substrate_form.ts
  client/scripts/views/pages/manage_community/chain_metadata_management_table.ts
  client/scripts/views/pages/manage_community/community_metadata_management_table.ts
  client/scripts/views/pages/manage_community/manage_roles_row.ts
  client/scripts/views/sublayout.ts
  client/styles/modals/create_community_modal.scss
  client/styles/pages/create_community.scss
  server/routes/addChainNode.ts
  server/routes/createChain.ts
  server/routes/getTokenForum.ts
Labels: enhancement, A0-please QA, A0-please review, 8, 13

#1558 Create abstract token adapter.
  client/scripts/app.ts
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/chain/community/account.ts
  client/scripts/controllers/chain/cosmos/account.ts
  client/scripts/controllers/chain/ethereum/account.ts
  client/scripts/controllers/chain/ethereum/moloch/governance.ts
  client/scripts/controllers/chain/ethereum/token/adapter.ts
  client/scripts/controllers/chain/ethereum/token/api.ts
  client/scripts/controllers/chain/ethereum/token/chain.ts
  client/scripts/controllers/chain/ethereum/tokenAdapter.ts
  client/scripts/controllers/chain/near/account.ts
  client/scripts/controllers/chain/solana/account.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/models/Account.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/ITokenAdapter.ts
  client/scripts/models/index.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/reaction_button.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/modals/token_management_modal.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/settings/send_edg_well.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/sublayout.ts
  client/styles/modals/token_management_modal.scss
  client/styles/pages/settings/send_edg_well.scss
  package.json
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review, cleanup, 3

#1559 Readd URL arg to getTokenForum.
  client/scripts/views/pages/create_community/erc20_form.ts
  client/scripts/views/pages/discussions/index.ts
  server/routes/createChain.ts
  server/routes/getTokenForum.ts
Labels: bug, A0-please QA, A0-please review, 1

#1560 Correct param on Cosmos createChain call.
  client/scripts/views/pages/create_community/cosmos_form.ts
Labels: bug, A0-please review, 1

#1554 Admin CommunityOptionsPopover Carat Fix
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/manage_community/index.ts
  client/scripts/views/pages/members.ts
  client/scripts/views/pages/proposals.ts
  client/scripts/views/pages/snapshot_proposals/index.ts
  client/scripts/views/pages/stats.ts
  client/scripts/views/sublayout.ts
  client/styles/components/dropdown_icon.scss
Labels: bug, 1

#1561 Support Solana token forums.
  client/scripts/app.ts
  client/scripts/controllers/chain/solana/tokenAdapter.ts
  client/scripts/controllers/chain/solana/types.ts
  client/scripts/models/ITokenAdapter.ts
  client/scripts/views/modals/edit_topic_thresholds_modal.ts
  client/scripts/views/pages/create_community/index.ts
  client/scripts/views/pages/create_community/spl_token_form.ts
  package.json
  server/routes/createChain.ts
  server/util/tokenBalanceCache.ts
  shared/types.ts
  test/util/modelUtils.ts
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review, 3, 2

#1562 Factor out token decimal input.
  client/scripts/helpers/index.ts
  client/scripts/views/components/token_decimal_input.ts
  client/scripts/views/modals/edit_topic_thresholds_modal.ts
  client/scripts/views/modals/new_topic_modal.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/styles/components/token_decimal_input.scss
Labels: A2-in progress, 2, blocked

#1565 Implemented Lazy Loading for Members Page
  client/scripts/views/pages/members.ts
  client/styles/pages/members.scss
Labels: bug, 8

#1569 Support arbitrary cosmos chain login via Keplr.
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/views/pages/create_community/cosmos_form.ts
Labels: enhancement, A0-please QA, A0-please review, 3, 2

#1570 Link Threads Title Tag and Proposals Sidebar Consolidation
  client/scripts/views/pages/view_proposal/index.ts
  client/scripts/views/pages/view_proposal/sidebar.ts
  client/styles/pages/view_proposal/index.scss
Labels: enhancement, 2

#1571 Proxy cosmos requests through server to fix CORS issues.
  client/scripts/controllers/chain/cosmos/chain.ts
  client/scripts/views/pages/create_community/cosmos_form.ts
  server.ts
  server/router.ts
  server/routes/createChain.ts
  server/util/cosmosProxy.ts
Labels: enhancement, A0-please QA, A0-please review, 3, 2

#1572 Fix snapshot redirect bug
  client/scripts/views/components/new_proposal_button.ts
Labels: bug, 1

#1573 Thread decoding falls back on error.
  client/scripts/controllers/server/threads.ts
Labels: bug, A0-please QA, A0-please review, 1

#1575 Markdown parser fixes
  client/scripts/lib/markdownShortcuts.js
Labels: A0-please QA, A0-please review, 2

#1583 Login dropdown shows wallet name instead of base.
  client/scripts/controllers/app/webWallets/injective_web_wallet.ts
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  client/scripts/controllers/app/webWallets/phantom_web_wallet.ts
  client/scripts/controllers/app/webWallets/polkadot_web_wallet.ts
  client/scripts/controllers/app/webWallets/terra_station_web_wallet.ts
  client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  client/scripts/views/components/chain_icon.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  static/img/wallets/inj-metamask.png
  static/img/wallets/keplr.png
  static/img/wallets/metamask.png
  static/img/wallets/near.png
  static/img/wallets/phantom.jpg
  static/img/wallets/phantom.png
  static/img/wallets/polkadot.jpg
  static/img/wallets/polkadot.png
  static/img/wallets/terrastation.png
  static/img/wallets/walletconnect.png
Labels: A0-please QA, A0-please review, cleanup, 1

#1590 Add Sputnik Vote type to new proposal form.
  client/scripts/controllers/chain/near/sputnik/dao.ts
  client/scripts/controllers/chain/near/sputnik/proposal.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
Labels: enhancement, A0-please QA, A0-please review, 1

#1586 Support addEthereumChain and remove unsupported RPC for Celo.
  client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  client/scripts/controllers/chain/ethereum/chain.ts
  package.json
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review, 8

#1584 Gradient Hover Button (used for Hiring Button for now)
  client/scripts/views/components/component_kit/buttons.ts
  client/scripts/views/components/component_kit/component_listing.ts
  client/scripts/views/sublayout.ts
  client/styles/components/component_kit/buttons.scss
  client/styles/sublayout.scss
Labels: enhancement, 2

#1581 Handle Multiple Snapshot Spaces for a Community
  client/scripts/app.ts
  client/scripts/helpers/snapshot_utils.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/components/stage_editor.ts
  client/scripts/views/pages/manage_community/chain_metadata_management_table.ts
  client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  client/scripts/views/pages/snapshot_proposals/index.ts
  client/scripts/views/pages/snapshot_proposals/proposal_row.ts
  client/scripts/views/pages/view_multiple_snapshot_spaces/index.ts
  client/scripts/views/pages/view_multiple_snapshot_spaces/space_card.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/scripts/views/pages/view_proposal/sidebar.ts
  client/styles/pages/snapshot/multiple_snapshots.scss
  server/migrations/20211213195557-add-multiple-snapshots.js
  server/models/chain.ts
  server/routes/updateChain.ts
Labels: enhancement, 8

#1591 Lint-Branch Script
  package.json
  scripts/lint-branch.sh
Labels: infrastructure

#1596 Remove Pinned Threads from Summary View
  client/scripts/views/pages/discussions/index.ts
  client/styles/pages/discussions/summary_listing.scss
Labels: cleanup, 1

#1597 Alex.multiple snapshot bug
  server/routes/updateChain.ts
Labels: 1

#1598 Multiple Snapshots Null String Fix
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/view_proposal/index.ts
  server/migrations/20211222234851-snapshots-remove-empty-strings.js
  server/routes/updateChain.ts
Labels: 1

#1594 Disallow non-alphanum chars in new topics
  client/scripts/helpers/index.ts
  client/scripts/views/components/component_kit/forms.ts
  client/scripts/views/modals/new_topic_modal.ts
  server/migrations/20211222191316-remove-non-alphanumeric-chars-from-topic-names.js
  server/routes/createTopic.ts
Labels: bug, A0-please QA, A0-please review

#1603 Ensure Markdown handling is Safari-friendly
  client/scripts/lib/markdownShortcuts.js
Labels: bug, A0-please QA, A0-please review

#1553 Search 3.0
  client/scripts/controllers/server/search.ts
  client/scripts/helpers/search.ts
  client/scripts/models/SearchQuery.ts
  client/scripts/models/SearchResult.ts
  client/scripts/models/index.ts
  client/scripts/state.ts
  client/scripts/stores/SearchStore.ts
  client/scripts/views/components/component_kit/component_listing.ts
  client/scripts/views/components/component_kit/icons.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/components/search_bar.ts
  client/scripts/views/components/thread_selector.ts
  client/scripts/views/modals/create_invite_modal.ts
  client/scripts/views/pages/landing/tokens_community_hero.ts
  client/scripts/views/pages/search.ts
  client/styles/pages/search.scss
  server/migrations/20211117015845-rank-search-results.js
  server/router.ts
  server/routes/searchComments.ts
  server/routes/searchDiscussions.ts
Labels: enhancement

#1607 Fix Search Bugs
  client/scripts/controllers/server/search.ts
  server/routes/searchComments.ts
  server/routes/searchDiscussions.ts
Labels: bug

#1606 Do not display voters for completed cosmos proposals.
  client/scripts/views/components/proposals/voting_results.ts
Labels: A0-please QA, A0-please review, A3-needs resolving, cleanup, 1

#1602 Link Snapshot to Threads for Admins
  client/scripts/controllers/server/threads.ts
  client/scripts/views/components/stage_editor.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/scripts/views/pages/view_proposal/sidebar.ts
  client/scripts/views/pages/view_snapshot_proposal/index.ts
  server/routes/fetchThreadForSnapshot.ts
  server/routes/updateThreadLinkedSnapshotProposal.ts
  server/routes/updateThreadStage.ts
Labels: enhancement, 1

#1609 Support more proposal titles for Sputnik apps.
  client/scripts/controllers/chain/near/sputnik/proposal.ts
  client/scripts/controllers/chain/near/sputnik/types.ts
Labels: enhancement, A0-please QA, A0-please review, 1

#1604 Fix tx signing when using Keplr's experimentalSuggestChain.
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  server/models/address.ts
Labels: bug, A0-please QA, A0-please review, 1, 2

#1610 Bump chain events to fix entity migration.
  package.json
  yarn.lock
Labels: bug, A0-please review, 1

#1605 Add custom & infinite poll durations
  client/scripts/controllers/server/threads.ts
  client/scripts/helpers/index.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/views/components/poll_editor.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/components/poll_editor.scss
  server/migrations/20211227213351-add-poll-enabled-col.js
  server/models/offchain_thread.ts
  server/routes/bulkThreads.ts
  server/routes/updateOffchainVote.ts
  server/routes/updateThreadPolling.ts
Labels: enhancement, A0-please QA, A0-please review, 5
