Repository hicommonwealth/commonwealth, pull requests merged in 2021-07, with the labels that each got.

#1240 Offchain Polls v2
  client/scripts/controllers/server/threads.ts
  client/scripts/helpers/index.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/models/OffchainVote.ts
  client/scripts/models/index.ts
  client/scripts/models/types.ts
  client/scripts/views/components/poll_editor.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/components/stage_editor.ts
  client/scripts/views/components/topic_selector.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/scripts/views/sublayout.ts
  client/styles/components/listing_row.scss
  client/styles/components/poll_editor.scss
  client/styles/components/sidebar/index.scss
  client/styles/components/stage_editor.scss
  client/styles/components/widgets/user_gallery.scss
  client/styles/construct.scss
  client/styles/pages/discussions/discussion_row.scss
  client/styles/pages/view_proposal/index.scss
  client/styles/shared.scss
  client/styles/sublayout.scss
  server/migrations/20210630185936-add-options-spec-to-offchain-polls.js
  server/models/offchain_thread.ts
  server/routes/bulkOffchain.ts
  server/routes/bulkThreads.ts
  server/routes/updateThreadPolling.ts
  shared/utils.ts
Labels: enhancement

#1242 Tips "Reason" fix: Commonwealth links open in the same tab
  client/scripts/views/components/markdown_formatted_text.ts
Labels: 1

#1245 Update User component address display options
  client/scripts/views/components/search_bar.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/pages/search.ts
  shared/utils.ts
Labels: 1, 2, A0-please QA, A0-please review, enhancement

#1249 Ensure search SVG always renders
  client/scripts/helpers/search.ts
  client/scripts/views/components/proposal_card.ts
  client/scripts/views/components/search_bar.ts
  client/scripts/views/pages/landing/index.ts
  client/scripts/views/pages/landing/tokens_community_hero.ts
Labels: A0-please QA, A0-please review, bug

#1161 Adds Injective and Osmosis, Cosmos Rewrite with cosmjs
  client/scripts/app.ts
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  client/scripts/controllers/chain/community/account.ts
  client/scripts/controllers/chain/cosmos/account.ts
  client/scripts/controllers/chain/cosmos/chain.ts
  client/scripts/controllers/chain/cosmos/governance.ts
  client/scripts/controllers/chain/cosmos/main.ts
  client/scripts/controllers/chain/cosmos/proposal.ts
  client/scripts/controllers/chain/cosmos/types.ts
  client/scripts/controllers/chain/ethereum/account.ts
  client/scripts/controllers/chain/ethereum/accounts.ts
  client/scripts/controllers/chain/near/account.ts
  client/scripts/controllers/chain/straightedge/main.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/models/Account.ts
  client/scripts/models/types.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/components/proposals/voting_results.ts
  client/scripts/views/modals/message_signing_modal.ts
  client/scripts/views/modals/tx_signing_modal.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/view_proposal/index.ts
  package.json
  server/migrations/20210707150138-add-osmosis-chain.js
  server/migrations/20210709164618-add-injective-chain.js
  server/models/address.ts
  server/scripts/resetServer.ts
  shared/adapters/chain/cosmos/api.ts
  shared/adapters/chain/cosmos/keys.ts
  shared/utils.ts
  static/img/protocols/injective.png
  static/img/protocols/osm.png
  webpack/webpack.common.js
  yarn.lock
Labels: 13, 8, A0-please QA, cleanup, enhancement

#1268 Add community terms of service support
  client/scripts/app.ts
  client/scripts/models/ChainInfo.ts
  client/scripts/models/CommunityInfo.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/modals/confirm_invite_modal.ts
  client/scripts/views/modals/manage_community_modal/chain_metadata_management_table.ts
  client/scripts/views/modals/manage_community_modal/community_metadata_management_table.ts
  client/scripts/views/modals/select_address_modal.ts
  client/styles/modals/confirm_invite_modal.scss
  client/styles/modals/select_address_modal.scss
  server/migrations/20210715002927-add-terms-to-chains.js
  server/models/chain.ts
  server/models/offchain_community.ts
  server/routes/updateChain.ts
  server/routes/updateCommunity.ts
Labels: A0-please QA, A0-please review, enhancement

#1271 Snapshot Remove SimplePicker
  client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  package.json
  yarn.lock
Labels: A0-please QA, A0-please review

#1275 Featured topics
  client/scripts/controllers/server/topics.ts
  client/scripts/models/OffchainTopic.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/modals/edit_topic_modal.ts
  client/scripts/views/modals/new_topic_modal.ts
  client/scripts/views/pages/discussions/index.ts
  server/migrations/20210729160800-offchain-topic-new-featured-fields.js
  server/models/offchain_topic.ts
  server/routes/createTopic.ts
  server/routes/editTopic.ts
Labels: A0-please QA, A0-please review, enhancement

#1266 General custom domain support
  client/scripts/views/components/login.ts
  client/scripts/views/modals/manage_community_modal/chain_metadata_management_table.ts
  client/scripts/views/modals/manage_community_modal/community_metadata_management_table.ts
  server.ts
  server/migrations/20210727013558-add-domain-to-login-tokens.js
  server/migrations/20210727022413-add-socialaccount-to-login-tokens.js
  server/models/login_token.ts
  server/passport.ts
  server/router.ts
  server/routes/finishEmailLogin.ts
  server/routes/finishOAuthLogin.ts
  server/routes/startEmailLogin.ts
  server/routes/startOAuthLogin.ts
  server/routes/updateChain.ts
  server/routes/updateCommunity.ts
Labels: 13, 8, A0-please QA, A0-please review, enhancement
