Repository hicommonwealth/commonwealth, pull requests merged in 2021-06, with the labels that each got.

#1212 Invite Flow Fixes, Stage 1
  client/scripts/views/components/header/invites_menu.ts
  client/scripts/views/modals/confirm_invite_modal.ts
  client/styles/components/header/invites_menu.scss
  client/styles/modals/confirm_invite_modal.scss
Labels: A0-please QA, A0-please review, bug, enhancement

#1214 Separate and share community options popover, first pass
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/members.ts
  client/styles/components/sidebar/index.scss
Labels: 1, A0-please review

#1213 Small Invite Flow Bug Fixes
  client/scripts/views/modals/create_invite_modal.ts
  client/styles/modals/create_invite_modal.scss
  static/img/copy_default.svg
  static/img/copy_hover.svg
Labels: A0-please QA, A0-please review, bug

#1221 Tips UI
  .gitignore
  client/scripts/app.ts
  client/scripts/controllers/chain/substrate/main.ts
  client/scripts/controllers/chain/substrate/treasury_tip.ts
  client/scripts/controllers/chain/substrate/treasury_tips.ts
  client/scripts/controllers/server/chain_entities.ts
  client/scripts/identifiers.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/proposal_card.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/tips.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/pages/tips.scss
  client/styles/pages/view_proposal/tips.scss
  package.json
  server/eventHandlers/migration.ts
  server/routes/fetchEntityTitle.ts
  shared/adapters/chain/substrate/types.ts
  shared/utils.ts
  yarn.lock
Labels: A0-please QA, A0-please review

#1233 Added google tag manager script
  client/index.html
  client/scripts/app.ts
Labels: A0-please review
