Repository hicommonwealth/commonwealth, pull requests merged in 2021-01, with the labels that each got.

#1047 Bumps API versions and types to fix FIS and KLP compatibility.
  client/scripts/controllers/chain/darwinia/main.ts
  client/scripts/controllers/chain/darwinia/spec.ts
  client/scripts/controllers/chain/edgeware/main.ts
  client/scripts/controllers/chain/edgeware/signaling.ts
  client/scripts/controllers/chain/stafi/main.ts
  client/scripts/controllers/chain/substrate/collective.ts
  client/scripts/controllers/chain/substrate/identities.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/views/components/edgeware_function_picker.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  package.json
  server/scripts/migrateChainEntities.ts
  server/scripts/migrateCouncillorValidatorFlags.ts
  server/scripts/migrateIdentities.ts
  server/scripts/setupChainEventListeners.ts
  yarn.lock
Labels: 3, 5, A0-please QA, A0-please review, bug, high priority

#1050 Allow authors to add collaborators to offchain threads
  client/scripts/controllers/chain/community/main.ts
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/helpers/notifications.ts
  client/scripts/models/OffchainComment.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/modals/version_history_modal.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/notifications.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/construct.scss
  client/styles/modals/version_history_modal.scss
  client/styles/pages/discussions/discussion_row.scss
  client/styles/pages/view_proposal/editor_permissions.scss
  server-test.ts
  server/migrations/20201223183016-add-collaboration-table.js
  server/migrations/20210112001734-add-collaboration-subscriptions-to-existing-users.js
  server/models/address.ts
  server/models/collaboration.ts
  server/models/offchain_thread.ts
  server/models/subscription.ts
  server/passport.ts
  server/router.ts
  server/routes/addEditors.ts
  server/routes/bulkAddresses.ts
  server/routes/bulkOffchain.ts
  server/routes/bulkThreads.ts
  server/routes/createRole.ts
  server/routes/createThread.ts
  server/routes/deleteEditors.ts
  server/routes/editThread.ts
  server/routes/finishEmailLogin.ts
  server/routes/getProfile.ts
  server/routes/getThread.ts
  server/routes/pinThread.ts
  server/routes/setPrivacy.ts
  server/scripts/resetServer.ts
  server/webhookNotifier.ts
  shared/notificationFormatter.ts
  shared/types.ts
  test/unit/api/threads.spec.ts
Labels: 13, A0-please QA, A0-please review, enhancement

#1056 Fix VoteListing bug
  client/scripts/controllers/chain/substrate/democracy_referendum.ts
  client/scripts/views/components/proposals/voting_results.ts
Labels: 3, A0-please QA, bug

#1055 Ensure mentioned users are not doubly notified
  server/routes/createComment.ts
  server/routes/createThread.ts
Labels: 2, 3, A0-please QA, A0-please review, bug

#1061 Move version history generation from controller to endpoints
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/views/modals/version_history_modal.ts
  client/scripts/views/pages/view_proposal/body.ts
  server/routes/createComment.ts
  server/routes/createThread.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
  test/unit/api/threads.spec.ts
  test/util/modelUtils.ts
Labels: 3, 5, A0-please QA, A0-please review, bug

#1054 Ensure that mentions added while editing a thread are propagated to tagged users
  client/scripts/controllers/server/comments.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/helpers/threads.ts
  client/scripts/views/pages/view_proposal/body.ts
  server/routes/createComment.ts
  server/routes/createThread.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
Labels: 3, 5, A3-needs resolving, enhancement

#1070 Improve collaboration notifications
  server/routes/addEditors.ts
  server/routes/deleteEditors.ts
Labels: 3, 5, A0-please QA, A0-please review, bug

#1074 Ensure notification cache is cleared on initApi call
  client/scripts/app.ts
  client/scripts/controllers/server/notifications.ts
Labels: 1, A0-please QA, A0-please review, bug

#1073 Ensure batch threads notifications render properly
  client/scripts/helpers/notifications.ts
  client/scripts/views/components/header/notifications_menu.ts
  client/scripts/views/pages/notificationsList.ts
Labels: 1, 2, A0-please QA, A0-please review, bug
