Repository hicommonwealth/commonwealth, pull requests merged in 2022-03, with the labels that each got.

#1628 Basic support for creating CommunitySpend proposals.
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  client/scripts/controllers/chain/cosmos/governance.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
Labels: enhancement, A0-please QA, A0-please review, A2-in progress, 3, 2

#1733 Separate notification dispatching code from createThread.
  server/models/notifications_read.ts
  server/models/subscription.ts
  server/routes/createThread.ts
  server/routes/editThread.ts
  server/webhookNotifier.ts
  shared/types.ts
Labels: bug, enhancement, A2-in progress, 5, 3, 8

#1737 Remove notification refresh on create thread.
  client/scripts/controllers/server/threads.ts
  client/scripts/views/components/new_thread_form.ts
Labels: enhancement, A0-please QA, A0-please review, cleanup, 1

#1746 Remove hedgehog server dead code.
  package.json
  server/database.ts
  server/migrations/20220317200012-remove-hedgehog.js
  server/models/hedgehog_authentication.ts
  server/models/hedgehog_user.ts
  server/routes/createHedgehogAuthentication.ts
  server/routes/createHedgehogUser.ts
  server/routes/getHedgehogAuthentication.ts
  yarn.lock
Labels: A0-please QA, A0-please review, cleanup, 1

#1748 Clean up a few routes + helpers.
  server/router.ts
  server/routes/addChainNode.ts
  server/routes/createGist.ts
  server/routes/getInvites.ts
  server/routes/getSubstrateSpec.ts
  server/routes/updateChain.ts
  server/routes/updateOffchainVote.ts
  server/util/lookupAddressIsOwnedByUser.ts
  server/util/validateChain.ts
Labels: A0-please QA, A0-please review, cleanup, 1

#1753 Snapshot API Hardening + Snapshot UI Changes
  client/scripts/app.ts
  client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  client/scripts/controllers/chain/ethereum/aave/proposal.ts
  client/scripts/helpers/snapshot_utils.ts
  client/scripts/views/modals/confirm_snapshot_vote_modal.ts
  client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  client/scripts/views/pages/snapshot_proposals/index.ts
  client/scripts/views/pages/view_snapshot_proposal/index.ts
  client/styles/pages/snapshot/view_proposal.scss
  package.json
  yarn.lock
Labels: 8

#1768 Fix discussion row linked proposal badge suffix.
  client/scripts/models/OffchainThread.ts
Labels: bug, A0-please QA, A0-please review, 1
