Repository hicommonwealth/commonwealth, pull requests merged in 2022-10, with the labels that each got.

#2146 Add Cosmos Chain Events.
  packages/chain-events/.eslintrc.json
  packages/chain-events/scripts/listener.ts
  packages/chain-events/scripts/listenerUtils.ts
  packages/chain-events/scripts/listenerV2.ts
  packages/chain-events/src/chains/aave/storageFetcher.ts
  packages/chain-events/src/chains/commonwealth/storageFetcher.ts
  packages/chain-events/src/chains/compound/storageFetcher.ts
  packages/chain-events/src/chains/cosmos/Listener.ts
  packages/chain-events/src/chains/cosmos/filters/enricher.ts
  packages/chain-events/src/chains/cosmos/filters/labeler.ts
  packages/chain-events/src/chains/cosmos/filters/titler.ts
  packages/chain-events/src/chains/cosmos/filters/type_parser.ts
  packages/chain-events/src/chains/cosmos/index.ts
  packages/chain-events/src/chains/cosmos/processor.ts
  packages/chain-events/src/chains/cosmos/storageFetcher.ts
  packages/chain-events/src/chains/cosmos/subscribeFunc.ts
  packages/chain-events/src/chains/cosmos/subscriber.ts
  packages/chain-events/src/chains/cosmos/types.ts
  packages/chain-events/src/index.ts
  packages/chain-events/src/interfaces.ts
  packages/chain-events/src/util.ts
  packages/chain-events/test/unit/cosmos/enricher.spec.ts
  packages/chain-events/test/unit/cosmos/storageFetcher.spec.ts
  packages/chain-events/test/unit/cosmos/subscriber.spec.ts
  packages/chain-events/test/unit/cosmos/util.ts
  packages/commonwealth/client/scripts/controllers/server/chain_entities.ts
  packages/commonwealth/server/routes/migrateEvent.ts
  packages/commonwealth/server/scripts/dbNode.ts
  packages/commonwealth/server/scripts/migrateChainEntities.ts
Labels: A0-please QA, A0-please review, 8

#2118 New Login Flow
  packages/commonwealth/client/scripts/app.ts
  packages/commonwealth/client/scripts/controllers/app/login.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/cosmos_evm_metamask_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/keplr_ethereum_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/near_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/phantom_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/polkadot_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/ronin_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/terra_station_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/chain/solana/tokenAdapter.ts
  packages/commonwealth/client/scripts/controllers/server/profiles.ts
  packages/commonwealth/client/scripts/controllers/server/roles.ts
  packages/commonwealth/client/scripts/helpers/index.ts
  packages/commonwealth/client/scripts/models/Account.ts
  packages/commonwealth/client/scripts/models/IWebWallet.ts
  packages/commonwealth/client/scripts/views/app_modals.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_modal.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_profiles_list.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_text_input.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_wallet_option_row.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_wallets_list.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/helpers.ts
  packages/commonwealth/client/scripts/views/components/header/invites_menu.tsx
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/scripts/views/components/login.ts
  packages/commonwealth/client/scripts/views/components/reaction_button/helpers.tsx
  packages/commonwealth/client/scripts/views/modals/confirm_invite_modal.ts
  packages/commonwealth/client/scripts/views/modals/link_new_address_modal.ts
  packages/commonwealth/client/scripts/views/modals/login_modal.tsx
  packages/commonwealth/client/scripts/views/modals/select_address_modal.ts
  packages/commonwealth/client/scripts/views/pages/finish_axie_login.ts
  packages/commonwealth/client/scripts/views/pages/finish_near_login.ts
  packages/commonwealth/client/scripts/views/pages/landing/landing_page_header.ts
  packages/commonwealth/client/scripts/views/pages/login/helpers.ts
  packages/commonwealth/client/scripts/views/pages/login/index.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_desktop.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_desktop_sidebar.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_mobile.tsx
  packages/commonwealth/client/scripts/views/pages/login/types.ts
  packages/commonwealth/client/scripts/views/pages/notification_settings/index.tsx
  packages/commonwealth/client/scripts/views/pages/profile/profile_bio.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_header.ts
  packages/commonwealth/client/scripts/views/pages/web3login.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_wallets_list.scss
  packages/commonwealth/client/styles/components/header/login_selector.scss
  packages/commonwealth/client/styles/modals/link_new_address_modal.scss
  packages/commonwealth/client/styles/pages/login/login_mobile.scss
  packages/commonwealth/client/styles/pages/web3login.scss
  packages/commonwealth/server/routes/authCallback.ts
  packages/commonwealth/server/routes/createAddress.ts
  packages/commonwealth/server/routes/finishSsoLogin.ts
  packages/commonwealth/server/routes/verifyAddress.ts
Labels: 13

#2172 Add magic migration logic for old email users.
  packages/commonwealth/server/passport/magic.ts
Labels: bug, A0-please QA, A0-please review, 1

#2173 Add webpack define for magic publishable key.
  packages/commonwealth/client/scripts/controllers/app/login.ts
  packages/commonwealth/webpack/webpack.common.js
Labels: enhancement, cleanup, 1

#2164 Upgrade to Webpack 5
  .github/workflows/CI.yml
  packages/commonwealth/package.json
  packages/commonwealth/postcss.config.js
  packages/commonwealth/server.ts
  packages/commonwealth/server/migrations/20220811142850-add-contracts-tables.js
  packages/commonwealth/webpack/webpack.common.js
  packages/commonwealth/webpack/webpack.config.dev.js
  packages/commonwealth/webpack/webpack.config.prod.js
  packages/commonwealth/webpack/webpack.config.test.js
  yarn.lock
Labels: 5, 8

#2199 Add statsd metrics for route hits.
  packages/commonwealth/package.json
  packages/commonwealth/server.ts
  packages/commonwealth/server/scripts/setupExpressStats.ts
  packages/commonwealth/server/util/cosmosProxy.ts
  packages/commonwealth/server/util/statsd.ts
  yarn.lock
Labels: A0-please QA, A0-please review, 1, 2

#2202 Add generic Cover Image Uploader component
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_cover_image_uploader.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon_lookup.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icons.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_cover_image_uploader.scss
Labels: 5
