Repository hicommonwealth/commonwealth, pull requests merged in 2022-08, with the labels that each got.

#2009 Re-enable redis adapter
  packages/commonwealth/server/socket/index.ts
Labels: bug

#2021 Temporary change in RPC
  packages/chain-events/scripts/listenerUtils.ts
Labels: A0-please review, high priority

#1997 Polls UI + Small Button + Progress Bars Component Kit Updates
  packages/commonwealth/client/scripts/views/components/component_kit/cw_button.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_progress_bar.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/types.ts
  packages/commonwealth/client/scripts/views/components/poll_card.tsx
  packages/commonwealth/client/scripts/views/components/poll_editor.tsx
  packages/commonwealth/client/scripts/views/modals/confirm_modal.tsx
  packages/commonwealth/client/scripts/views/modals/confirm_snapshot_vote_modal.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/helpers.ts
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.ts
  packages/commonwealth/client/scripts/views/pages/view_proposal/linked_proposals_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/linked_threads_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/poll_editor_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/proposal_poll_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_information_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_proposal_cards.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_vote_action_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_voting_results_card.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_button.scss
  packages/commonwealth/client/styles/components/component_kit/cw_component_showcase.scss
  packages/commonwealth/client/styles/components/component_kit/cw_progress_bar.scss
  packages/commonwealth/client/styles/components/poll_card.scss
  packages/commonwealth/client/styles/mixins/buttons.scss
  packages/commonwealth/client/styles/mixins/choice.scss
  packages/commonwealth/client/styles/modals/confirm_modal.scss
  packages/commonwealth/client/styles/pages/snapshot/index.scss
  packages/commonwealth/client/styles/pages/snapshot/snapshot_information_card.scss
  packages/commonwealth/client/styles/pages/snapshot/snapshot_vote_action_card.scss
  packages/commonwealth/client/styles/pages/snapshot/snapshot_voting_results_card.scss
  packages/commonwealth/client/styles/pages/snapshot/view_proposal.scss
  packages/commonwealth/client/styles/pages/view_proposal/index.scss
  packages/commonwealth/client/styles/pages/view_proposal/linked_proposals_card.scss
  packages/commonwealth/client/styles/pages/view_proposal/linked_threads_card.scss
  packages/commonwealth/client/styles/pages/view_proposal/poll_editor_card.scss
  packages/commonwealth/client/styles/pages/view_proposal/proposal_poll_card.scss
Labels: 8

#2023 Permit non URI compliant text in quill text body.
  packages/commonwealth/client/scripts/views/components/quill/helpers.ts
Labels: bug, A0-please QA, A0-please review, 1

#2005 Custom Domain Update Automation
  packages/commonwealth/server/router.ts
  packages/commonwealth/server/routes/updateChainCustomDomain.ts
Labels: 3

#1959 Remote Redis and RabbitMQ Docker Containers
  packages/commonwealth/README.md
  packages/commonwealth/package.json
  packages/commonwealth/scripts/delete-docker-containers.sh
  packages/commonwealth/scripts/install-docker.sh
  packages/commonwealth/scripts/start-docker-containers.sh
  packages/commonwealth/scripts/start-docker-setup-help.sh
  packages/commonwealth/scripts/stop-docker-containers.sh
  packages/commonwealth/scripts/update-docker-images.sh
  packages/commonwealth/server/config.ts
  packages/commonwealth/server/socket/index.ts
  packages/commonwealth/server/util/rabbitmq/RabbitMQConfig.ts
  packages/commonwealth/server/util/redisCache.ts
Labels: enhancement

#2025 Add ts-alias step in CE compilation.
  packages/commonwealth/Procfile
  packages/commonwealth/package.json
  packages/commonwealth/server/tsconfig.json
  yarn.lock
Labels: A0-please QA, A0-please review, 1, 2, high priority

#2028 Improved Redis connection logging + Vultr Docker `start-containers` fix
  packages/commonwealth/scripts/start-docker-containers.sh
  packages/commonwealth/server/config.ts
  packages/commonwealth/server/socket/index.ts
  packages/commonwealth/server/util/redisCache.ts
Labels: bug, enhancement

#1958 Sidebar + Community Cards Command Click
  packages/commonwealth/client/scripts/helpers/index.ts
  packages/commonwealth/client/scripts/views/components/chat/chat_section.tsx
  packages/commonwealth/client/scripts/views/components/community_card.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/discussion_section.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/governance_section.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/discussion_row.tsx
Labels: 1

#2030 Fix axie de-linking address case.
  packages/commonwealth/server/routes/finishSsoLogin.ts
Labels: 1

#2037 Ensure no client/scripts prefixes in client imports.
  packages/commonwealth/client/scripts/views/pages/create_community/cosmos_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/substrate_form.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/helpers.ts
  packages/commonwealth/client/scripts/views/pages/discussions/pinned_listing.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/summary_listing.tsx
  packages/commonwealth/client/scripts/views/pages/members.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/dashboard_communities_preview.tsx
  packages/commonwealth/client/scripts/views/pages/view_multiple_snapshot_spaces/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_multiple_snapshot_spaces/snapshot_space_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.ts
  packages/commonwealth/client/scripts/views/pages/view_proposal/linked_threads_card.tsx
Labels: A0-please QA, A0-please review, 1

#2050 Fix mentions!
  packages/commonwealth/client/scripts/views/components/quill/quill_editor_internal.ts
Labels: bug, 1

#2051 Fix file upload, copy-paste bugs
  packages/commonwealth/client/scripts/views/components/quill/helpers.ts
  packages/commonwealth/client/scripts/views/components/quill/markdown_formatted_text.tsx
  packages/commonwealth/client/scripts/views/components/quill/quill_editor_internal.ts
  packages/commonwealth/client/scripts/views/pages/view_proposal/body.ts
Labels: bug, 2

#2053 Better Quill isBlank check, better Quill on changes listener
  packages/commonwealth/client/scripts/views/components/quill/quill_editor.ts
  packages/commonwealth/client/scripts/views/components/quill/quill_editor_internal.ts
  packages/commonwealth/client/scripts/views/pages/view_proposal/create_comment.tsx
Labels: 1

#2072 Make AddressInfo an extension of Account.
  packages/commonwealth/client/scripts/controllers/app/login.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/cosmos_evm_metamask_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/near_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/phantom_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/polkadot_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/ronin_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/terra_station_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/web_wallets.ts
  packages/commonwealth/client/scripts/controllers/chain/cosmos/account.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/account.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/contractApi.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/member.ts
  packages/commonwealth/client/scripts/controllers/chain/near/account.ts
  packages/commonwealth/client/scripts/controllers/chain/solana/account.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/account.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/democracy_proposal.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/democracy_referendum.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/phragmen_election.ts
  packages/commonwealth/client/scripts/controllers/server/profiles.ts
  packages/commonwealth/client/scripts/controllers/server/user/base.ts
  packages/commonwealth/client/scripts/controllers/server/user/roles.ts
  packages/commonwealth/client/scripts/models/Account.ts
  packages/commonwealth/client/scripts/models/AddressInfo.ts
  packages/commonwealth/client/scripts/models/IChainAdapter.ts
  packages/commonwealth/client/scripts/models/ITokenAdapter.ts
  packages/commonwealth/client/scripts/models/IWebWallet.ts
  packages/commonwealth/client/scripts/models/Identity.ts
  packages/commonwealth/client/scripts/models/Proposal.ts
  packages/commonwealth/client/scripts/models/interfaces.ts
  packages/commonwealth/client/scripts/models/votes.ts
  packages/commonwealth/client/scripts/views/components/avatar_upload.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_avatar_username_input.tsx
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/scripts/views/components/new_thread_form/new_thread_form.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/community_selector.tsx
  packages/commonwealth/client/scripts/views/components/widgets/substrate_identity.ts
  packages/commonwealth/client/scripts/views/components/widgets/user.ts
  packages/commonwealth/client/scripts/views/components/widgets/user_gallery.ts
  packages/commonwealth/client/scripts/views/modals/edit_profile_modal.tsx
  packages/commonwealth/client/scripts/views/modals/link_new_address_modal.ts
  packages/commonwealth/client/scripts/views/modals/select_address_modal.ts
  packages/commonwealth/client/scripts/views/pages/council.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/upgrade_roles_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  packages/commonwealth/client/scripts/views/pages/profile/index.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_banner.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_bio.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_comment_group.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_content.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_header.ts
  packages/commonwealth/client/scripts/views/pages/settings/linked_addresses_section.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/body.ts
  packages/commonwealth/client/scripts/views/pages/view_proposal/create_comment.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.ts
Labels: A0-please QA, A0-please review, cleanup, 5, 3

#2065 User Survey Popup
  packages/commonwealth/client/scripts/views/components/component_kit/cw_growl.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/types.ts
  packages/commonwealth/client/scripts/views/components/user_survey_popup.tsx
  packages/commonwealth/client/scripts/views/layout.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_growl.scss
  packages/commonwealth/client/styles/components/user_survey_popup.scss
  packages/commonwealth/static/img/survey_header.svg
Labels: 8

#2081 Refactor keplr to use signArbitrary
  packages/commonwealth/client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  packages/commonwealth/server/routes/verifyAddress.ts
  packages/commonwealth/shared/adapters/chain/cosmos/keys.ts
Labels: 5

#2086 Fix migrations to run from scratch
  packages/commonwealth/server/migrations/20220209053616-add-chain-attributes.js
  packages/commonwealth/server/migrations/20220601182733-add-rules-table-and-associations.js
Labels: 1

#2068 Prioritize Community Route (for an airplane task)
  packages/commonwealth/server/router.ts
  packages/commonwealth/server/routes/updateChainCustomDomain.ts
  packages/commonwealth/server/routes/updateChainPriority.ts
Labels: 2
