Repository hicommonwealth/commonwealth, pull requests merged in 2022-01, with the labels that each got.

#1608 No longer subscribe to block numbers.
  client/scripts/controllers/chain/cosmos/chain.ts
  client/scripts/controllers/chain/ethereum/aave/governance.ts
  client/scripts/controllers/chain/ethereum/aave/proposal.ts
  client/scripts/controllers/chain/ethereum/chain.ts
  client/scripts/controllers/chain/ethereum/compound/governance.ts
  client/scripts/controllers/chain/ethereum/compound/proposal.ts
  client/scripts/controllers/chain/near/chain.ts
  client/scripts/controllers/chain/solana/chain.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/helpers/index.ts
  client/scripts/views/components/chain_status_indicator.ts
Labels: A0-please QA, A0-please review, cleanup, 1, 2

#1614 Snapshot Linking for Non Admins Fix
  client/scripts/views/pages/view_proposal/index.ts
Labels: bug, 1

#1616 Use proxied endpoint in Keplr config.
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  shared/adapters/chain/cosmos/keys.ts
Labels: bug, A0-please QA, A0-please review, 1

#1618 Comment threshold text says how much token you have.
  client/scripts/views/pages/view_proposal/create_comment.ts
Labels: enhancement, A0-please QA, A0-please review, 1

#1617 Support title for compound proposal creation.
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
Labels: enhancement, A0-please QA, A0-please review, 1

#1601 Explore Page Redesign
  client/scripts/views/components/component_kit/cards.ts
  client/scripts/views/components/component_kit/component_listing.ts
  client/scripts/views/pages/landing/community_cards.ts
  client/styles/components/component_kit/cards.scss
  client/styles/components/component_kit/component_listing.scss
  client/styles/facelift.scss
  client/styles/pages/landing/community_cards.scss
  client/styles/sublayout.scss
Labels: enhancement, 8

#1615 Support scope/proposal/X and scope/discussion/X paths.
  client/scripts/app.ts
  client/scripts/controllers/chain/near/sputnik/dao.ts
  client/scripts/identifiers.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/proposal_card.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/discussions/summary_listing.ts
  client/scripts/views/pages/new_proposal/index.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/notifications.ts
  client/scripts/views/pages/profile/profile_comment_group.ts
  client/scripts/views/pages/profile/profile_proposal.ts
  client/scripts/views/pages/proposals.ts
  client/scripts/views/pages/referenda.ts
  client/scripts/views/pages/treasury.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/scripts/views/pages/view_proposal/sidebar.ts
  server/scripts/setupAppRoutes.ts
  shared/utils.ts
Labels: enhancement, A2-in progress, 3

#1619 Summary Page Bug Fix + Redesign
  client/scripts/controllers/app/recent_activity.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/models/OffchainThread.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/discussions/index.ts
  client/scripts/views/pages/discussions/summary_listing.ts
  client/styles/pages/discussions/summary_listing.scss
  server/migrations/20220104220331-add_last_commented_col_to_threads.js
  server/models/offchain_thread.ts
  server/routes/activeThreads.ts
  server/routes/bulkThreads.ts
  server/routes/createComment.ts
Labels: bug, enhancement, A0-please QA, A0-please review

#1620 Snapshot Initialization Fix
  client/scripts/views/pages/view_proposal/sidebar.ts
Labels: bug

#1622 Explore Page Fix for very large monitors.
  client/styles/pages/landing/community_cards.scss
Labels: bug

#1623 Rename /new/thread to /new/discussion.
  client/scripts/app.ts
  client/scripts/views/components/new_proposal_button.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/pages/new_proposal/index.ts
Labels: A0-please QA, A0-please review, cleanup, 1

#1626 Fix offchain thread loading sans chain.
  client/scripts/views/pages/view_proposal/index.ts
Labels: bug, A0-please review, 1

#1629 Update summary page to follow redesign updates
  client/scripts/views/pages/discussions/summary_listing.ts
  client/scripts/views/pages/landing/community_cards.ts
  client/styles/mixins/responsive.scss
  client/styles/pages/discussions/summary_listing.scss
Labels: A0-please QA, A0-please review

#1631 Increase walletconnect version.
  package.json
  yarn.lock
Labels: bug, A0-please QA, A0-please review, 3

#1636 Scope getThreads to chain, and ensure errors are thrown when fetch fails
  server/routes/getThreads.ts
Labels: A0-please QA, A0-please review

#1634 Fix missing avatars bug
  client/scripts/controllers/server/profiles.ts
  client/scripts/models/Profile.ts
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/components/widgets/user_gallery.ts
  client/scripts/views/pages/discussions/discussion_row.ts
  client/scripts/views/pages/profile/profile_bio.ts
  client/scripts/views/pages/view_proposal/body.ts
Labels: bug, A0-please QA, A0-please review

#1632 Sidebar Revamp
  client/scripts/views/components/component_kit/buttons.ts
  client/scripts/views/components/sidebar/discussion_section.ts
  client/scripts/views/components/sidebar/governance_section.ts
  client/scripts/views/components/sidebar/index.ts
  client/scripts/views/components/sidebar/sidebar_section.ts
  client/scripts/views/components/subscription_button.ts
  client/scripts/views/mobile/mobile_sidebar.ts
  client/scripts/views/pages/landing/landing_page_footer.ts
  client/scripts/views/sublayout.ts
  client/styles/components/sidebar/index.scss
  client/styles/pages/landing/landing_page_footer.scss
  client/styles/shared.scss
  client/styles/sublayout.scss
  package.json
Labels: enhancement, A7-looks good, 8

#1568 Discord Login
  README.md
  client/scripts/app.ts
  client/scripts/views/components/login.ts
  client/scripts/views/pages/settings/email_well.ts
  client/styles/pages/settings/discord_well.scss
  package.json
  server/config.ts
  server/passport.ts
  server/router.ts
  server/routes/deleteSocialAccount.ts
  server/routes/startOAuthLogin.ts
  yarn.lock
Labels: enhancement, A7-looks good

#1640 Support ETH typed message + deprecate seeds and mnemonics.
  client/scripts/app.ts
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  client/scripts/controllers/app/webWallets/near_web_wallet.ts
  client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  client/scripts/controllers/chain/cosmos/account.ts
  client/scripts/controllers/chain/ethereum/account.ts
  client/scripts/controllers/chain/ethereum/accounts.ts
  client/scripts/controllers/chain/near/account.ts
  client/scripts/controllers/chain/solana/account.ts
  client/scripts/controllers/chain/substrate/account.ts
  client/scripts/controllers/chain/substrate/shared.ts
  client/scripts/models/Account.ts
  client/scripts/models/NodeInfo.ts
  client/scripts/views/components/hedgehog_login_form.ts
  client/scripts/views/modals/message_signing_modal.ts
  client/scripts/views/modals/tx_signing_modal.ts
  client/scripts/views/pages/admin.ts
  client/scripts/views/pages/create_community/chain_input_rows.ts
  client/scripts/views/pages/create_community/cosmos_form.ts
  client/scripts/views/pages/create_community/erc20_form.ts
  client/scripts/views/pages/create_community/eth_dao_form.ts
  client/scripts/views/pages/finish_near_login.ts
  client/styles/components/hedgehog_login_form.scss
  client/styles/modals/message_signing_modal.scss
  package.json
  server/migrations/20220114200851-add-alt-chain-url.js
  server/models/address.ts
  server/models/chain_node.ts
  server/routes/addChainNode.ts
  server/routes/createChain.ts
  server/routes/getSupportedEthChains.ts
  server/routes/getTokenForum.ts
  server/util/supportedEthChains.ts
  server/util/tokenBalanceCache.ts
  shared/adapters/chain/ethereum/keys.ts
  test/unit/api/index.spec.ts
  test/unit/api/invites.spec.ts.old
  test/util/modelUtils.ts
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review, A7-looks good, cleanup, 5, 8

#1652 Fix sidebar topic loading.
  client/scripts/views/components/sidebar/discussion_section.ts
Labels: bug, A0-please QA, A0-please review, 1

#1650 CreateCommunity properly sets eth_chain_id on new communities.
  client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  client/scripts/views/components/metadata_rows.ts
  client/scripts/views/pages/create_community/erc20_form.ts
  server/models/address.ts
  server/routes/createChain.ts
  server/routes/getTokenForum.ts
Labels: bug, A0-please QA, A0-please review, 1

#1653 Use snapshot graphql scores rather than manual sum.
  client/scripts/helpers/snapshot_utils.ts
  client/scripts/views/pages/snapshot_proposals/index.ts
  client/scripts/views/pages/snapshot_proposals/proposal_row.ts
  client/scripts/views/pages/view_snapshot_proposal/index.ts
Labels: bug, A0-please QA, A0-please review, 1, 2

#1654 Permit double proposal complete with warning.
  client/scripts/models/Proposal.ts
Labels: bug, A0-please QA, A0-please review, 1

#1655 Custom Domain Sidebar Overflow Fix
  README.md
  client/scripts/views/components/sidebar/index.ts
  client/styles/components/sidebar/index.scss
Labels: bug, 1

#1657 Use 0 keplr fee to fix regen signing.
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  package.json
  shared/adapters/chain/cosmos/keys.ts
  yarn.lock
Labels: A0-please QA, A0-please review, cleanup, 1

#1645 Design system v2 text input implemented in JSX
  client/scripts/views/components/component_kit/component_listing.ts
  client/scripts/views/components/component_kit/cw_text_input.tsx
  client/scripts/views/components/component_kit/forms.ts
  client/scripts/views/components/component_kit/types.ts
  client/scripts/views/modals/new_topic_modal.ts
  client/styles/components/component_kit/cw_text_input.scss
  client/styles/components/component_kit/forms.scss
Labels: A7-looks good

#1646 Design system v2 card implemented in JSX
  client/scripts/views/components/component_kit/cards.ts
  client/scripts/views/components/component_kit/component_listing.ts
  client/scripts/views/components/component_kit/cw_card.tsx
  client/scripts/views/components/component_kit/types.ts
  client/scripts/views/pages/landing/community_cards.ts
  client/styles/components/component_kit/cards.scss
  client/styles/components/component_kit/cw_card.scss
Labels: A7-looks good

#1612 Notifications Refactor
  client/scripts/controllers/server/notifications.ts
  client/scripts/models/ChainEvent.ts
  client/scripts/models/Notification.ts
  client/scripts/views/components/notification_row.ts
  package.json
  server-test.ts
  server/database.ts
  server/eventHandlers/notifications.ts
  server/migrations/20211225065548-refactor_notifications.js
  server/migrations/20220102124147-add-notif-categories.js
  server/models/chain.ts
  server/models/notification.ts
  server/models/notification_category.ts
  server/models/notifications_read.ts
  server/models/subscription.ts
  server/routes/clearNotifications.ts
  server/routes/clearReadNotifications.ts
  server/routes/markNotificationsRead.ts
  server/routes/viewNotifications.ts
  server/webhookNotifier.ts
  shared/types.ts
  test/unit/api/drafts.spec.ts
  test/unit/api/subscriptions.spec.ts
  test/unit/api/threads.spec.ts
  test/unit/events/notificationHandler.spec.ts
Labels: enhancement, A7-looks good

#1659 Fixes for PhantomDAO.
  client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  client/scripts/controllers/chain/ethereum/aave/chain.ts
  client/scripts/controllers/chain/ethereum/chain.ts
  client/scripts/controllers/chain/ethereum/compound/chain.ts
  client/scripts/controllers/chain/ethereum/compound/governance.ts
  client/scripts/controllers/chain/ethereum/compound/proposal.ts
Labels: A0-please QA, A0-please review, cleanup, 5, 3

#1660 Reintroduce delegate check.
  client/scripts/controllers/chain/ethereum/compound/proposal.ts
Labels: bug, A0-please QA, A0-please review, 1

#1661 Fix cancel support for OZ.
  client/scripts/controllers/chain/ethereum/compound/proposal.ts
Labels: A0-please QA, A0-please review, cleanup, 1, 2

#1663 Fix comp voting check to use proposal start block.
  client/scripts/controllers/chain/ethereum/compound/chain.ts
  client/scripts/controllers/chain/ethereum/compound/proposal.ts
Labels: bug, A0-please review, 1

#1664 Add start block to isDelegate check.
  client/scripts/controllers/chain/ethereum/compound/proposal.ts
Labels: bug, A0-please review, 1

#1665 Remove OAuth state check.
  server/passport.ts
  server/routes/startOAuthLogin.ts
Labels: bug, A0-please QA, A0-please review, 2

#1670 Manually compute snapshot scores if non-final.
  client/scripts/helpers/snapshot_utils.ts
Labels: bug, A0-please QA, A0-please review, 1
