Repository hicommonwealth/commonwealth, pull requests merged in 2022-04, with the labels that each got.

#1770 Add private url field to chain node.
  server/migrations/20220403192148-add-private-url.js
  server/models/chain_node.ts
  server/routes/createChain.ts
  server/routes/getSupportedEthChains.ts
  server/routes/getTokenForum.ts
  server/scripts/dbNode.ts
  server/util/supportedEthChains.ts
  server/util/tokenBalanceCache.ts
Labels: enhancement, A0-please QA, A0-please review, 1, high priority

#1777 Fix private url handling in token forum.
  server/routes/getTokenForum.ts
Labels: bug, A0-please QA, A0-please review, 1

#1766 Explore Page Filters
  client/scripts/app.ts
  client/scripts/state.ts
  client/scripts/views/components/dashboard_explore_preview.ts
  client/scripts/views/pages/community_cards.tsx
  client/scripts/views/pages/manage_community/chain_metadata_management_table.ts
  client/scripts/views/pages/manage_community/index.ts
  client/styles/pages/landing/community_cards.scss
  client/styles/pages/manage_community.scss
  client/styles/pages/user_dashboard.scss
  server/database.ts
  server/migrations/20220209053616-add-chain-attributes.js
  server/models/chain_category.ts
  server/models/chain_category_type.ts
  server/router.ts
  server/routes/status.ts
  server/routes/updateChainCategory.ts
  shared/types.ts
Labels: 8

#1719 Integrate Axie Infinity.
  client/scripts/app.ts
  client/scripts/controllers/app/webWallets/phantom_web_wallet.ts
  client/scripts/controllers/app/webWallets/ronin_web_wallet.ts
  client/scripts/controllers/app/web_wallets.ts
  client/scripts/controllers/chain/ethereum/chain.ts
  client/scripts/controllers/chain/ethereum/tokenAdapter.ts
  client/scripts/controllers/chain/solana/tokenAdapter.ts
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/pages/finish_axie_login.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  server/config.ts
  server/database.ts
  server/migrations/20220222200353-add-ronin.js
  server/migrations/20220223160031-add-sso-token-table.js
  server/models/address.ts
  server/models/sso_token.ts
  server/models/user.ts
  server/passport/index.ts
  server/passport/magic.ts
  server/passport/socialAccount.ts
  server/router.ts
  server/routes/finishSsoLogin.ts
  server/routes/startEmailLogin.ts
  server/routes/startSsoLogin.ts
  server/routes/tokenBalance.ts
  server/routes/updateAddress.ts
  server/routes/verifyAddress.ts
  server/scripts/setupErrorHandlers.ts
  server/util/tokenBalanceCache.ts
  shared/types.ts
  static/img/wallets/ronin.png
Labels: enhancement, A0-please QA, A0-please review, A2-in progress, 13, high priority, major project

#1782 Migrate axie balance check to use rpc endpoint.
  client/scripts/views/pages/finish_axie_login.ts
  server/config.ts
  server/util/tokenBalanceCache.ts
Labels: enhancement, A0-please QA, A0-please review, 1

#1781 Profile Page Infinite Scroll Bug
  client/scripts/views/components/widgets/tabs.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/profile/profile_content.ts
Labels: 2

#1787 Use coalesce to handle null last_commented_on.
  server/routes/bulkThreads.ts
Labels: bug, A0-please QA, A0-please review, 1, high priority

#1786 Convert proposals subcomponents
  client/scripts/views/components/proposals/aave_detail.ts
  client/scripts/views/components/proposals/aave_proposal_card_detail.ts
  client/scripts/views/components/proposals/aave_proposal_card_detail.tsx
  client/scripts/views/components/proposals/balance_info.ts
  client/scripts/views/components/proposals/balance_info.tsx
  client/scripts/views/components/proposals/convictions_chooser.ts
  client/scripts/views/components/proposals/convictions_chooser.tsx
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/pages/proposals.ts
  client/styles/components/proposals/aave_detail.scss
  client/styles/components/proposals/convictions_chooser.scss
Labels: A0-please review

#1792 Stop Searching Deleted Content
  server/routes/searchComments.ts
  server/routes/searchDiscussions.ts
Labels: bug

#1788 Clean up manage community page
  client/scripts/views/pages/manage_community/admin_panel_tabs.ts
  client/scripts/views/pages/manage_community/admin_panel_tabs.tsx
  client/scripts/views/pages/manage_community/chain_metadata_management_table.ts
  client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
  client/scripts/views/pages/manage_community/helpers.ts
  client/scripts/views/pages/manage_community/index.ts
  client/scripts/views/pages/manage_community/index.tsx
  client/scripts/views/pages/manage_community/manage_roles.tsx
  client/scripts/views/pages/manage_community/manage_roles_row.ts
  client/scripts/views/pages/manage_community/upgrade_roles_form.tsx
  client/scripts/views/pages/manage_community/webhooks_form.tsx
  client/styles/components/component_kit/cw_button.scss
  client/styles/components/component_kit/cw_text_input.scss
  client/styles/construct.scss
  client/styles/pages/create_community.scss
  client/styles/pages/manage_community.scss
  client/styles/pages/manage_community/admin_panel_tabs.scss
  client/styles/pages/manage_community/chain_metadata_rows.scss
  client/styles/pages/manage_community/index.scss
  client/styles/pages/manage_community/manage_roles.scss
  client/styles/pages/manage_community/upgrade_roles_form.scss
  client/styles/pages/manage_community/webhooks_form.scss
Labels: A0-please review

#1793 Fix 2 discussions page bugs
  client/scripts/views/pages/discussions/index.tsx
Labels: A7-looks good

#1779 Convert login selector to JSX
  client/scripts/views/components/header/login_selector.ts
  client/scripts/views/components/header/login_selector.tsx
  client/scripts/views/mobile/mobile_sidebar.tsx
  client/scripts/views/sublayout_header_right.tsx
  client/styles/components/header/login_selector.scss
Labels: A0-please review

#1794 Replace as many Construct UI icons as possible
  client/scripts/views/components/avatar_upload.ts
  client/scripts/views/components/chain_icon.tsx
  client/scripts/views/components/community_label.tsx
  client/scripts/views/components/community_options_popover.tsx
  client/scripts/views/components/dashboard_explore_preview.ts
  client/scripts/views/components/empty_topic_placeholder.ts
  client/scripts/views/components/header/login_selector.tsx
  client/scripts/views/components/header/notifications_menu.tsx
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/notification_row.ts
  client/scripts/views/components/proposal_card.ts
  client/scripts/views/components/sidebar/sidebar_quick_switcher.tsx
  client/scripts/views/components/sidebar/sidebar_section.tsx
  client/scripts/views/components/social_sharing_carat.tsx
  client/scripts/views/components/widgets/user.ts
  client/scripts/views/mobile/mobile_header.tsx
  client/scripts/views/mobile/mobile_icons.ts
  client/scripts/views/modals/select_address_modal.ts
  client/scripts/views/pages/discussions/topics_menu.tsx
  client/scripts/views/pages/manage_community/webhooks_form.tsx
  client/scripts/views/pages/user_dashboard.tsx
  client/styles/components/avatar_upload.scss
  client/styles/components/empty_topic_placeholder.scss
  client/styles/components/login_with_wallet_dropdown.scss
  client/styles/components/new_thread_form.scss
  client/styles/components/proposal_card.scss
  client/styles/components/quill_editor.scss
  client/styles/components/widgets/user.scss
  client/styles/construct.scss
  client/styles/mobile/mobile_sidebar.scss
  client/styles/modals/select_address_modal.scss
  client/styles/pages/discussions/topics_menu.scss
  client/styles/pages/user_dashboard.scss
  client/styles/pages/view_proposal/index.scss
  client/styles/shared.scss
  client/styles/sublayout_header_left.scss
Labels: A0-please review

#1805 Fix ERC20 event listener urls.
  server/scripts/dbNode.ts
Labels: bug, A0-please QA, A0-please review, 1, high priority

#1799 Replace discussion icons
  client/scripts/views/pages/discussions/discussion_row.tsx
  client/scripts/views/pages/discussions/discussion_row_menu.tsx
Labels: A0-please review

#1800 Replace some proposal icons and add flex: 1 in some empty pages
  client/scripts/views/components/sidebar/community_selector.tsx
  client/scripts/views/pages/create_community/create_community.tsx
  client/scripts/views/pages/create_community/index.tsx
  client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/scripts/views/pages/view_snapshot_proposal/index.ts
  client/styles/pages/create_community.scss
  client/styles/pages/referenda.scss
  client/styles/pages/snapshot/view_proposal.scss
  client/styles/pages/tips.scss
  client/styles/pages/treasury.scss
  client/styles/pages/validators.scss
  client/styles/pages/view_proposal/index.scss
Labels: A0-please review

#1801 Fix stage editor checkmark positioning
  client/styles/components/chain_entities_selector.scss
  client/styles/components/snapshot_proposal_selector.scss
Labels: A0-please review

#1807 Fix last visit
  client/scripts/views/pages/discussions/helpers.ts
  client/scripts/views/pages/discussions/index.tsx
Labels: A0-please review

#1806 Convert discussion subcomponents to JSX
  client/scripts/views/components/empty_topic_placeholder.ts
  client/scripts/views/components/empty_topic_placeholder.tsx
  client/scripts/views/components/loading_row.ts
  client/scripts/views/components/loading_row.tsx
  client/scripts/views/pages/discussions/index.tsx
  client/scripts/views/pages/discussions/listing_scroll.tsx
  client/scripts/views/pages/discussions/pinned_listing.tsx
  client/scripts/views/pages/discussions/recent_listing.tsx
  client/scripts/views/pages/discussions/summary_listing.tsx
  client/scripts/views/pages/listing.ts
  client/scripts/views/pages/listing.tsx
  client/styles/components/empty_topic_placeholder.scss
  client/styles/components/loading_row.scss
Labels: A0-please review

#1809 Minor UI/copy cleanup.
  client/scripts/views/components/header/login_selector.tsx
  client/scripts/views/components/sidebar/index.tsx
  client/scripts/views/components/topic_selector.tsx
Labels: A0-please QA, A0-please review, cleanup, 1

#1808 Convert webhooks settings modal to JSX and clean up CSS
  client/scripts/views/modals/webhook_settings_modal.ts
  client/scripts/views/modals/webhook_settings_modal.tsx
  client/scripts/views/pages/manage_community/upgrade_roles_form.tsx
  client/scripts/views/pages/manage_community/webhooks_form.tsx
  client/styles/modals/webhook_settings_modal.scss
  client/styles/pages/manage_community/webhooks_form.scss
Labels: A0-please review

#1812 Fix webhooks modal padding and section display
  client/scripts/views/modals/webhook_settings_modal.tsx
  client/styles/modals/webhook_settings_modal.scss
Labels: A0-please review

#1816 Fix comment button by removing isAdapterReady check.
  client/scripts/views/pages/view_proposal/create_comment.ts
Labels: bug, A0-please QA, A0-please review, 1, high priority

#1817 Add case for unknown chain on /getTokenForum.
  server/util/supportedEthChains.ts
Labels: bug, A0-please QA, A0-please review, 1

#1820 Re-add question mark to snapshot
  client/scripts/views/pages/view_proposal/linked_proposals_card.tsx
Labels: A0-please review

#1804 Add better validation for createAddress.
  server/routes/createAddress.ts
Labels: bug, A0-please QA, A0-please review, 1

#1791 Add wallet field to address to improve signing flow.
  client/scripts/controllers/app/login.ts
  client/scripts/controllers/app/webWallets/injective_web_wallet.ts
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  client/scripts/controllers/app/webWallets/near_web_wallet.ts
  client/scripts/controllers/app/webWallets/phantom_web_wallet.ts
  client/scripts/controllers/app/webWallets/polkadot_web_wallet.ts
  client/scripts/controllers/app/webWallets/ronin_web_wallet.ts
  client/scripts/controllers/app/webWallets/terra_station_web_wallet.ts
  client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  client/scripts/controllers/app/web_wallets.ts
  client/scripts/controllers/chain/cosmos/chain.ts
  client/scripts/controllers/chain/ethereum/aave/chain.ts
  client/scripts/controllers/chain/ethereum/aave/governance.ts
  client/scripts/controllers/chain/ethereum/aave/proposal.ts
  client/scripts/controllers/chain/ethereum/compound/chain.ts
  client/scripts/controllers/chain/ethereum/compound/governance.ts
  client/scripts/controllers/chain/ethereum/compound/proposal.ts
  client/scripts/controllers/chain/ethereum/contractApi.ts
  client/scripts/controllers/chain/ethereum/moloch/governance.ts
  client/scripts/controllers/chain/ethereum/moloch/member.ts
  client/scripts/controllers/chain/ethereum/moloch/proposal.ts
  client/scripts/models/Account.ts
  client/scripts/models/AddressInfo.ts
  client/scripts/models/IWebWallet.ts
  client/scripts/views/components/header/login_selector.tsx
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/modals/select_address_modal.ts
  client/scripts/views/pages/finish_near_login.ts
  client/scripts/views/pages/manage_community/manage_roles.tsx
  client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  client/scripts/views/pages/settings/email_well.ts
  client/scripts/views/pages/settings/linked_addresses_well.ts
  server/migrations/20220408182445-add-address-wallet-field.js
  server/models/address.ts
  server/passport/magic.ts
  server/router.ts
  server/routes/createAddress.ts
  server/routes/deleteAddress.ts
  server/routes/finishSsoLogin.ts
  server/routes/linkExistingAddressToChain.ts
  server/routes/setAddressWallet.ts
  server/routes/startEmailLogin.ts
  server/routes/updateEmail.ts
  server/routes/verifyAddress.ts
  shared/types.ts
  test/integration/chain-events-nodes.spec.ts
  test/unit/api/index.spec.ts
  test/util/modelUtils.ts
Labels: enhancement, A0-please QA, A0-please review, cleanup, 8

#1822 Add Text component
  client/scripts/views/components/component_kit/cw_button.tsx
  client/scripts/views/components/component_kit/cw_component_showcase.tsx
  client/scripts/views/components/component_kit/cw_engagement_button.tsx
  client/scripts/views/components/component_kit/cw_gradient_button.tsx
  client/scripts/views/components/component_kit/cw_icons/cw_icons.tsx
  client/scripts/views/components/component_kit/cw_text.tsx
  client/scripts/views/components/component_kit/cw_text_input.tsx
  client/scripts/views/components/component_kit/helpers.ts
  client/scripts/views/components/component_kit/types.ts
  client/styles/components/component_kit/cw_component_showcase.scss
  client/styles/components/component_kit/cw_text.scss
  client/styles/shared.scss
Labels: A0-please review

#1813 Clean up thread reaction button and reply button
  client/scripts/controllers/server/reactionCounts.ts
  client/scripts/controllers/server/threads.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/stores/ReactionCountsStore.ts
  client/scripts/views/components/inline_reply_button.tsx
  client/scripts/views/components/reaction_button.tsx
  client/scripts/views/components/reaction_button/comment_reaction_button.tsx
  client/scripts/views/components/reaction_button/discussion_row_reaction_button.tsx
  client/scripts/views/components/reaction_button/helpers.tsx
  client/scripts/views/components/reaction_button/thread_reaction_button.tsx
  client/scripts/views/components/thread_reaction_button.ts
  client/scripts/views/pages/discussions/discussion_row.tsx
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/components/inline_reply_button.scss
  client/styles/components/reaction_button/comment_reaction_button.scss
  client/styles/components/reaction_button/discussion_row_reaction_button.scss
  client/styles/components/thread_reaction_button.scss
  client/styles/pages/view_proposal/index.scss
  server/routes/bulkOffchain.ts
  server/routes/createReaction.ts
  server/routes/reactionsCounts.ts
Labels: A0-please review

#1825 Remove Axie login options.
  client/scripts/views/components/login.ts
Labels: enhancement, A0-please QA, A0-please review, 1, high priority

#1827 Add single-click login flow for Axie.
  client/scripts/views/components/login.ts
Labels: enhancement, A0-please QA, A0-please review, 1, high priority

#1832 Replace old alchemy url with new one.
  client/scripts/views/pages/create_community/starter_community_form.tsx
Labels: bug, A0-please review, 1
