Repository hicommonwealth/commonwealth, pull requests merged in 2022-09, with the labels that each got.

#2096 Add JWE util for CMNBot integration.
  packages/commonwealth/package.json
  packages/commonwealth/server/util/jwe.ts
  yarn.lock
Labels: 1

#2101 Fix env var for specific dynos
  packages/commonwealth/Procfile
Labels: bug, high priority

#2102 Fix notifications menu css for new users
  packages/commonwealth/client/styles/components/header/notifications_menu.scss
Labels: bug, 1

#2104 Auto enable ce listener for aave and compound
  packages/commonwealth/server/routes/createChain.ts
Labels: enhancement

#2073 Bulk Balances Route for Commonbot
  packages/commonwealth/server/router.ts
  packages/commonwealth/server/routes/bulkBalances.ts
Labels: 5

#2121 Fix login button breaking on medium viewports
  packages/commonwealth/client/styles/pages/landing/landing_page_header.scss
Labels: bug

#2145 Disable Chat Toggle
  packages/commonwealth/client/scripts/models/ChainInfo.ts
  packages/commonwealth/client/scripts/views/components/sidebar/index.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
  packages/commonwealth/server/migrations/20220926183821-add-chat-enabled.js
  packages/commonwealth/server/models/chain.ts
  packages/commonwealth/server/routes/updateChain.ts
Labels: 1

#2129 Modify Delete Chain for use with Airplane
  packages/commonwealth/client/scripts/views/pages/manage_community/index.tsx
  packages/commonwealth/server/router.ts
  packages/commonwealth/server/routes/deleteChain.ts
Labels: 1
