Repository hicommonwealth/commonwealth, pull requests merged in 2022-07, with the labels that each got.

#1957 Typify and clean up getProfile route.
  server/routes/getProfile.ts
Labels: A0-please QA, A0-please review, cleanup, 1

#1961 Fix cosmos account switching and balance query.
  client/scripts/controllers/app/webWallets/keplr_web_wallet.ts
  server/util/tokenBalanceCache.ts
Labels: bug, A0-please QA, A0-please review, cleanup, 1

#1966 Fix 500 error on axie login.
  server/routes/finishSsoLogin.ts
Labels: bug, A0-please QA, A0-please review, 1

#1985 Show More Fix
  packages/commonwealth/client/scripts/views/pages/view_proposal/body.ts
Labels: 1

#1986 Make token-balance-cache into library.
  package.json
  packages/common-common/package.json
  packages/common-common/src/cacheJobRunner.ts
  packages/common-common/src/types.ts
  packages/commonwealth/package.json
  packages/commonwealth/server-test.ts
  packages/commonwealth/server.ts
  packages/commonwealth/server/migrations/20220720191840-augment-chain-node.js
  packages/commonwealth/server/models/chain_node.ts
  packages/commonwealth/server/router.ts
  packages/commonwealth/server/routes/createComment.ts
  packages/commonwealth/server/routes/createReaction.ts
  packages/commonwealth/server/routes/createThread.ts
  packages/commonwealth/server/routes/tokenBalance.ts
  packages/commonwealth/server/routes/updateOffchainVote.ts
  packages/commonwealth/server/util/banCheckCache.ts
  packages/commonwealth/server/util/identityFetchCache.ts
  packages/commonwealth/server/util/rules/ruleCache.ts
  packages/commonwealth/server/util/tokenBalanceCache.ts
  packages/commonwealth/server/util/validateTopicThreshold.ts
  packages/commonwealth/server/util/viewCountCache.ts
  packages/commonwealth/test/tsconfig.node.json
  packages/commonwealth/test/unit/api/tokenForum.spec.ts
  packages/commonwealth/test/util/modelUtils.ts
  packages/commonwealth/tsconfig.json
  packages/commonwealth/webpack/webpack.common.js
  packages/token-balance-cache/package.json
  packages/token-balance-cache/src/index.ts
  packages/token-balance-cache/src/provider.ts
  packages/token-balance-cache/src/types.ts
  yarn.lock
Labels: A0-please QA, A0-please review, cleanup, 1, 2

#2000 Fix Axie login post-checksum migration.
  packages/commonwealth/server/models/address.ts
  packages/commonwealth/server/routes/finishSsoLogin.ts
Labels: bug, A0-please QA, A0-please review, 1

#2001 Prevent createAddress calls on axie.
  packages/commonwealth/server/routes/createAddress.ts
Labels: bug, A0-please QA, A0-please review, 1

#2002 Add required true to addresses in getMembers
  packages/commonwealth/server/routes/bulkMembers.ts
Labels: bug
