Repository hicommonwealth/commonwealth, pull requests merged in 2022-06, with the labels that each got.

#1894 Deprecate resetServer script.
  package.json
  server/scripts/resetServer.ts
Labels: 1

#1914 Secure Chat Websockets
  client/scripts/app.ts
  client/scripts/controllers/server/socket/chatNs.ts
  client/scripts/views/components/chat/chat_window.tsx
  server/socket/chainEventsNs.ts
  server/socket/chatNs.ts
  server/socket/index.ts
  server/util/redisCache.ts
  shared/types.ts
Labels: bug

#1915 Snapshot Not Appearing Fix
  client/scripts/helpers/snapshot_utils.ts
  client/scripts/views/components/sidebar/governance_section.tsx
  client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
  client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  client/scripts/views/pages/snapshot_proposals/index.tsx
  client/styles/pages/snapshot/list_proposal.scss
Labels: 2

#1917 Specify deleteThread Address association.
  server/routes/deleteThread.ts
Labels: bug, 1, high priority

#1835 Integrate ERC721 chain events.
  client/scripts/controllers/server/chain_entities.ts
  package.json
  server/scripts/dbNode.ts
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review, A3-needs resolving, 5

#1913 Adds Token Thresholds to Native Cosmos Token Chains
  client/scripts/controllers/chain/cosmos/account.ts
  client/scripts/controllers/chain/cosmos/main.ts
  package.json
  server-test.ts
  server/migrations/20220607213602-terra-token-threshold.js
  server/routes/verifyAddress.ts
  server/util/tokenBalanceCache.ts
  test/mocha.opts
  yarn.lock
Labels: enhancement, A0-please QA, A0-please review

#1920 Chat Mentions
  client/scripts/controllers/server/socket/chatNs.ts
  client/scripts/views/components/chat/chat_window.tsx
  client/scripts/views/components/notification_row.ts
  client/scripts/views/components/quill_editor.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/styles/components/quill_editor.scss
  client/styles/pages/chat.scss
  server-test.ts
  server/migrations/20220609234625-subscribe-user-to-chat-notifs.js
  server/models/subscription.ts
  server/passport/magic.ts
  server/passport/socialAccount.ts
  server/router.ts
  server/routes/chat/getChatChannel.ts
  server/routes/finishEmailLogin.ts
  server/routes/finishOAuthLogin.ts
  server/routes/finishSsoLogin.ts
  server/routes/verifyAddress.ts
  server/routes/viewNotifications.ts
  server/socket/chatNs.ts
  shared/types.ts
Labels: enhancement, A0-please QA

#1895 Add rule system for gating user forum actions.
  .gitignore
  client/scripts/controllers/server/socket/chatNs.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/views/components/chat/admin_modals.tsx
  package.json
  server-test.ts
  server.ts
  server/database.ts
  server/migrations/20220601182733-add-rules-table-and-associations.js
  server/models/chat_channel.ts
  server/models/offchain_thread.ts
  server/models/offchain_topic.ts
  server/models/rule.ts
  server/router.ts
  server/routes/bulkOffchain.ts
  server/routes/chat/editChatCategory.ts
  server/routes/chat/editChatChannel.ts
  server/routes/chat/renameChatChannel.ts
  server/routes/createComment.ts
  server/routes/createReaction.ts
  server/routes/createThread.ts
  server/routes/editTopic.ts
  server/routes/rules/createRule.ts
  server/routes/rules/deleteRule.ts
  server/routes/rules/getRuleTypes.ts
  server/routes/updateOffchainVote.ts
  server/ruleTypes/adminOnly.ts
  server/ruleTypes/all.ts
  server/ruleTypes/allowList.ts
  server/ruleTypes/any.ts
  server/ruleTypes/index.ts
  server/util/rules/checkRule.ts
  server/util/rules/ruleCache.ts
  server/util/rules/ruleParser.ts
  server/util/rules/ruleTypes.ts
  test/unit/api/threads.spec.ts
  test/unit/rules/adminOnly.spec.ts
  test/unit/rules/all.spec.ts
  test/unit/rules/allowList.spec.ts
  test/unit/rules/any.spec.ts
Labels: enhancement, A0-please QA, A0-please review, 8

#1882 View notifications refactor
  client/scripts/app.ts
  client/scripts/controllers/server/notifications.ts
  client/scripts/controllers/server/socket/chainEventsNs.ts
  client/scripts/views/components/header/notifications_menu.tsx
  client/scripts/views/components/notification_row.ts
  client/scripts/views/pages/notifications_page.ts
  client/styles/components/header/notifications_menu.scss
  package.json
  server/migrations/20220518072401-repopulate-notification-data.js
  server/migrations/20220518074202-add-userid-column-to-notifications-read.js
  server/migrations/20220521055322-add-id-to-notifications-read.js
  server/models/notifications_read.ts
  server/models/subscription.ts
  server/router.ts
  server/routes/viewNotifications.ts
  server/scripts/benchmarks/createThread.js
  server/socket/chainEventsNs.ts
  server/socket/chatNs.ts
  server/socket/index.ts
  test/unit/api/subscriptions.spec.ts
Labels: enhancement

#1934 Set saveUnitialized session to false.
  server.ts
  server/routes/viewNotifications.ts
  test/unit/api/subscriptions.spec.ts
Labels: 1

#1936 Remove awaits when calling emitNotifications
  server/routes/addEditors.ts
  server/routes/createComment.ts
  server/routes/createReaction.ts
  server/routes/createThread.ts
  server/routes/editComment.ts
  server/routes/editThread.ts
Labels: bug

#1945 Fix oauth state
  server/passport/socialAccount.ts
  server/router.ts
  server/routes/startOAuthLogin.ts
Labels: bug
