Repository hicommonwealth/commonwealth, pull requests merged in 2022-02, with the labels that each got.

#1671 Change snapshot default length from 5d to 4d.
  client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
Labels: enhancement, A0-please QA, A0-please review, 1

#1673 Fix analytics 404 by re-exposing communityStats route.
  server/router.ts
  server/routes/communityStats.ts
Labels: bug, A0-please QA, A0-please review, 1

#1677 Fix Ion
  server/migrations/20220203231624-fix-ion.js
Labels: 1

#1679 Use snapshot.js to compute vote totals.
  client/scripts/helpers/snapshot_utils.ts
Labels: bug, A0-please QA, A0-please review, 1, 2

#1683 Fix snapshot voting power.
  client/scripts/helpers/snapshot_utils.ts
  client/scripts/views/pages/view_snapshot_proposal/index.ts
Labels: bug, A0-please review, 1

#1693 Ensure getSupportedEthChains only returns w addresses.
  server/util/supportedEthChains.ts
Labels: bug, A0-please QA, A0-please review, 1, high priority

#1694 Add cascade for NotificationsRead on Subscription delete.
  server/migrations/20220215201512-add-subscription-delete-cascade.js
Labels: bug, A0-please QA, A0-please review, 1, high priority

#1684 Defer chain init on login when possible and remove substrate CLI option.
  client/scripts/app.ts
  client/scripts/views/components/login_with_wallet_dropdown.ts
  client/scripts/views/modals/link_new_address_modal.ts
Labels: enhancement, A0-please QA, A0-please review, 1, 2

#1707 User Dashboard Refactor to remove Construct UI
  client/scripts/views/pages/user_dashboard.ts
  client/styles/pages/user_dashboard.scss
Labels: 1

#1651 Use getProposalUrlPath to construct proposal link.
  client/scripts/identifiers.ts
  client/scripts/views/components/search_bar.ts
  client/scripts/views/components/user_dashboard_row.ts
  client/scripts/views/pages/search.ts
  client/scripts/views/pages/view_proposal/header.ts
  client/scripts/views/pages/view_proposal/sidebar.ts
Labels: A0-please QA, A0-please review, A2-in progress, cleanup, 1

#1709 Add missing checks for createChain and addChainNode.
  client/scripts/views/pages/create_community/starter_community_form.tsx
  server/routes/addChainNode.ts
  server/routes/createChain.ts
Labels: bug, A0-please QA, A0-please review, 1, high priority

#1545 Scalable Socket.io Websocket servers + live chain-event notifications
  client/scripts/app.ts
  client/scripts/controllers/server/notifications.ts
  client/scripts/controllers/server/socket/chainEventsNs.ts
  client/scripts/controllers/server/socket/chat.ts
  client/scripts/controllers/server/socket/index.ts
  client/scripts/models/ChainEvent.ts
  client/scripts/models/Notification.ts
  client/scripts/models/NotificationSubscription.ts
  client/scripts/state.ts
  client/scripts/views/components/widgets/user_gallery.ts
  client/scripts/views/pages/chat.ts
  client/scripts/views/pages/notification_settings.ts
  package.json
  server-test.ts
  server.ts
  server/config.ts
  server/eventHandlers/entityArchival.ts
  server/eventHandlers/notifications.ts
  server/migrations/20210914210024-clean-up-db.js
  server/models/subscription.ts
  server/routes/subscription/deleteSubscription.ts
  server/routes/subscription/viewSubscriptions.ts
  server/routes/viewNotifications.ts
  server/scripts/chainEventsConsumer.ts
  server/scripts/dbNode.ts
  server/scripts/setupServer.ts
  server/socket/README.md
  server/socket/chainEventsNs.ts
  server/socket/index.ts
  server/tsconfig.json
  server/util/rabbitmq/rabbitMQController.ts
  shared/types.ts
  test/unit/events/entityArchivalHandler.spec.ts
  yarn.lock
Labels: testing, 13
