Repository hicommonwealth/commonwealth, pull requests merged in 2022-12, with the labels that each got.

#2317 Hotfixes for entities migration UI bugs.
  packages/commonwealth/client/scripts/controllers/chain/ethereum/aave/proposal.ts
  packages/commonwealth/client/scripts/controllers/server/chain_entities.ts
  packages/commonwealth/client/scripts/identifiers.ts
  packages/commonwealth/server.ts
  packages/commonwealth/server/config.ts
  packages/commonwealth/server/migrations/20220822175426-refactor-type-id-of-collective-proposal.js
  packages/commonwealth/server/migrations/20220822175433-ce-dup-constraint-and-cleanup.js
  packages/commonwealth/server/util/cosmosProxy.ts
  packages/commonwealth/server/util/entitiesProxy.ts
  packages/commonwealth/server/util/ipfsProxy.ts
Labels: WTD

#2319 Fix Forum Notifications
  packages/commonwealth/server/models/subscription.ts
  packages/commonwealth/server/routes/addEditors.ts
  packages/commonwealth/server/routes/createComment.ts
  packages/commonwealth/server/routes/createReaction.ts
  packages/commonwealth/server/routes/createThread.ts
  packages/commonwealth/server/routes/editComment.ts
  packages/commonwealth/server/routes/editThread.ts
  packages/commonwealth/server/types.ts
  packages/commonwealth/tsconfig.json
Labels: bug

#2240 Discussion listing UI update
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon_lookup.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icons.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_tag.tsx
  packages/commonwealth/client/scripts/views/components/empty_topic_placeholder.tsx
  packages/commonwealth/client/scripts/views/components/loading_row.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/thread_preview_reaction_button.tsx
  packages/commonwealth/client/scripts/views/menus/create_content_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/discussion_filter_bar.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/discussion_row.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/helpers.ts
  packages/commonwealth/client/scripts/views/pages/discussions/index.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_listing.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/stages_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/topics_menu.tsx
  packages/commonwealth/client/scripts/views/pages/overview/index.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_content_page.scss
  packages/commonwealth/client/styles/components/component_kit/cw_tag.scss
  packages/commonwealth/client/styles/components/empty_topic_placeholder.scss
  packages/commonwealth/client/styles/components/loading_row.scss
  packages/commonwealth/client/styles/components/reaction_button/thread_preview_reaction_button.scss
  packages/commonwealth/client/styles/mixins/media_queries.scss
  packages/commonwealth/client/styles/pages/discussions/discussion_filter_bar.scss
  packages/commonwealth/client/styles/pages/discussions/discussion_row.scss
  packages/commonwealth/client/styles/pages/discussions/discussion_row_menu.scss
  packages/commonwealth/client/styles/pages/discussions/index.scss
  packages/commonwealth/client/styles/pages/discussions/recent_listing.scss
  packages/commonwealth/client/styles/pages/discussions/recent_threads_header.scss
  packages/commonwealth/client/styles/pages/discussions/thread_preview.scss
  packages/commonwealth/client/styles/pages/overview/topic_summary_row.scss
  packages/commonwealth/client/styles/pages/snapshot/index.scss
  packages/commonwealth/client/styles/pages/snapshot_proposals.scss
  packages/commonwealth/client/styles/pages/view_thread/linked_threads_card.scss
  packages/commonwealth/client/styles/shared.scss
Labels: React

#2361 Fix mobile bug where sidebar opens by default
  packages/commonwealth/client/scripts/state.ts
Labels: bug, A0-please QA, 1

#2362 remove unused component
  packages/commonwealth/client/scripts/helpers/index.ts
  packages/commonwealth/client/scripts/views/components/login_with_wallet_dropdown.ts
  packages/commonwealth/client/scripts/views/modals/confirm_invite_modal.ts
  packages/commonwealth/client/scripts/views/modals/select_address_modal.ts
  packages/commonwealth/client/scripts/views/pages/create_community/starter_community_form.tsx
  packages/commonwealth/client/scripts/views/pages/profile/profile_bio.ts
  packages/commonwealth/client/styles/components/login_with_wallet_dropdown.scss
Labels: enhancement

#2356 Purge Commonwealth folder and misc
  packages/commonwealth/client/scripts/app.ts
  packages/commonwealth/client/scripts/views/pages/commonwealth/backers.ts
  packages/commonwealth/client/scripts/views/pages/commonwealth/collectives.ts
  packages/commonwealth/client/scripts/views/pages/commonwealth/commonwealth.scss
  packages/commonwealth/client/scripts/views/pages/commonwealth/geometric_pattern_section.ts
  packages/commonwealth/client/scripts/views/pages/commonwealth/index.ts
  packages/commonwealth/client/scripts/views/pages/commonwealth/projects.ts
  packages/commonwealth/client/scripts/views/pages/communities.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/helpers.ts
  packages/commonwealth/client/scripts/views/pages/privacy.tsx
  packages/commonwealth/client/scripts/views/pages/terms.tsx
  packages/commonwealth/client/scripts/views/pages/why_commonwealth.tsx
  packages/commonwealth/client/styles/pages/commonwealth/backers.scss
  packages/commonwealth/client/styles/pages/commonwealth/collectives.scss
  packages/commonwealth/client/styles/pages/commonwealth/projects.scss
  packages/commonwealth/client/styles/pages/communities.scss
  packages/commonwealth/client/styles/pages/privacy_and_terms.scss
  packages/commonwealth/client/styles/pages/why_commonwealth.scss
Labels: React

#2326 Remove Construct UI components from search bar and refactor
  packages/commonwealth/client/scripts/controllers/server/search.ts
  packages/commonwealth/client/scripts/models/SearchQuery.ts
  packages/commonwealth/client/scripts/models/SearchResult.ts
  packages/commonwealth/client/scripts/views/components/search_bar.tsx
  packages/commonwealth/client/scripts/views/pages/search/index.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar_components.tsx
  packages/commonwealth/client/scripts/views/sublayout_header.tsx
  packages/commonwealth/client/styles/components/quill/markdown_formatted_text.scss
  packages/commonwealth/client/styles/components/quill/quill_formatted_text.scss
  packages/commonwealth/client/styles/pages/search/index.scss
  packages/commonwealth/client/styles/pages/search/search_bar.scss
  packages/commonwealth/client/styles/pages/search/search_bar_components.scss
  packages/commonwealth/client/styles/pages/search_bar.scss
Labels: React

#2325 Convert and clean up new proposal form
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_dropdown.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_text_input.tsx
  packages/commonwealth/client/scripts/views/components/forms.ts
  packages/commonwealth/client/scripts/views/pages/new_proposal/aave_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/compound_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/cosmos_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/index.ts
  packages/commonwealth/client/scripts/views/pages/new_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/new_proposal_form.ts
  packages/commonwealth/client/scripts/views/pages/new_proposal/phragmen_candidacy_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/sputnik_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_bounty_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_collective_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_democracy_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_treasury_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_treasury_tip_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/types.ts
  packages/commonwealth/client/styles/components/component_kit/cw_dropdown.scss
  packages/commonwealth/client/styles/pages/new_proposal/aave_proposal_form.scss
  packages/commonwealth/client/styles/pages/new_proposal/compound_proposal_form.scss
  packages/commonwealth/client/styles/pages/new_proposal/index.scss
  packages/commonwealth/client/styles/pages/new_proposal_page.scss
Labels: React

#2371 Fix navigation URL after clicking stage filter
  .gitignore
  packages/commonwealth/client/scripts/views/pages/discussions/stages_menu.tsx
Labels: bug

#2372 Delete dead code
  packages/commonwealth/client/scripts/views/modals/ragequit_modal.ts
  packages/commonwealth/client/scripts/views/modals/update_delegate_modal.ts
  packages/commonwealth/client/scripts/views/modals/version_history_modal.ts
  packages/commonwealth/client/scripts/views/modals/view_voters_modal.ts
  packages/commonwealth/client/scripts/views/pages/notification_settings/helpers.tsx
  packages/commonwealth/client/styles/modals/ragequit_modal.scss
  packages/commonwealth/client/styles/modals/update_delegate_modal.scss
  packages/commonwealth/client/styles/modals/version_history_modal.scss
  packages/commonwealth/client/styles/modals/view_voters_modal.scss
  packages/commonwealth/server/routes/createMembership.ts
  packages/commonwealth/server/routes/deleteMembership.ts
Labels: React

#2369 Convert and clean up admin
  packages/commonwealth/client/scripts/views/components/forms.ts
  packages/commonwealth/client/scripts/views/pages/admin.ts
  packages/commonwealth/client/scripts/views/pages/admin.tsx
  packages/commonwealth/client/scripts/views/pages/spec_settings.tsx
  packages/commonwealth/client/styles/components/forms.scss
  packages/commonwealth/client/styles/pages/admin.scss
Labels: React

#2322 Convert and clean up new snapshot proposal form
  packages/commonwealth/client/scripts/views/components/component_kit/cw_radio_group.tsx
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/helpers.ts
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/new_proposal_form.ts
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/types.ts
  packages/commonwealth/client/styles/pages/new_proposal_page.scss
  packages/commonwealth/client/styles/pages/new_snapshot_proposal.scss
Labels: React

#2365 Convert finish login pages to class components.
  packages/commonwealth/client/scripts/views/pages/finish_axie_login.tsx
  packages/commonwealth/client/scripts/views/pages/finish_near_login.ts
  packages/commonwealth/client/scripts/views/pages/finish_near_login.tsx
Labels: React

#2375 Add thread preview in Overview and in listing page
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
  packages/commonwealth/client/styles/components/community_card.scss
  packages/commonwealth/client/styles/components/notification_row.scss
  packages/commonwealth/client/styles/mixins/text.scss
  packages/commonwealth/client/styles/pages/discussions/thread_preview.scss
  packages/commonwealth/client/styles/pages/overview/topic_summary_row.scss
  packages/commonwealth/client/styles/pages/tips.scss
  packages/commonwealth/server/routes/bulkThreads.ts
Labels: enhancement

#2345 Bugfix: fix link previews in twitter
  packages/commonwealth/server/scripts/setupAppRoutes.ts
Labels: bug, twitter

#2344 Form Components
  packages/commonwealth/client/scripts/views/components/component_kit/cw_form.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_form_section.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/types.ts
  packages/commonwealth/client/styles/components/component_kit/cw_form.scss
  packages/commonwealth/client/styles/components/component_kit/cw_form_section.scss
Labels: enhancement

#2380 Misc Construct UI out
  packages/commonwealth/client/scripts/views/components/breadcrumbs_title_tag.tsx
  packages/commonwealth/client/scripts/views/components/chat/chat_window.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_dropdown.tsx
  packages/commonwealth/client/scripts/views/components/metadata_rows.tsx
  packages/commonwealth/client/scripts/views/components/proposals/convictions_chooser.tsx
  packages/commonwealth/client/scripts/views/components/share_popover.tsx
  packages/commonwealth/client/scripts/views/modals/alert_modal.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/chain_input_rows.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/eth_dao_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/spl_token_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/starter_community_form.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/stages_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/topics_menu.tsx
  packages/commonwealth/client/scripts/views/pages/profile/profile_banner.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_bio.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_header.ts
  packages/commonwealth/client/scripts/views/pages/search/search_bar.tsx
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/index.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/dashboard_communities_preview.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_bottom.tsx
  packages/commonwealth/client/styles/components/login.scss
  packages/commonwealth/client/styles/components/proposals/convictions_chooser.scss
  packages/commonwealth/client/styles/components/sidebar/external_links_module.scss
  packages/commonwealth/client/styles/pages/chat.scss
  packages/commonwealth/client/styles/pages/create_community.scss
  packages/commonwealth/client/styles/pages/discussions/recent_threads_header.scss
  packages/commonwealth/client/styles/pages/discussions/stages_menu.scss
  packages/commonwealth/client/styles/pages/discussions/topics_menu.scss
  packages/commonwealth/client/styles/pages/profile.scss
  packages/commonwealth/client/styles/pages/snapshot_proposals.scss
  packages/commonwealth/client/styles/pages/spec_settings.scss
  packages/commonwealth/client/styles/pages/user_dashboard/dashboard_communities_preview.scss
  packages/commonwealth/client/styles/pages/web3login.scss
Labels: React

#2312 Convert and clean up confirm invite modal
  packages/commonwealth/client/scripts/app.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_custom_icons.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon_lookup.ts
  packages/commonwealth/client/scripts/views/menus/invites_menu.tsx
  packages/commonwealth/client/scripts/views/modals/confirm_invite_modal.ts
  packages/commonwealth/client/scripts/views/modals/confirm_invite_modal.tsx
  packages/commonwealth/client/scripts/views/sublayout_header.tsx
  packages/commonwealth/client/styles/components/header/invites_menu.scss
  packages/commonwealth/client/styles/modals/confirm_invite_modal.scss
Labels: React

#2370 Convert change address modal
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/scripts/views/modals/select_address_modal.ts
  packages/commonwealth/client/scripts/views/modals/select_address_modal.tsx
  packages/commonwealth/client/styles/modals/select_address_modal.scss
Labels: React

#2395 Suppress webpack warnings from external libraries
  packages/commonwealth/webpack/webpack.config.dev.js
Labels: bug, 1
