Repository hicommonwealth/commonwealth, pull requests merged in 2022-05, with the labels that each got.

#1838 Fix getClasses
  client/scripts/views/components/component_kit/helpers.ts
Labels: A0-please review

#1837 Support flag for admin only poll creation.
  client/scripts/models/ChainInfo.ts
  client/scripts/views/pages/view_proposal/index.ts
  server/migrations/20220502181130-admin-only-polling.js
  server/models/chain.ts
  server/routes/updateThreadPolling.ts
Labels: enhancement, A0-please QA, A0-please review, 1, 2, high priority

#1834 Convert and clean up edit topic threshold modal and associated components
  client/scripts/views/components/community_options_popover.tsx
  client/scripts/views/components/token_decimal_input.ts
  client/scripts/views/components/token_decimal_input.tsx
  client/scripts/views/modals/edit_topic_thresholds_modal.ts
  client/scripts/views/modals/edit_topic_thresholds_modal.tsx
  client/scripts/views/modals/new_topic_modal.ts
  client/styles/components/token_decimal_input.scss
  client/styles/modals/edit_topic_thresholds_modal.scss
Labels: A0-please review

#1840 Fix sidebar text overflow
  client/styles/components/sidebar/index.scss
  client/styles/components/sidebar/sidebar_section.scss
Labels: A0-please review

#1831 Convert proposal card and clean up associated pages
  client/scripts/views/components/cards_collection.tsx
  client/scripts/views/components/component_kit/cw_card.tsx
  client/scripts/views/components/countdown.ts
  client/scripts/views/components/countdown.tsx
  client/scripts/views/components/proposal_card.ts
  client/scripts/views/components/proposal_card/helpers.tsx
  client/scripts/views/components/proposal_card/proposal_card.tsx
  client/scripts/views/pages/bounties.ts
  client/scripts/views/pages/discussions/discussion_filter_bar.tsx
  client/scripts/views/pages/listing.tsx
  client/scripts/views/pages/proposals.tsx
  client/scripts/views/pages/referenda.ts
  client/scripts/views/pages/snapshot_proposals/index.ts
  client/scripts/views/pages/snapshot_proposals/index.tsx
  client/scripts/views/pages/snapshot_proposals/proposal_row.ts
  client/scripts/views/pages/snapshot_proposals/snapshot_proposal_card.tsx
  client/scripts/views/pages/tips.ts
  client/scripts/views/pages/treasury.ts
  client/scripts/views/pages/view_multiple_snapshot_spaces/index.ts
  client/scripts/views/pages/view_multiple_snapshot_spaces/index.tsx
  client/scripts/views/pages/view_multiple_snapshot_spaces/snapshot_space_card.tsx
  client/scripts/views/pages/view_proposal/header.ts
  client/styles/components/cards_collection.scss
  client/styles/components/component_kit/cw_card.scss
  client/styles/components/listing.scss
  client/styles/components/proposal_card.scss
  client/styles/pages/settings/linked_addresses_well.scss
  client/styles/pages/snapshot/multiple_snapshots.scss
  client/styles/pages/snapshot/multiple_snapshots_page.scss
  client/styles/pages/snapshot/snapshot_space_card.scss
  client/styles/pages/snapshot_proposals.scss
  client/styles/pages/tips.scss
  client/styles/shared.scss
Labels: A0-please review

#1841 Fix community selector text overflow
  client/scripts/views/components/community_label.tsx
  client/styles/components/chain_icon.scss
  client/styles/components/community_label.scss
  client/styles/components/sidebar/community_selector.scss
Labels: A0-please review

#1842 Rename inj to cosm metamask to support evmos.
  client/scripts/controllers/app/webWallets/cosmos_evm_metamask_web_wallet.ts
  client/scripts/controllers/app/webWallets/ronin_web_wallet.ts
  client/scripts/controllers/app/webWallets/terra_station_web_wallet.ts
  client/scripts/controllers/app/web_wallets.ts
  client/scripts/models/IWebWallet.ts
  client/scripts/views/components/header/login_selector.tsx
  client/scripts/views/components/login_with_wallet_dropdown.ts
  server/migrations/20220503174704-rename-inj-metamask.js
  server/routes/verifyAddress.ts
  shared/types.ts
  static/img/wallets/cosm-metamask.png
  static/img/wallets/inj-metamask.png
Labels: enhancement, A0-please QA, A0-please review, 1, 2, high priority

#1843 Add icon button component
  client/scripts/views/components/component_kit/cw_component_showcase.tsx
  client/scripts/views/components/component_kit/cw_icon_button.tsx
  client/scripts/views/components/component_kit/cw_icons/cw_icon.tsx
  client/scripts/views/components/component_kit/cw_icons/cw_icons.tsx
  client/scripts/views/components/component_kit/cw_icons/types.ts
  client/scripts/views/components/component_kit/types.ts
  client/styles/components/component_kit/cw_component_showcase.scss
  client/styles/components/component_kit/cw_icon.scss
  client/styles/components/component_kit/cw_icon_button.scss
Labels: A0-please review

#1833 Adds authentication to websocket analytics dashboard
  server/config.ts
  server/socket/index.ts
Labels: enhancement, high priority

#1836 Fix Notifications Queue Backlog
  server-test.ts
  server.ts
  server/scripts/setupErrorHandlers.ts
  server/scripts/setupServer.ts
  server/socket/index.ts
  server/util/rabbitmq/RabbitMQConfig.ts
Labels: bug, high priority

#1845 Fix cards width and misc
  client/scripts/views/components/proposal_card/proposal_card.tsx
  client/styles/components/cards_collection.scss
  client/styles/components/component_kit/cw_card.scss
  client/styles/components/proposal_card.scss
  client/styles/pages/bounties.scss
  client/styles/pages/tips.scss
  client/styles/pages/user_dashboard.scss
Labels: A0-please review

#1846 Change quill loading image background color
  client/styles/components/quill_formatted_text.scss
Labels: A0-please review

#1847 Fix dashboard decoding
  client/scripts/views/components/user_dashboard_row.ts
Labels: bug, high priority

#1724 Chat v1
  client/scripts/app.ts
  client/scripts/controllers/server/notifications.ts
  client/scripts/controllers/server/socket/chainEventsNs.ts
  client/scripts/controllers/server/socket/chat.ts
  client/scripts/controllers/server/socket/chatNs.ts
  client/scripts/controllers/server/socket/index.ts
  client/scripts/models/ChatMessage.ts
  client/scripts/models/IChainAdapter.ts
  client/scripts/models/index.ts
  client/scripts/state.ts
  client/scripts/views/components/chat/admin_modals.tsx
  client/scripts/views/components/chat/chat_section.tsx
  client/scripts/views/components/chat/chat_window.tsx
  client/scripts/views/components/markdown_formatted_text.ts
  client/scripts/views/components/sidebar/discussion_section.tsx
  client/scripts/views/components/sidebar/index.tsx
  client/scripts/views/components/sidebar/sidebar_section.tsx
  client/scripts/views/mobile/mobile_sidebar.tsx
  client/scripts/views/pages/chat.ts
  client/scripts/views/pages/chat.tsx
  client/scripts/views/sublayout.tsx
  client/styles/components/sidebar/community_selector.scss
  client/styles/components/sidebar/index.scss
  client/styles/components/sidebar/sidebar_section.scss
  client/styles/facelift.scss
  client/styles/mobile/mobile_header.scss
  client/styles/pages/chat.scss
  client/styles/pages/search.scss
  client/styles/pages/settings/index.scss
  server.ts
  server/database.ts
  server/eventHandlers/entityArchival.ts
  server/migrations/20211229025313-create-message-channels-tables.js
  server/migrations/20220213101951-add-default-chat-channels.js
  server/models/chain.ts
  server/models/chat_channel.ts
  server/models/chat_message.ts
  server/router.ts
  server/routes/bulkOffchain.ts
  server/routes/chat/createChatChannel.ts
  server/routes/chat/deleteChatCategory.ts
  server/routes/chat/deleteChatChannel.ts
  server/routes/chat/getChatMessages.ts
  server/routes/chat/renameChatCategory.ts
  server/routes/chat/renameChatChannel.ts
  server/routes/createChain.ts
  server/scripts/setupServer.ts
  server/socket/chainEventsNs.ts
  server/socket/chatNs.ts
  server/socket/index.ts
  shared/types.ts
  yarn.lock
Labels: enhancement, A0-please review

#1828 Use bulkCreate instead of create loop on subscription.
  server/models/subscription.ts
  server/scripts/emails.ts
Labels: bug, A0-please QA, A0-please review, cleanup, 1, high priority

#1848 Fix card heights
  client/styles/components/proposal_card.scss
Labels: A0-please review

#1853 Better spacing in AAVE detail
  client/styles/components/proposals/aave_detail.scss
Labels: A0-please review

#1854 Re-delete facelift styles
  client/styles/components/sidebar/community_selector.scss
  client/styles/facelift.scss
Labels: A0-please review

#1855 Fix chat redirect.
  client/scripts/app.ts
  client/scripts/views/pages/chat.tsx
Labels: bug, A0-please QA, A0-please review, 1, high priority

#1860 Update radio button styles
  client/scripts/views/components/component_kit/cw_component_showcase.tsx
  client/scripts/views/components/component_kit/cw_radio_button.tsx
  client/scripts/views/components/component_kit/cw_radio_group.tsx
  client/scripts/views/components/component_kit/helpers.ts
  client/styles/components/component_kit/cw_component_showcase.scss
  client/styles/components/component_kit/cw_radio_button.scss
  client/styles/mixins/border_radius.scss
  client/styles/shared.scss
Labels: A0-please review

#1858 Adapter creation fix
  server/socket/index.ts
Labels: bug

#1861 Radio buttons update
  client/scripts/views/components/component_kit/cw_radio_button.tsx
  client/scripts/views/components/component_kit/cw_text.tsx
  client/styles/components/component_kit/cw_radio_button.scss
  client/styles/components/component_kit/cw_text.scss
Labels: A0-please review

#1862 Inline reply button should not stay purple
  client/scripts/views/components/inline_reply_button.tsx
  client/styles/components/inline_reply_button.scss
Labels: A0-please review

#1851 Bump ethereumjs-wallet version.
  package.json
  test/unit/api/index.spec.ts
  test/util/modelUtils.ts
  yarn.lock
Labels: A0-please QA, A0-please review, cleanup, 1

#1864 Add type check for poll fetching
  client/scripts/views/pages/view_proposal/index.ts
Labels: bug

#1868 Re-instate cmd click new tab on discussion rows
  client/scripts/views/pages/discussions/discussion_row.tsx
Labels: bug

#1844 Mixpanel Implementation
  client/scripts/app.ts
  client/scripts/controllers/app/login.ts
  client/scripts/helpers/mixpanel_browser_util.ts
  client/scripts/views/components/header/login_selector.tsx
  client/scripts/views/components/new_thread_form.ts
  client/scripts/views/components/proposals/voting_actions.ts
  client/scripts/views/components/reaction_button/helpers.tsx
  client/scripts/views/components/sidebar/sidebar_quick_switcher.tsx
  client/scripts/views/modals/confirm_invite_modal.ts
  client/scripts/views/modals/confirm_snapshot_vote_modal.ts
  client/scripts/views/modals/create_invite_modal.ts
  client/scripts/views/modals/link_new_address_modal.ts
  client/scripts/views/pages/404.tsx
  client/scripts/views/pages/admin.ts
  client/scripts/views/pages/council.ts
  client/scripts/views/pages/create_community/chain_input_rows.tsx
  client/scripts/views/pages/create_community/cosmos_form.tsx
  client/scripts/views/pages/create_community/erc20_form.tsx
  client/scripts/views/pages/create_community/erc721_form.tsx
  client/scripts/views/pages/create_community/eth_dao_form.tsx
  client/scripts/views/pages/create_community/index.tsx
  client/scripts/views/pages/create_community/spl_token_form.tsx
  client/scripts/views/pages/create_community/sputnik_form.tsx
  client/scripts/views/pages/create_community/starter_community_form.tsx
  client/scripts/views/pages/create_community/substrate_form.tsx
  client/scripts/views/pages/discussions/index.tsx
  client/scripts/views/pages/error.tsx
  client/scripts/views/pages/finish_near_login.ts
  client/scripts/views/pages/landing/index.ts
  client/scripts/views/pages/landing/privacy.ts
  client/scripts/views/pages/landing/terms.ts
  client/scripts/views/pages/login.tsx
  client/scripts/views/pages/new_proposal/index.ts
  client/scripts/views/pages/new_proposal/new_proposal_form.ts
  client/scripts/views/pages/new_thread.ts
  client/scripts/views/pages/profile/index.ts
  client/scripts/views/pages/proposals.tsx
  client/scripts/views/pages/referenda.ts
  client/scripts/views/pages/settings/index.tsx
  client/scripts/views/pages/snapshot_proposals/index.tsx
  client/scripts/views/pages/treasury.ts
  client/scripts/views/pages/view_proposal/create_comment.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/scripts/views/pages/view_snapshot_proposal/index.ts
  package.json
  server/config.ts
  server/routes/createAddress.ts
  server/routes/createChain.ts
  server/routes/createComment.ts
  server/routes/createReaction.ts
  server/routes/createThread.ts
  server/routes/finishEmailLogin.ts
  server/routes/finishOAuthLogin.ts
  server/routes/finishSsoLogin.ts
  server/routes/verifyAddress.ts
  server/util/mixpanelUtil.ts
  shared/analytics/types.ts
  yarn.lock
Labels: 8

#1866 Improve Communities Search
  client/scripts/app.ts
  client/scripts/controllers/server/search.ts
  client/scripts/views/components/search_bar.tsx
  client/scripts/views/pages/landing/input_tokens_lists.ts
  client/scripts/views/pages/landing/tokens_community_hero.ts
  server/routes/status.ts
Labels: enhancement

#1863 Break out proposal header links
  client/scripts/views/pages/view_proposal/header.tsx
  client/scripts/views/pages/view_proposal/index.ts
  client/scripts/views/pages/view_proposal/proposal_header_links.tsx
  client/scripts/views/pages/view_snapshot_proposal/index.ts
  client/styles/pages/view_proposal/index.scss
  client/styles/pages/view_proposal/proposal_header_links.scss
Labels: A0-please review

#1865 Create GovExplainer component to replace mixin
  client/scripts/views/components/gov_explainer.tsx
  client/scripts/views/components/proposals/proposals_explainers.tsx
  client/scripts/views/pages/proposals.tsx
  client/styles/components/gov_explainer.scss
  client/styles/pages/proposals.scss
Labels: A0-please review

#1873 Community Card Style Fix
  client/styles/pages/user_dashboard.scss
Labels: 1

#1875 status + viewNotifications route response time decrease (fix/refactor)
  package.json
  server/routes/createThread.ts
  server/routes/status.ts
  server/scripts/benchmarks/createThread.ts
  server/scripts/benchmarks/status.ts
  server/scripts/benchmarks/util.js
  yarn.lock
Labels: enhancement

#1874 Mixpanel Production Ready
  client/scripts/app.ts
  client/scripts/controllers/app/toasts.ts
  client/scripts/views/components/chat/admin_modals.tsx
  client/scripts/views/components/chat/chat_window.tsx
  client/scripts/views/pages/chat.tsx
  server/util/mixpanelUtil.ts
  shared/analytics/types.ts
Labels: 2

#1867 "Show More" Collapsing Threads Functionality
  client/scripts/views/components/markdown_formatted_text.ts
  client/scripts/views/components/quill_formatted_text.ts
  client/scripts/views/pages/view_proposal/body.ts
  client/scripts/views/pages/view_proposal/index.ts
  client/styles/pages/view_proposal/index.scss
Labels: 2

#1871 User Dashboard Update
  client/scripts/app.ts
  client/scripts/views/pages/landing/index.ts
  client/scripts/views/pages/user_dashboard.tsx
  client/styles/pages/user_dashboard.scss
  server/router.ts
  server/routes/viewActivity.ts
  server/routes/viewChainActivity.ts
  server/routes/viewGlobalActivity.ts
  server/routes/viewUserActivity.ts
Labels: enhancement, 3

#1877 Fix scroll on Why Commonwealth? page
  client/scripts/views/pages/commonwealth/commonwealth.scss
  client/scripts/views/pages/commonwealth/index.ts
Labels: A0-please review

#1885 Fix up routes and resetServer script.
  server/models/chat_channel.ts
  server/models/chat_message.ts
  server/scripts/resetServer.ts
Labels: bug, A0-please QA, A0-please review, 1
