Repository hicommonwealth/commonwealth, pull requests merged in 2022-11, with the labels that each got.

#2222 Suppress tokenAdapter no contract error on Axie.
  packages/commonwealth/client/scripts/controllers/chain/ethereum/tokenAdapter.ts
Labels: 1

#2103 Session Keys PR1: Generate keys on client, validate when logging in
  packages/commonwealth/client/scripts/controllers/app/login.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/server/sessions.ts
  packages/commonwealth/client/scripts/models/Account.ts
  packages/commonwealth/client/scripts/models/BlockInfo.ts
  packages/commonwealth/client/scripts/models/IWebWallet.ts
  packages/commonwealth/client/scripts/models/index.ts
  packages/commonwealth/client/scripts/state.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_wallets_list.tsx
  packages/commonwealth/client/scripts/views/modals/login_modal.tsx
  packages/commonwealth/package.json
  packages/commonwealth/server/migrations/20220908222716-add_blockinfo_to_address_logins.js
  packages/commonwealth/server/models/address.ts
  packages/commonwealth/server/routes/createAddress.ts
  packages/commonwealth/server/routes/verifyAddress.ts
  packages/commonwealth/shared/adapters/chain/ethereum/keys.ts
  packages/commonwealth/test/integration/api/index.spec.ts
  packages/commonwealth/test/util/modelUtils.ts
  yarn.lock
Labels: enhancement, 8, 13

#2237 Add types to role routes and fix requests.
  packages/commonwealth/client/scripts/controllers/server/roles.ts
  packages/commonwealth/server/routes/createRole.ts
  packages/commonwealth/server/routes/deleteRole.ts
  packages/commonwealth/server/types.ts
  packages/commonwealth/server/util/validateChain.ts
Labels: bug, A0-please QA, A0-please review, 1

#2239 RabbitMQ Refactor + Redis/Service Consumer
  packages/common-common/.gitignore
  packages/common-common/package.json
  packages/common-common/src/ServiceConsumer.ts
  packages/common-common/src/rabbitmq/README.md
  packages/common-common/src/rabbitmq/RabbitMQConfig.ts
  packages/common-common/src/rabbitmq/index.ts
  packages/common-common/src/rabbitmq/mockRabbitMQController.ts
  packages/common-common/src/rabbitmq/rabbitMQController.ts
  packages/common-common/src/rabbitmq/scripts/publishRmqMessageScript.ts
  packages/common-common/src/rabbitmq/types/ChainEventNotification.ts
  packages/common-common/src/rabbitmq/types/ChainEvents.ts
  packages/common-common/src/rabbitmq/types/index.ts
  packages/common-common/src/rabbitmq/util.ts
  packages/common-common/src/redisCache.ts
  packages/common-common/src/types.ts
  packages/commonwealth/server/config.ts
  packages/commonwealth/server/eventHandlers/notifications.ts
  packages/commonwealth/server/eventHandlers/rabbitMQ.ts
  packages/commonwealth/server/scripts/chainEventsConsumer.ts
  packages/commonwealth/server/scripts/dbNode.ts
  packages/commonwealth/server/scripts/migrateChainEntities.ts
  packages/commonwealth/server/socket/chainEventsNs.ts
  packages/commonwealth/server/socket/chatNs.ts
  packages/commonwealth/server/socket/index.ts
  packages/commonwealth/server/util/rabbitmq/RabbitMQConfig.ts
  packages/commonwealth/server/util/rabbitmq/rabbitMQController.ts
  packages/commonwealth/shared/types.ts
  packages/commonwealth/test/integration/events/rabbitmqProducer.spec.ts
Labels: enhancement

#2075 Fix chain entities and chain-events
  .gitignore
  packages/chain-events/package.json
  packages/chain-events/src/interfaces.ts
  packages/commonwealth/client/scripts/controllers/server/chain_entities.ts
  packages/commonwealth/client/scripts/models/ProposalModule.ts
  packages/commonwealth/package.json
  packages/commonwealth/server/eventHandlers/entityArchival.ts
  packages/commonwealth/server/eventHandlers/migration.ts
  packages/commonwealth/server/eventHandlers/rabbitMQ.ts
  packages/commonwealth/server/eventHandlers/storage.ts
  packages/commonwealth/server/migrations/20220822175427-fix-entity-duplicates.js
  packages/commonwealth/server/models/chain_entity.ts
  packages/commonwealth/server/scripts/getEntitiesWithEvents.ts
  yarn.lock
Labels: bug

#2091 Remove Substrate chain-loaded entities
  packages/commonwealth/client/scripts/controllers/chain/ethereum/aave/adapter.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/aave/governance.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/commonwealth/adapter.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/commonwealth/governance.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/compound/adapter.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/compound/governance.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/governance.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/bountyTreasury.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/collective.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/collective_proposal.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/democracy.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/democracy_proposal.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/democracy_proposals.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/shared.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/treasury.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/treasury_proposal.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/treasury_tip.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/treasury_tips.ts
  packages/commonwealth/client/scripts/controllers/server/chain_entities.ts
  packages/commonwealth/client/scripts/models/IChainAdapter.ts
  packages/commonwealth/client/scripts/stores/ChainEntityStore.ts
  packages/commonwealth/client/scripts/views/components/chain_entities_selector.tsx
  packages/commonwealth/server/scripts/migrateChainEntities.ts
Labels: enhancement
