Repository hicommonwealth/commonwealth, pull requests merged in 2023-03, with the labels that each got.

#2966 Unified Profile Opt-in Modal
  packages/commonwealth/client/scripts/controllers/server/user.ts
  packages/commonwealth/client/scripts/state.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon_lookup.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icons.tsx
  packages/commonwealth/client/scripts/views/components/unified_user_profiles_flow.tsx
  packages/commonwealth/client/scripts/views/layout.tsx
  packages/commonwealth/client/scripts/views/modals/unified_user_flow_modal.tsx
  packages/commonwealth/client/styles/modals/unified_user_flow_modal.scss
  packages/commonwealth/server/routes/status.ts
  packages/commonwealth/server/routes/updateNewProfile.ts
  packages/commonwealth/server/routing/router.ts
Labels: 2

#2979 Do not generate stats file on production build.
  packages/commonwealth/webpack/webpack.prod.config.js
Labels: 1

#2972 Fix web and mobile sidebar
  packages/commonwealth/client/scripts/hooks/useForceRerender.ts
  packages/commonwealth/client/scripts/state.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_mobile_menu.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/index.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/sidebar_quick_switcher.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/sidebar_section.tsx
  packages/commonwealth/client/scripts/views/menus/create_content_menu.tsx
  packages/commonwealth/client/scripts/views/menus/help_menu.tsx
  packages/commonwealth/client/scripts/views/menus/main_menu.tsx
  packages/commonwealth/client/scripts/views/sublayout.tsx
  packages/commonwealth/client/scripts/views/sublayout_header.tsx
Labels: React

#2970 Replace SelectList component
  packages/commonwealth/client/scripts/views/components/component_kit/cw_select_list.tsx
  packages/commonwealth/client/scripts/views/components/new_thread_form/helpers/useNewThreadForm.ts
  packages/commonwealth/client/scripts/views/components/new_thread_form/new_thread_form.tsx
  packages/commonwealth/client/scripts/views/components/thread_selector.tsx
  packages/commonwealth/client/scripts/views/components/topic_selector.tsx
  packages/commonwealth/client/scripts/views/modals/change_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/poll_editor_modal.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview_menu.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_select_list.scss
  packages/commonwealth/client/styles/components/topic_selector.scss
  packages/commonwealth/client/styles/modals/change_topic_modal.scss
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#3005 View thread page refactor
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/linked_proposals_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/linked_threads_card.tsx
Labels: React, blocker

#2995 Fix edit collaborators modal
  packages/commonwealth/client/scripts/models/Thread.ts
  packages/commonwealth/client/scripts/views/components/avatar_upload.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_text_input.tsx
  packages/commonwealth/client/scripts/views/modals/edit_collaborators_modal.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_text_input.scss
  packages/commonwealth/client/styles/modals/edit_collaborators_modal.scss
Labels: React

#3021 Replace Query list
  packages/commonwealth/client/scripts/views/components/chain_entities_selector.tsx
  packages/commonwealth/client/scripts/views/components/chain_entities_selector/chain_entities_selector.tsx
  packages/commonwealth/client/scripts/views/components/chain_entities_selector/chain_entities_selector_item.tsx
  packages/commonwealth/client/scripts/views/components/chain_entities_selector/index.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_query_list.tsx
  packages/commonwealth/client/scripts/views/components/snapshot_proposal_selector.tsx
  packages/commonwealth/client/scripts/views/components/snapshot_proposal_selector/index.ts
  packages/commonwealth/client/scripts/views/components/snapshot_proposal_selector/snapshot_proposal_selector.tsx
  packages/commonwealth/client/scripts/views/components/snapshot_proposal_selector/snapshot_proposal_selector_item.tsx
  packages/commonwealth/client/scripts/views/components/thread_selector.tsx
  packages/commonwealth/client/scripts/views/components/thread_selector/index.ts
  packages/commonwealth/client/scripts/views/components/thread_selector/thread_selector.tsx
  packages/commonwealth/client/scripts/views/components/thread_selector/thread_selector_item.tsx
  packages/commonwealth/client/scripts/views/modals/update_proposal_status_modal.tsx
  packages/commonwealth/client/styles/components/chain_entities_selector.scss
  packages/commonwealth/client/styles/components/component_kit/cw_query_list.scss
  packages/commonwealth/client/styles/components/snapshot_proposal_selector.scss
  packages/commonwealth/client/styles/components/thread_selector.scss
  yarn.lock
Labels: React, obstruct

#3019 Add passing of topic and stage to filter function
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/stages_menu.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/thread_components.tsx
Labels: React

#3003 Fix database dumps
  packages/chain-events/.gitignore
  packages/chain-events/CE_default.dump
  packages/commonwealth/package.json
Labels: enhancement

#2936 Hoist sequelize package to top level + bump version.
  package.json
  packages/chain-events/package.json
  packages/commonwealth/package.json
  yarn.lock
Labels: 1

#3027 Fix webhooks page crash and modal update
  packages/commonwealth/client/scripts/views/modals/webhook_settings_modal.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/ManageCommunityPage.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/admin_panel_tabs.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/webhooks_form.tsx
  packages/commonwealth/server/routes/webhooks/errors.ts
  packages/commonwealth/server/routes/webhooks/updateWebhook.ts
Labels: React

#2967 Fix thread preview reaction buttons
  packages/commonwealth/client/scripts/views/components/reaction_button/helpers.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/thread_preview_reaction_button.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/thread_reaction_button.tsx
  packages/commonwealth/client/styles/components/reaction_button/thread_preview_reaction_button.scss
Labels: React

#2961 Conversions 9
  packages/commonwealth/client/scripts/views/components/collapsible_body_text.tsx
  packages/commonwealth/client/scripts/views/modals/poll_editor_modal.tsx
  packages/commonwealth/client/scripts/views/pages/finish_axie_login.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar.tsx
Labels: React

#3042 Fix quill trim bug
  packages/commonwealth/client/scripts/views/components/quill/quill_formatted_text.tsx
Labels: React

#3057 New Profiles Announcement Growl
  packages/commonwealth/client/scripts/views/components/component_kit/cw_growl.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon_lookup.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icons.tsx
  packages/commonwealth/client/scripts/views/components/new_profiles_popup.tsx
  packages/commonwealth/client/scripts/views/layout.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_growl.scss
  packages/commonwealth/client/styles/components/profile_growl.scss
  packages/commonwealth/static/img/profile_growl.svg
Labels: 2

#3060 Fix intermittent /aave load
  packages/commonwealth/client/scripts/state.ts
Labels: React

#3053 Deletion of e.preventDefault() to solve some issues
  packages/commonwealth/client/scripts/views/pages/discussions/helpers.ts
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview_menu.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
Labels: React

#3077 Add UI/UX changes for toggle dark/light mode switch
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_toggle.scss
  packages/commonwealth/client/styles/index.scss
Labels: React

#3067 Linked proposals modal
  packages/commonwealth/client/scripts/views/components/chain_entities_selector/chain_entities_selector.tsx
  packages/commonwealth/client/scripts/views/components/snapshot_proposal_selector/snapshot_proposal_selector.tsx
  packages/commonwealth/client/scripts/views/modals/update_proposal_status_modal.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview_menu.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
Labels: React

#3031 Added include_addresses flag to the external GET /profiles
  packages/commonwealth/server/routes/profiles/getProfiles.ts
Labels: external_api

#3076 Fix Aave proposal title, description loading
  packages/commonwealth/client/scripts/views/components/proposal_card/index.tsx
  packages/commonwealth/server/util/ipfsProxy.ts
Labels: React

#3089 Linked threads modal
  packages/commonwealth/client/scripts/views/components/chain_entities_selector/chain_entities_selector.tsx
  packages/commonwealth/client/scripts/views/components/snapshot_proposal_selector/snapshot_proposal_selector.tsx
  packages/commonwealth/client/scripts/views/components/thread_selector/thread_selector.tsx
  packages/commonwealth/client/scripts/views/modals/linked_thread_modal.tsx
  packages/commonwealth/client/scripts/views/modals/update_proposal_status_modal.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/linked_threads_card.tsx
  packages/commonwealth/client/styles/modals/linked_thread_modal.scss
Labels: React

#3086 Fix thread state update syntax
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
Labels: React

#3097 Empty Profiles Page State Fix
  packages/commonwealth/client/scripts/views/components/profile/profile_activity_content.tsx
  packages/commonwealth/client/styles/components/profile/index.scss
Labels: bug

#3102 Some routing bugs
  packages/commonwealth/client/scripts/views/components/sidebar/sidebar_quick_switcher.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
Labels: React

#3110 Edit subscription action to save state change
  packages/commonwealth/client/scripts/views/pages/discussions/helpers.ts
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
Labels: React

#3129 Community Image Icons Upload to S3 Script
  packages/commonwealth/server/scripts/imagesUrlMigration.ts
Labels: 1

#3131 Show loader in dashboard tabs
  packages/commonwealth/client/scripts/views/components/feed.tsx
Labels: React

#3133 Dashboard bell icon - update on click
  packages/commonwealth/client/scripts/views/pages/user_dashboard/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_bottom.tsx
Labels: React

#3124 Delete dead mixins
  packages/commonwealth/client/styles/mixins/animation.scss
  packages/commonwealth/client/styles/shared.scss
Labels: React

#3118 Show edit topic modal
  packages/commonwealth/client/scripts/views/modals/edit_topic_modal.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/topics_menu.tsx
Labels: React

#3111 Fix polls - creating and voting
  packages/commonwealth/client/scripts/views/components/component_kit/cw_content_page.tsx
  packages/commonwealth/client/scripts/views/components/poll_card.tsx
  packages/commonwealth/client/scripts/views/modals/poll_editor_modal.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/helpers.ts
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/poll_cards.tsx
Labels: React

#3061 Add global react quill component
  packages/commonwealth/client/scripts/views/components/comments/create_comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/edit_comment.tsx
  packages/commonwealth/client/scripts/views/components/new_thread_form/helpers/useNewThreadForm.ts
  packages/commonwealth/client/scripts/views/components/new_thread_form/new_thread_form.tsx
  packages/commonwealth/client/scripts/views/components/quill/quill_editor_component.tsx
  packages/commonwealth/client/scripts/views/components/react_quill_editor/index.ts
  packages/commonwealth/client/scripts/views/components/react_quill_editor/react_quill_editor.tsx
  packages/commonwealth/client/scripts/views/components/react_quill_editor/utils.ts
  packages/commonwealth/client/scripts/views/modals/edit_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/new_topic_modal.tsx
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/edit_body.tsx
  packages/commonwealth/client/styles/components/comments/create_comment.scss
  packages/commonwealth/client/styles/components/new_thread_form.scss
Labels: React

#3046 Fix search bar and page
  packages/commonwealth/client/scripts/views/components/comments/comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/create_comment.tsx
  packages/commonwealth/client/scripts/views/components/poll_card.tsx
  packages/commonwealth/client/scripts/views/pages/search/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/search/index.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar_components.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/thread_components.tsx
Labels: React

#3166 Fix toggle switch
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_toggle.tsx
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_component_showcase.scss
  packages/commonwealth/client/styles/components/component_kit/cw_toggle.scss
  packages/commonwealth/client/styles/components/header/login_selector.scss
  packages/commonwealth/client/styles/index.scss
Labels: React

#3171 Magic Login Homepage Login Fix
  packages/commonwealth/server/passport/magic.ts
Labels: 2

#3165 Dashboard - Chain: navigate to chain ID on community name click
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_chain_event_row.tsx
Labels: React

#3162 Fix thread body edit + comment text edit
  packages/commonwealth/client/scripts/views/components/comments/comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/create_comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/edit_comment.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_popover/cw_popover_menu.tsx
  packages/commonwealth/client/scripts/views/components/react_quill_editor/utils.ts
  packages/commonwealth/client/scripts/views/pages/view_thread/edit_body.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
Labels: React

#3185 Fix Countdown component
  packages/commonwealth/client/scripts/views/components/countdown.tsx
Labels: React

#3146 Notifications mgmt render fixes
  packages/commonwealth/client/scripts/controllers/server/notifications.ts
  packages/commonwealth/client/scripts/identifiers.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_community_avatar.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/notification_settings/helper_components.tsx
  packages/commonwealth/client/scripts/views/pages/notification_settings/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/styles/pages/notification_settings/helper_components.scss
Labels: React

#3187 Remove Footer from all but landing page (React)
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
  packages/commonwealth/client/scripts/views/sublayout.tsx
Labels: React

#3217 Support for custom domains
  packages/commonwealth/client/scripts/DEPRECATED_router.ts
  packages/commonwealth/client/scripts/app.tsx
  packages/commonwealth/client/scripts/helpers/constants.ts
  packages/commonwealth/client/scripts/index.tsx
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/navigation/customDomainRoutes.tsx
  packages/commonwealth/client/scripts/navigation/generalRoutes.tsx
  packages/commonwealth/client/scripts/navigation/router.ts
  packages/commonwealth/client/scripts/state.ts
  packages/commonwealth/client/scripts/views/layout.tsx
  packages/commonwealth/client/scripts/views/pages/discussions_redirect.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
  packages/commonwealth/client/styles/index.scss
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#3201 React Quill Image Upload
  packages/commonwealth/client/scripts/views/components/new_thread_form/helpers/useNewThreadForm.ts
  packages/commonwealth/client/scripts/views/components/new_thread_form/new_thread_form.tsx
  packages/commonwealth/client/scripts/views/components/react_quill_editor/react_quill_editor.tsx
  packages/commonwealth/client/scripts/views/components/react_quill_editor/utils.ts
  packages/commonwealth/client/scripts/views/modals/edit_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/new_topic_modal.tsx
  packages/commonwealth/client/styles/components/comments/edit_comment.scss
  packages/commonwealth/client/styles/components/new_thread_form.scss
  packages/commonwealth/client/styles/components/react_quill/react_quill_editor.scss
  packages/commonwealth/client/styles/modals/new_topic_modal.scss
  packages/commonwealth/client/styles/pages/view_thread/edit_body.scss
Labels: React

#3227 Update `UpdateProposalStatusModal`
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/views/components/chain_entities_selector/chain_entities_selector_item.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_text.tsx
  packages/commonwealth/client/scripts/views/components/snapshot_proposal_selector/snapshot_proposal_selector.tsx
  packages/commonwealth/client/scripts/views/components/snapshot_proposal_selector/snapshot_proposal_selector_item.tsx
  packages/commonwealth/client/scripts/views/modals/update_proposal_status_modal.tsx
  packages/commonwealth/client/styles/components/chain_entities_selector.scss
  packages/commonwealth/client/styles/components/component_kit/cw_text.scss
  packages/commonwealth/client/styles/components/snapshot_proposal_selector.scss
  packages/commonwealth/client/styles/modals/update_proposal_status_modal.scss
Labels: React

#3154 Fixed and Optimized Reaction preview for pinned threads
  packages/commonwealth/client/scripts/controllers/server/reactions/ThreadReactionsController.ts
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/models/Reaction.ts
  packages/commonwealth/client/scripts/models/Thread.ts
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/navigation/customDomainRoutes.tsx
  packages/commonwealth/client/scripts/state.ts
  packages/commonwealth/client/scripts/stores/ReactionCountsStore.ts
  packages/commonwealth/client/scripts/stores/ReactionStore.ts
  packages/commonwealth/client/scripts/views/components/reaction_button/ThreadPreviewReactionButtonBig.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/ThreadPreviewReactionButtonSmall.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/UseReactionButton.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/comment_reaction_button.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/helpers.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/thread_reaction_button.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/server/routes/bulkOffchain.ts
  packages/commonwealth/server/routes/bulkThreads.ts
Labels: React

#3263 Profiles Title Undefined Bug
  packages/commonwealth/client/scripts/views/components/profile/profile_activity_row.tsx
Labels: 1

#3279 Fix jump/highlight to comment upon posting
  packages/commonwealth/client/scripts/views/components/comments/helpers.ts
Labels: bug, 1

#3285 Fix for Duplicate Webhook Notifications
  packages/commonwealth/server/routes/createComment.ts
  packages/commonwealth/server/routes/createThread.ts
  packages/commonwealth/server/routes/editComment.ts
  packages/commonwealth/server/routes/editThread.ts
Labels: 2

#3278 Fix thread page crash
  packages/commonwealth/client/scripts/views/components/quill/render_quill_delta.ts
Labels: React

#3239 Searchbar and searchpage fixes
  packages/commonwealth/client/scripts/models/SearchQuery.ts
  packages/commonwealth/client/scripts/views/components/quill/quill_formatted_text.tsx
  packages/commonwealth/client/scripts/views/pages/search/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/search/index.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar_components.tsx
Labels: React

#3199 Edit dark mode when visiting 1inch
  packages/commonwealth/client/scripts/helpers/index.ts
  packages/commonwealth/client/scripts/models/IChainAdapter.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_toggle.tsx
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/scripts/views/modals/login_modal.tsx
  packages/commonwealth/client/scripts/views/sublayout.tsx
Labels: React
