Repository hicommonwealth/commonwealth, pull requests merged in 2023-04, with the labels that each got.

#3246 React Quill Markdown
  packages/commonwealth/client/scripts/views/components/comments/comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/create_comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/edit_comment.tsx
  packages/commonwealth/client/scripts/views/components/edit_profile.tsx
  packages/commonwealth/client/scripts/views/components/react_quill_editor/markdown_formatted_text.tsx
  packages/commonwealth/client/scripts/views/components/react_quill_editor/quill_renderer.tsx
  packages/commonwealth/client/scripts/views/components/react_quill_editor/react_quill_editor.tsx
  packages/commonwealth/client/scripts/views/components/react_quill_editor/utils.ts
  packages/commonwealth/client/scripts/views/modals/edit_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/new_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/preview_modal.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/edit_body.tsx
  packages/commonwealth/client/styles/components/react_quill/react_quill_editor.scss
  packages/commonwealth/client/styles/modals/preview_modal.scss
Labels: React

#3319 Fix `/createSubscription`
  packages/commonwealth/server/routes/subscription/createSubscription.ts
Labels: bug, 1

#3296 Mark as read does not work in notifications
  packages/commonwealth/client/scripts/views/menus/notifications_menu.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/index.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/notification_row.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/notification_row_components.tsx
  packages/commonwealth/client/styles/pages/notifications/notification_row.scss
Labels: React

#3295 Refactor New Snapshot Proposal to React
  packages/commonwealth/client/scripts/mithrilInterop/index.ts
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/helpers.ts
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/index.tsx
Labels: React

#3338 WalletConnect Mobile Login Hotfix
  packages/commonwealth/client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
Labels: 2

#3332 Fix view snapshot page
  packages/commonwealth/client/scripts/helpers/snapshot_utils.ts
  packages/commonwealth/client/scripts/views/components/poll_card.tsx
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/index.tsx
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/snapshot_proposal_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card_container.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_votes_table.tsx
Labels: React

#3326 Rerender components on logging in and out
  packages/commonwealth/client/scripts/hooks/useUserLoggedIn.tsx
  packages/commonwealth/client/scripts/views/components/comments/comment.tsx
  packages/commonwealth/client/scripts/views/components/profile/profile_header.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/index.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/sidebar_quick_switcher.tsx
  packages/commonwealth/client/scripts/views/menus/create_content_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/poll_cards.tsx
  packages/commonwealth/client/scripts/views/sublayout_header.tsx
Labels: React

#3275 Fixed sidebar toggle
  packages/commonwealth/client/scripts/views/components/sidebar/admin_section.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/discussion_section.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/governance_section.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/sidebar_section.tsx
Labels: React

#3350 Handle cross community link in custom domain
  packages/commonwealth/client/scripts/views/components/profile/profile_activity_row.tsx
Labels: React

#3336 Bet1 - modals
  packages/commonwealth/client/scripts/views/components/component_kit/cw_button.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/modals/confirmation_modal.tsx
  packages/commonwealth/client/scripts/views/modals/manage_contract_template_modal.tsx
  packages/commonwealth/client/styles/modals/confirmation_modal.scss
  packages/commonwealth/client/styles/modals/manage_contract_template_modal.scss
Labels: React, bet1

#3341 Bet1 - Controllers
  packages/commonwealth/client/scripts/controllers/chain/ethereum/callContractFunction.ts
  packages/commonwealth/client/scripts/controllers/server/contracts.ts
Labels: React, bet1

#3340 Bet1 - Backend
  packages/commonwealth/package.json
  packages/commonwealth/server/database.ts
  packages/commonwealth/server/migrations/20220811142850-add-contracts-tables.js
  packages/commonwealth/server/migrations/20230404181021-create-template-cct-cctmd.js
  packages/commonwealth/server/migrations/20230404181055-add-and-connect-erc20-abi.js
  packages/commonwealth/server/models.ts
  packages/commonwealth/server/models/community_contract_metadata.ts
  packages/commonwealth/server/models/community_contract_template.ts
  packages/commonwealth/server/models/contract.ts
  packages/commonwealth/server/models/contract_abi.ts
  packages/commonwealth/server/models/template.ts
  packages/commonwealth/server/routes/bulkOffchain.ts
  packages/commonwealth/server/routes/contractAbis/createContractAbi.ts
  packages/commonwealth/server/routes/contracts/createContract.ts
  packages/commonwealth/server/routes/createChain.ts
  packages/commonwealth/server/routes/etherscanAPI.ts
  packages/commonwealth/server/routes/proposalTemplate.ts
  packages/commonwealth/server/routes/templates.ts
  packages/commonwealth/server/routing/router.ts
  packages/commonwealth/shared/validateJson.ts
  packages/commonwealth/test/unit/abi_functions/abi_form_helpers.spec.ts
  yarn.lock
Labels: 2, React, bet1

#3371 Fix Bet 1 React Merge Issues
  packages/commonwealth/client/scripts/helpers/abi_form_helpers.ts
  packages/commonwealth/client/scripts/helpers/validateTypes.ts
  packages/commonwealth/client/scripts/models/Contract.ts
  packages/commonwealth/client/scripts/stores/ContractsStore.ts
  packages/commonwealth/client/scripts/views/modals/manage_contract_template_modal.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_card.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_template_card.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract_template/create_contract_template_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract_template/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_template/view_template.tsx
  packages/commonwealth/client/styles/new_contract_template/create_contract_template_form.scss
  packages/commonwealth/client/styles/new_contract_template/new_contract_template_page.scss
  packages/commonwealth/client/styles/view_template/view_template.scss
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#3342 Cherry-picked root-id refactor onto react branch
  packages/commonwealth/client/scripts/controllers/server/comments.ts
  packages/commonwealth/client/scripts/controllers/server/threadUniqueAddressesCount.ts
  packages/commonwealth/client/scripts/models/Comment.ts
  packages/commonwealth/client/scripts/stores/ActivityStore.ts
  packages/commonwealth/client/scripts/stores/CommentsStore.ts
  packages/commonwealth/client/scripts/views/components/comments/comments_tree.tsx
  packages/commonwealth/client/scripts/views/components/comments/create_comment.tsx
  packages/commonwealth/client/scripts/views/components/profile/index.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/comment_reaction_button.tsx
  packages/commonwealth/client/scripts/views/pages/notification_settings/helper_components.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/search/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar_components.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_top.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/server/database.ts
  packages/commonwealth/server/migrations/20230330164706-root-id-refactor.js
  packages/commonwealth/server/models.ts
  packages/commonwealth/server/models/comment.ts
  packages/commonwealth/server/models/thread.ts
  packages/commonwealth/server/models/viewcount.ts
  packages/commonwealth/server/routes/addEditors.ts
  packages/commonwealth/server/routes/bulkComments.ts
  packages/commonwealth/server/routes/bulkThreads.ts
  packages/commonwealth/server/routes/createComment.ts
  packages/commonwealth/server/routes/createReaction.ts
  packages/commonwealth/server/routes/createThread.ts
  packages/commonwealth/server/routes/editComment.ts
  packages/commonwealth/server/routes/editThread.ts
  packages/commonwealth/server/routes/getNewProfile.ts
  packages/commonwealth/server/routes/searchComments.ts
  packages/commonwealth/server/routes/status.ts
  packages/commonwealth/server/routes/threadsUsersCountAndAvatars.ts
  packages/commonwealth/server/routes/viewComments.ts
  packages/commonwealth/server/routes/viewCount.ts
  packages/commonwealth/server/routes/viewUserActivity.ts
  packages/commonwealth/server/util/getThreadCommentsCount.ts
  packages/commonwealth/server/util/queryGlobalActivity.ts
  packages/commonwealth/shared/notificationFormatter.ts
  packages/commonwealth/shared/types.ts
  packages/commonwealth/shared/utils.ts
  packages/commonwealth/test/integration/api/external/dbEntityHooks.spec.ts
  packages/commonwealth/test/integration/api/subscriptions.spec.ts
  packages/commonwealth/test/integration/api/threads.spec.ts
  packages/commonwealth/test/integration/api/tokenForum.spec.ts
  packages/commonwealth/test/integration/api/webhooks.spec.ts
  packages/commonwealth/test/util/fixtures/markdownComment.ts
  packages/commonwealth/test/util/fixtures/richTextComment.ts
  packages/commonwealth/test/util/modelUtils.ts
Labels: React

#3384 Use 300px max height for <SelectList/> and overflow in all <Modal/> instances
  packages/commonwealth/client/scripts/views/components/component_kit/cw_modal.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_select_list.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/linked_proposals_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/poll_cards.tsx
  packages/commonwealth/client/styles/modals/poll_editor_modal.scss
  packages/commonwealth/client/styles/pages/view_thread/linked_proposals_card.scss
  packages/commonwealth/client/styles/pages/view_thread/poll_cards.scss
Labels: React

#3385 Fixed infinite thread loop
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
Labels: React

#3376 Add Phosphor Icons Package
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#3375 Reactify Bet1 Conversion Bug Squash
  packages/commonwealth/client/scripts/controllers/server/contracts.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_text_area.tsx
  packages/commonwealth/client/scripts/views/menus/create_content_menu.tsx
  packages/commonwealth/client/scripts/views/modals/manage_contract_template_modal.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_card.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_template_card.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract_template/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_template/view_template.tsx
  packages/commonwealth/client/styles/modals/manage_contract_template_modal.scss
  packages/commonwealth/client/styles/pages/contracts/contract_card.scss
  packages/commonwealth/server/routes/proposalTemplate.ts
Labels: 3, React

#3378 Removed unjoined communities from explore sidebar
  packages/commonwealth/client/scripts/views/components/sidebar/explore_sidebar.tsx
Labels: React

#3414 Fix create thread button
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/overview/index.tsx
  packages/commonwealth/client/scripts/views/sublayout.tsx
Labels: React

#3395 React: fix CI pt.1
  .eslintignore
  packages/chain-events/chain-testing/sdk/chainTesting.ts
  packages/commonwealth/test/e2e/landing.spec.ts
Labels: React

#3412 adjusted snapshot detail route
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/snapshot_proposal_card.tsx
Labels: React

#3423 Quill typecheck + prettify
  datadog/conf.d/postgres.yaml
  packages/commonwealth/client/scripts/views/components/comments/comment.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_content_page.tsx
  packages/commonwealth/client/scripts/views/components/new_thread_form/new_thread_form.tsx
  packages/commonwealth/client/scripts/views/components/quill/markdown_formatted_text.tsx
  packages/commonwealth/client/scripts/views/components/quill/quill_editor.ts
  packages/commonwealth/client/scripts/views/components/quill/quill_editor_component.tsx
  packages/commonwealth/client/scripts/views/components/quill/quill_editor_internal.ts
  packages/commonwealth/client/scripts/views/components/quill/types.ts
  packages/commonwealth/client/scripts/views/components/react_quill_editor/helpers.ts
  packages/commonwealth/client/scripts/views/components/react_quill_editor/react_quill_editor.tsx
  packages/commonwealth/client/scripts/views/modals/edit_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/new_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/preview_modal.tsx
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar_components.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
Labels: React

#3452 Wallet Connect Reset Fix
  packages/commonwealth/client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
Labels: 2

#3435 Remove wallet connect session during logout
  packages/commonwealth/client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
Labels: React

#3455 Reactify manage community page
  packages/commonwealth/client/scripts/views/pages/manage_community/ManageCommunityPage.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
Labels: React

#3448 Fixed issue with login display
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
Labels: React

#3456 React: fix remaining typechecking errors.
  packages/commonwealth/client/scripts/controllers/chain/ethereum/aave/proposal.ts
  packages/commonwealth/client/scripts/controllers/server/sessions.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_sidebar_menu.tsx
  packages/commonwealth/client/scripts/views/components/feed.tsx
  packages/commonwealth/client/scripts/views/modals/canvas_verify_data_modal.tsx
  packages/commonwealth/client/scripts/views/modals/login_modal.tsx
  packages/commonwealth/client/scripts/views/modals/session_signin_modal.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/helpers.ts
  packages/commonwealth/client/scripts/views/pages/new_proposal/cosmos_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/notification_row_components.tsx
Labels: React

#3431 Implement unscoped search
  packages/commonwealth/client/scripts/models/SearchQuery.ts
  packages/commonwealth/client/scripts/views/components/comments/comments_tree.tsx
  packages/commonwealth/client/scripts/views/components/user/user.tsx
  packages/commonwealth/client/scripts/views/pages/landing/community_search.tsx
  packages/commonwealth/client/scripts/views/pages/search/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/search/index.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar_components.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_top.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/server/middleware/databaseValidationService.ts
  packages/commonwealth/server/routes/bulkAddresses.ts
  packages/commonwealth/server/routes/createChain.ts
  packages/commonwealth/server/routes/searchComments.ts
  packages/commonwealth/server/routes/searchDiscussions.ts
  packages/commonwealth/server/routes/updateChain.ts
Labels: React

#3394 thread preview comment 0, snapshot detail router broken
  packages/commonwealth/server/util/getThreadCommentsCount.ts
Labels: React

#3475 Fix Reorder Topics Modal
  packages/commonwealth/client/scripts/views/modals/order_topics_modal/order_topics_modal.tsx
Labels: 1

#3436 Threads Refresh Bug Fix
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
Labels: 2, React

#3487 Fixed error when going to discussions page for empty community
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
Labels: React

#3476 Fix new proposal page infinite loading + community not loading at all for slow connections
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/navigation/customDomainRoutes.tsx
  packages/commonwealth/client/scripts/views/layout.tsx
  packages/commonwealth/client/scripts/views/menus/create_content_menu.tsx
Labels: React

#3495 Mobile Wallets Login Flow Fix
  packages/commonwealth/client/scripts/views/components/component_kit/cw_modal.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_wallets_list.tsx
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/scripts/views/pages/login/helpers.ts
  packages/commonwealth/client/scripts/views/pages/login/login_mobile.tsx
  packages/commonwealth/client/scripts/views/pages/login/types.ts
  packages/commonwealth/client/styles/pages/login/login_mobile.scss
  packages/commonwealth/package.json
  yarn.lock
Labels: bug, 2

#3451 Add search pagination + other fixes
  packages/commonwealth/client/scripts/controllers/server/search.ts
  packages/commonwealth/client/scripts/models/SearchQuery.ts
  packages/commonwealth/client/scripts/views/components/thread_selector/thread_selector.tsx
  packages/commonwealth/client/scripts/views/pages/search/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/search/index.tsx
  packages/commonwealth/server/routes/searchComments.ts
  packages/commonwealth/server/routes/searchDiscussions.ts
  packages/commonwealth/server/util/queries.ts
  packages/commonwealth/test/unit/server_util/queries.spec.ts
Labels: React

#3508 Show thread lock status without page reload
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
Labels: React

#3509 Fixed reaction popover
  packages/commonwealth/client/scripts/views/components/reaction_button/comment_reaction_button.tsx
Labels: React

#3393 Cherry-picked notifications fix onto react.
  packages/commonwealth/server/migrations/20230405143032-notifications-root-id-migration.js
  packages/commonwealth/server/routes/createComment.ts
  packages/commonwealth/server/scripts/emailDigest.ts
  packages/commonwealth/shared/utils.ts
  packages/commonwealth/test/integration/api/external/dbEntityHooks.spec.ts
  packages/commonwealth/test/integration/api/subscriptions.spec.ts
  packages/commonwealth/test/util/fixtures/markdownComment.ts
  packages/commonwealth/test/util/fixtures/richTextComment.ts
Labels: React

#3532 Bet1 Fast Follows Pt 1
  packages/commonwealth/client/scripts/views/components/component_kit/cw_divider.tsx
  packages/commonwealth/client/scripts/views/modals/manage_contract_template_modal.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_card.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_template_card.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/index.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_breadcrumbs.scss
  packages/commonwealth/client/styles/components/component_kit/cw_text_input.scss
  packages/commonwealth/client/styles/modals/manage_contract_template_modal.scss
  packages/commonwealth/client/styles/pages/contracts/contract_card.scss
  packages/commonwealth/client/styles/pages/contracts/contracts_page.scss
  packages/commonwealth/client/styles/pages/new_contract/new_contract_page.scss
Labels: 2

#3568 Fixed subscription issue
  packages/commonwealth/server/routes/subscription/createSubscription.ts
Labels: React

#3572 Evmos Wallet Names + Icons
  packages/commonwealth/client/scripts/controllers/app/webWallets/cosmos_evm_metamask_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/keplr_ethereum_web_wallet.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon_lookup.ts
Labels: 1

#3561 Snapshot Voting Fix
  packages/commonwealth/client/scripts/views/modals/confirm_snapshot_vote_modal.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card_container.tsx
Labels: 2

#3589 Set verified date when existing address is used for rejoining community
  packages/commonwealth/server/routes/linkExistingAddressToChain.ts
Labels: React

#3593 Fix thread update for chains that dont required snapshot
  packages/commonwealth/client/scripts/views/modals/update_proposal_status_modal.tsx
Labels: React

#3618 Update quill editor styles for height expansion
  packages/commonwealth/client/styles/components/new_thread_form.scss
  packages/commonwealth/client/styles/components/react_quill/react_quill_editor.scss
Labels: design review

#3620 Add defer chain on discussions redirect.
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/navigation/customDomainRoutes.tsx
Labels: high priority
