Repository hicommonwealth/commonwealth, pull requests merged in 2023-01, with the labels that each got.

#2403 Add comments count to thread previews
  packages/commonwealth/client/scripts/controllers/app/recent_activity.ts
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/models/Thread.ts
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
  packages/commonwealth/client/styles/pages/overview/topic_summary_row.scss
  packages/commonwealth/server/routes/activeThreads.ts
  packages/commonwealth/server/routes/bulkOffchain.ts
  packages/commonwealth/server/routes/bulkThreads.ts
  packages/commonwealth/server/util/getThreadCommentsCount.ts
Labels: enhancement

#2411 Head bobbing spinner
  packages/commonwealth/client/styles/components/component_kit/cw_spinner.scss
Labels: 1

#2350 Dan.chainvalidation middleware
  packages/commonwealth/server/middleware/databaseValidationService.ts
  packages/commonwealth/server/routes/activeThreads.ts
  packages/commonwealth/server/routes/addEditors.ts
  packages/commonwealth/server/routes/addMember.ts
  packages/commonwealth/server/routes/banAddress.ts
  packages/commonwealth/server/routes/bulkAddresses.ts
  packages/commonwealth/server/routes/bulkComments.ts
  packages/commonwealth/server/routes/bulkMembers.ts
  packages/commonwealth/server/routes/bulkOffchain.ts
  packages/commonwealth/server/routes/bulkThreads.ts
  packages/commonwealth/server/routes/bulkTopics.ts
  packages/commonwealth/server/routes/communityStats.ts
  packages/commonwealth/server/routes/createComment.ts
  packages/commonwealth/server/routes/createInvite.ts
  packages/commonwealth/server/routes/createPoll.ts
  packages/commonwealth/server/routes/createReaction.ts
  packages/commonwealth/server/routes/createRole.ts
  packages/commonwealth/server/routes/createThread.ts
  packages/commonwealth/server/routes/createTopic.ts
  packages/commonwealth/server/routes/deleteEditors.ts
  packages/commonwealth/server/routes/deleteRole.ts
  packages/commonwealth/server/routes/deleteTopic.ts
  packages/commonwealth/server/routes/drafts/createDraft.ts
  packages/commonwealth/server/routes/drafts/deleteDraft.ts
  packages/commonwealth/server/routes/drafts/editDraft.ts
  packages/commonwealth/server/routes/editComment.ts
  packages/commonwealth/server/routes/editSubstrateSpec.ts
  packages/commonwealth/server/routes/editThread.ts
  packages/commonwealth/server/routes/editTopic.ts
  packages/commonwealth/server/routes/getBannedAddresses.ts
  packages/commonwealth/server/routes/getPolls.ts
  packages/commonwealth/server/routes/getThreads.ts
  packages/commonwealth/server/routes/orderTopics.ts
  packages/commonwealth/server/routes/rules/createRule.ts
  packages/commonwealth/server/routes/searchComments.ts
  packages/commonwealth/server/routes/searchDiscussions.ts
  packages/commonwealth/server/routes/setDefaultRole.ts
  packages/commonwealth/server/routes/setProjectChain.ts
  packages/commonwealth/server/routes/starCommunity.ts
  packages/commonwealth/server/routes/tokenBalance.ts
  packages/commonwealth/server/routes/updateBanner.ts
  packages/commonwealth/server/routes/updateChainEntityTitle.ts
  packages/commonwealth/server/routes/updateLinkedThreads.ts
  packages/commonwealth/server/routes/updateProfile.ts
  packages/commonwealth/server/routes/updateThreadLinkedChainEntities.ts
  packages/commonwealth/server/routes/updateThreadLinkedSnapshotProposal.ts
  packages/commonwealth/server/routes/updateVote.ts
  packages/commonwealth/server/routes/upgradeMember.ts
  packages/commonwealth/server/routes/viewComments.ts
  packages/commonwealth/server/routes/viewReactions.ts
  packages/commonwealth/server/routes/viewVotes.ts
  packages/commonwealth/server/routes/webhooks/createWebhook.ts
  packages/commonwealth/server/routes/webhooks/deleteWebhook.ts
  packages/commonwealth/server/routes/webhooks/getWebhooks.ts
  packages/commonwealth/server/routes/webhooks/updateWebhook.ts
  packages/commonwealth/server/routing/router.ts
  packages/commonwealth/server/types.ts
  packages/commonwealth/test/integration/api/api.spec.ts
  packages/commonwealth/test/integration/api/validationMiddleware.spec.ts
Labels: middleware

#2449 Catch unhandled exception on decoding URI
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/server/scripts/setupAppRoutes.ts
Labels: bug

#2408 fix: overview page loading state
  packages/commonwealth/client/scripts/views/pages/overview/index.tsx
Labels: 1

#2386 Even more Construct out
  packages/commonwealth/client/scripts/views/components/component_kit/cw_sidebar_menu.tsx
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/scripts/views/pages/search/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/header.tsx
  packages/commonwealth/client/styles/components/header/login_selector.scss
  packages/commonwealth/client/styles/components/sidebar/explore_sidebar.scss
  packages/commonwealth/client/styles/pages/search/index.scss
Labels: React

#2420 Stage Change 3 Dot Menu + Pinned Post Refreshes
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/views/modals/update_proposal_status_modal.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview_menu.tsx
  packages/commonwealth/server/routing/router.ts
Labels: 1

#2450 Added support for serving external webpack files
  packages/commonwealth/client/scripts/helpers/snapshot_utils.ts
  packages/commonwealth/package.json
  packages/commonwealth/server.ts
  packages/commonwealth/server/scripts/setupAppRoutes.ts
  packages/commonwealth/webpack/webpack.base.config.js
  packages/commonwealth/webpack/webpack.dev.config.js
  yarn.lock
Labels: cleanup, C1, S2

#2504 Create Community Bug Fix
  packages/commonwealth/client/scripts/views/pages/create_community/cosmos_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/erc20_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/erc721_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/eth_dao_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/starter_community_form.tsx
  packages/commonwealth/server/routes/createChain.ts
Labels: 1

#2507 Adds mui-base to package.json
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#2399 Generative AI Image Uploader Component Update
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_cover_image_uploader.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_cover_image_uploader.scss
  packages/commonwealth/package.json
  packages/commonwealth/server/routes/generateImage.ts
  packages/commonwealth/server/routing/router.ts
  yarn.lock
Labels: 8

#2437 JSX-ify landing folder
  packages/commonwealth/client/scripts/views/modals/confirm_invite_modal.ts
  packages/commonwealth/client/scripts/views/modals/select_address_modal.ts
  packages/commonwealth/client/scripts/views/pages/discussions/index.tsx
  packages/commonwealth/client/scripts/views/pages/landing/chains_slider.ts
  packages/commonwealth/client/scripts/views/pages/landing/chains_slider.tsx
  packages/commonwealth/client/scripts/views/pages/landing/creators_card_section.ts
  packages/commonwealth/client/scripts/views/pages/landing/creators_card_section.tsx
  packages/commonwealth/client/scripts/views/pages/landing/crowdfunding_card_section.ts
  packages/commonwealth/client/scripts/views/pages/landing/crowdfunding_card_section.tsx
  packages/commonwealth/client/scripts/views/pages/landing/find_your_community_section.ts
  packages/commonwealth/client/scripts/views/pages/landing/find_your_community_section.tsx
  packages/commonwealth/client/scripts/views/pages/landing/find_your_token_input.ts
  packages/commonwealth/client/scripts/views/pages/landing/find_your_token_input.tsx
  packages/commonwealth/client/scripts/views/pages/landing/index.ts
  packages/commonwealth/client/scripts/views/pages/landing/index.tsx
  packages/commonwealth/client/scripts/views/pages/landing/input_token_option.ts
  packages/commonwealth/client/scripts/views/pages/landing/input_token_option.tsx
  packages/commonwealth/client/scripts/views/pages/landing/input_tokens_lists.tsx
  packages/commonwealth/client/scripts/views/pages/landing/landing_page_button.ts
  packages/commonwealth/client/scripts/views/pages/landing/landing_page_header.ts
  packages/commonwealth/client/scripts/views/pages/landing/landing_page_header.tsx
  packages/commonwealth/client/scripts/views/pages/landing/landing_page_pre_footer.ts
  packages/commonwealth/client/scripts/views/pages/landing/landing_page_pre_footer.tsx
  packages/commonwealth/client/scripts/views/pages/landing/list_container.ts
  packages/commonwealth/client/scripts/views/pages/landing/list_container.tsx
  packages/commonwealth/client/scripts/views/pages/landing/list_mapper_with_item.ts
  packages/commonwealth/client/scripts/views/pages/landing/list_mapper_with_item.tsx
  packages/commonwealth/client/scripts/views/pages/landing/listed_card_with_image.ts
  packages/commonwealth/client/scripts/views/pages/landing/listed_card_with_image.tsx
  packages/commonwealth/client/scripts/views/pages/landing/tokens_community_hero.ts
  packages/commonwealth/client/scripts/views/pages/landing/tokens_community_hero.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
  packages/commonwealth/client/styles/pages/landing/creators_card_section.scss
  packages/commonwealth/client/styles/pages/landing/crowdfunding_card_section.scss
  packages/commonwealth/client/styles/pages/landing/find_your_community_section.scss
  packages/commonwealth/client/styles/pages/landing/index.scss
  packages/commonwealth/client/styles/pages/landing/landing_page_header.scss
  packages/commonwealth/client/styles/pages/landing/tokens_community_hero.scss
  packages/commonwealth/shared/analytics/types.ts
Labels: cleanup, React, C1, S2

#2448 create Permissions functionality
  packages/common-common/src/permissions.ts
  packages/common-common/test/unit/computePermissions.spec.ts
  packages/common-common/tsconfig.json
  packages/commonwealth/client/scripts/controllers/server/roles.ts
  packages/commonwealth/client/scripts/models/ChainInfo.ts
  packages/commonwealth/client/scripts/models/CommunityRole.ts
  packages/commonwealth/client/scripts/models/RoleInfo.ts
  packages/commonwealth/client/scripts/models/RolePermission.ts
  packages/commonwealth/client/scripts/models/index.ts
  packages/commonwealth/client/scripts/views/components/chat/chat_window.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/index.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/helpers.ts
  packages/commonwealth/client/scripts/views/pages/manage_community/index.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/upgrade_roles_form.tsx
  packages/commonwealth/client/scripts/views/pages/spec_settings.tsx
  packages/commonwealth/server/controller/index.ts
  packages/commonwealth/server/routes/chat/getChatChannel.ts
  packages/commonwealth/server/routes/chat/getChatMessages.ts
  packages/commonwealth/server/routes/createThread.ts
  packages/commonwealth/server/routing/router.ts
  packages/commonwealth/server/socket/chatNs.ts
  packages/commonwealth/server/util/permissions.ts
  packages/commonwealth/server/util/roles.ts
  packages/commonwealth/shared/adapters/chain/ethereum/keys.ts
  packages/commonwealth/shared/types.ts
  packages/commonwealth/shared/utils.ts
  packages/commonwealth/test/integration/api/threads.spec.ts
  packages/commonwealth/test/integration/api/webhooks.spec.ts
  packages/commonwealth/test/unit/permissions/PermissionsManager.spec.ts
  packages/commonwealth/test/unit/permissions/aggregatePermissions.spec.ts
  packages/commonwealth/test/unit/permissions/computePermissions.spec.ts
  packages/commonwealth/test/unit/permissions/hasPermission.spec.ts
  packages/commonwealth/test/util/modelUtils.ts
Labels: enhancement

#2257 PR2: Contracts Main
  packages/commonwealth/client/scripts/app.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/cosmos_evm_metamask_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
  packages/commonwealth/client/scripts/controllers/app/web_wallets.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/callContractFunction.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/chain.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/account.ts
  packages/commonwealth/client/scripts/controllers/server/contracts.ts
  packages/commonwealth/client/scripts/helpers/abi_form_helpers.ts
  packages/commonwealth/client/scripts/models/Contract.ts
  packages/commonwealth/client/scripts/models/IWebWallet.ts
  packages/commonwealth/client/scripts/stores/ContractsStore.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_divider.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_text_input.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/index.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/types.ts
  packages/commonwealth/client/scripts/views/pages/general_contract/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract/add_contract_and_abi_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract/index.tsx
  packages/commonwealth/client/styles/footer.scss
  packages/commonwealth/client/styles/pages/general_contract/index.scss
  packages/commonwealth/client/styles/pages/new_contract/add_contract_and_abi_form.scss
  packages/commonwealth/client/styles/pages/new_contract/new_contract_page.scss
  packages/commonwealth/server/config.ts
  packages/commonwealth/server/migrations/20220926174017-add-isFactory-nickname-to-contracts.js
  packages/commonwealth/server/migrations/20221122190350-add-nickname-to-contractAbis.js
  packages/commonwealth/server/models/contract.ts
  packages/commonwealth/server/models/contract_abi.ts
  packages/commonwealth/server/routes/contractAbis/createContractAbi.ts
  packages/commonwealth/server/routes/contracts/createContract.ts
  packages/commonwealth/server/routes/etherscanAPI.ts
  packages/commonwealth/server/routing/external.ts
  packages/commonwealth/server/routing/router.ts
  packages/commonwealth/server/util/abiValidation.ts
  packages/commonwealth/shared/abi_utils.ts
  packages/commonwealth/test/unit/abi_functions/abi_form_helpers.spec.ts
  packages/commonwealth/test/unit/abi_functions/abi_utils.spec.ts
Labels: ContractsUI

#2528 Fix Chain-Events
  .github/workflows/CI.yml
  packages/chain-events/package.json
  packages/chain-events/scripts/batchPoller.ts
  packages/chain-events/scripts/migrateChainEntities.ts
  packages/chain-events/scripts/scraper.ts
  packages/chain-events/services/ChainEventsConsumer/republishMessages.ts
  packages/chain-events/services/app/Server.ts
  packages/chain-events/tsconfig.services.json
  packages/chain-events/tsconfig.src.json
  packages/common-common/tsconfig.json
  packages/commonwealth/Procfile
  packages/commonwealth/client/scripts/controllers/server/roles.ts
  packages/commonwealth/client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/upgrade_roles_form.tsx
  packages/commonwealth/client/scripts/views/pages/spec_settings.tsx
  packages/commonwealth/server/controller/index.ts
  packages/commonwealth/server/routes/chat/getChatMessages.ts
  packages/commonwealth/server/routing/router.ts
  packages/commonwealth/server/util/roles.ts
  packages/commonwealth/shared/adapters/chain/ethereum/keys.ts
  packages/commonwealth/shared/permissions.ts
  packages/commonwealth/shared/utils.ts
  packages/commonwealth/test/integration/api/threads.spec.ts
  packages/commonwealth/test/integration/api/webhooks.spec.ts
  packages/commonwealth/test/unit/permissions/PermissionsManager.spec.ts
  packages/commonwealth/test/unit/permissions/aggregatePermissions.spec.ts
  packages/commonwealth/test/unit/permissions/computePermissions.spec.ts
  packages/commonwealth/test/unit/permissions/hasPermission.spec.ts
  packages/commonwealth/test/util/modelUtils.ts
Labels: bug, high priority, P1

#2501 Edit Collaborators Modal Bug Fix
  packages/commonwealth/client/scripts/views/modals/edit_collaborators_modal.tsx
  packages/commonwealth/client/styles/modals/edit_collaborators_modal.scss
  packages/commonwealth/server/routes/bulkMembers.ts
  packages/commonwealth/server/util/roles.ts
Labels: 2

#2546 Fixed StatsPage view and corresponding API
  packages/commonwealth/client/scripts/views/pages/stats.tsx
  packages/commonwealth/server/routes/communityStats.ts
Labels: bug

#2557 Pinned Posts on Overview Page Fix
  packages/commonwealth/client/scripts/views/pages/overview/index.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
Labels: 1

#2486 App.ts file refactor
  packages/commonwealth/client/scripts/app.ts
  packages/commonwealth/client/scripts/controllers/app/login.ts
  packages/commonwealth/client/scripts/helpers/chain.ts
  packages/commonwealth/client/scripts/helpers/constants.ts
  packages/commonwealth/client/scripts/helpers/handleUpdateEmailConfirmation.ts
  packages/commonwealth/client/scripts/helpers/handleWindowError.ts
  packages/commonwealth/client/scripts/helpers/index.ts
  packages/commonwealth/client/scripts/helpers/initializeMixpanel.ts
  packages/commonwealth/client/scripts/helpers/injectGoogleTagManagerScript.ts
  packages/commonwealth/client/scripts/helpers/momentUpdateLocale.ts
  packages/commonwealth/client/scripts/helpers/showLoginNotification.ts
  packages/commonwealth/client/scripts/router.ts
  packages/commonwealth/client/scripts/state.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_sidebar_menu.tsx
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/scripts/views/components/new_thread_form/new_thread_form.tsx
  packages/commonwealth/client/scripts/views/components/proposal_card/index.tsx
  packages/commonwealth/client/scripts/views/components/proposals/proposals_explainers.tsx
  packages/commonwealth/client/scripts/views/layout.tsx
  packages/commonwealth/client/scripts/views/menus/create_content_menu.tsx
  packages/commonwealth/client/scripts/views/menus/notifications_menu.tsx
  packages/commonwealth/client/scripts/views/modals/confirm_invite_modal.tsx
  packages/commonwealth/client/scripts/views/modals/edit_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/login_modal.tsx
  packages/commonwealth/client/scripts/views/pages/chat.tsx
  packages/commonwealth/client/scripts/views/pages/council.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/cosmos_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/erc20_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/erc721_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/eth_dao_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/spl_token_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/sputnik_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/starter_community_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/substrate_form.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/stages_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/topics_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions_redirect.tsx
  packages/commonwealth/client/scripts/views/pages/finish_axie_login.tsx
  packages/commonwealth/client/scripts/views/pages/finish_near_login.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/index.tsx
  packages/commonwealth/client/scripts/views/pages/members.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/cosmos_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_thread.tsx
  packages/commonwealth/client/scripts/views/pages/overview/index.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
  packages/commonwealth/client/scripts/views/pages/profile/index.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_bio.ts
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/snapshot_proposal_card.tsx
  packages/commonwealth/client/scripts/views/pages/spec_settings.tsx
  packages/commonwealth/client/scripts/views/pages/tips.tsx
  packages/commonwealth/client/scripts/views/pages/view_multiple_snapshot_spaces/snapshot_space_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/linked_proposals_embed.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/edit_body.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/thread_components.tsx
Labels: cleanup

#2599 Fix Commonwealth Consumer
  packages/commonwealth/shared/utils.ts
Labels: bug, P1
