Repository hicommonwealth/commonwealth, pull requests merged in 2023-02, with the labels that each got.

#2637 Update Edgeware ChainNode URL
  packages/commonwealth/server/migrations/20230202213211-update-edgeware-chainNode.js
Labels: bug

#2643 autoupdate
  .github/workflows/autoupdate.yaml
Labels: autoupdate

#2668 Remove autoupdate workflow.
  .github/workflows/autoupdate.yaml
Labels: 1

#2482 Stopped rocket loader from handling webpack bundles
  packages/commonwealth/package.json
  packages/commonwealth/webpack/webpack.base.config.js
  yarn.lock
Labels: C1, S3

#2727 React: Fix Fragment shorthand.
  packages/commonwealth/.babelrc
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/navigation/generalRoutes.tsx
  packages/commonwealth/client/scripts/views/components/breadcrumbs_title_tag.tsx
  packages/commonwealth/client/scripts/views/components/chat/chat_section.tsx
  packages/commonwealth/client/scripts/views/components/collapsible_body_text.tsx
  packages/commonwealth/client/scripts/views/components/comments/comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/create_comment.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_popover/cw_address_tooltip.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_popover/cw_tooltip.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_wallets_list.tsx
  packages/commonwealth/client/scripts/views/components/edgeware_function_picker.tsx
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/scripts/views/components/new_thread_form/new_thread_form.tsx
  packages/commonwealth/client/scripts/views/components/poll_card.tsx
  packages/commonwealth/client/scripts/views/components/proposal_card/index.tsx
  packages/commonwealth/client/scripts/views/components/proposals/balance_info.tsx
  packages/commonwealth/client/scripts/views/components/proposals/voting_actions.tsx
  packages/commonwealth/client/scripts/views/components/quill/markdown_formatted_text.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/comment_reaction_button.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/thread_preview_reaction_button.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/thread_reaction_button.tsx
  packages/commonwealth/client/scripts/views/components/thread_selector.tsx
  packages/commonwealth/client/scripts/views/components/tx_signing/tx_signing_cli_option.tsx
  packages/commonwealth/client/scripts/views/components/tx_signing/tx_signing_modal_stages.tsx
  packages/commonwealth/client/scripts/views/components/tx_signing/tx_signing_web_wallet_option.tsx
  packages/commonwealth/client/scripts/views/components/user/substrate_identity.tsx
  packages/commonwealth/client/scripts/views/components/user/user.tsx
  packages/commonwealth/client/scripts/views/components/user/user_block.tsx
  packages/commonwealth/client/scripts/views/modals/ban_user_modal.tsx
  packages/commonwealth/client/scripts/views/modals/new_topic_modal.tsx
  packages/commonwealth/client/scripts/views/pages/admin.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/finish_near_login.tsx
  packages/commonwealth/client/scripts/views/pages/landing/landing_page_header.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/cosmos_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/sputnik_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_democracy_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_treasury_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_treasury_tip_form.tsx
  packages/commonwealth/client/scripts/views/pages/notification_settings/helper_components.tsx
  packages/commonwealth/client/scripts/views/pages/notification_settings/index.tsx
  packages/commonwealth/client/scripts/views/pages/search/index.tsx
  packages/commonwealth/client/scripts/views/pages/tip_detail.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/dashboard_communities_preview.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/linked_proposals_embed.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/thread_components.tsx
  packages/commonwealth/client/scripts/views/pages/web3login.tsx
  packages/commonwealth/client/scripts/views/sublayout_banners.tsx
  packages/commonwealth/webpack/webpack.base.config.js
Labels: 1, React

#2735 Replaced Redraw within NotificationsController
  packages/commonwealth/client/scripts/controllers/server/notifications.ts
  packages/commonwealth/client/scripts/controllers/server/profiles.ts
  packages/commonwealth/client/scripts/views/menus/notifications_menu.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/notification_row.tsx
Labels: React

#2740 React: Working Toasts
  packages/commonwealth/client/scripts/app.tsx
  packages/commonwealth/client/scripts/controllers/app/notifications.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/package.json
Labels: React

#2703 Replace more modals with new modal
  packages/commonwealth/client/scripts/views/components/sidebar/admin_section.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/index.tsx
  packages/commonwealth/client/scripts/views/menus/help_menu.tsx
  packages/commonwealth/client/scripts/views/modals/edit_topic_thresholds_modal.tsx
  packages/commonwealth/client/scripts/views/modals/feedback_modal.tsx
  packages/commonwealth/client/scripts/views/modals/new_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/order_topics_modal.tsx
  packages/commonwealth/client/scripts/views/modals/webhook_settings_modal.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/admin_panel_tabs.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/index.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/manage_roles.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/webhooks_form.tsx
  packages/commonwealth/client/scripts/views/sublayout_header.tsx
  yarn.lock
Labels: React

#2729 Even more new modals
  packages/commonwealth/client/scripts/views/components/snapshot_proposal_selector.tsx
  packages/commonwealth/client/scripts/views/modals/confirm_snapshot_vote_modal.tsx
  packages/commonwealth/client/scripts/views/modals/edit_topic_thresholds_modal.tsx
  packages/commonwealth/client/scripts/views/modals/linked_thread_modal.tsx
  packages/commonwealth/client/scripts/views/modals/offchain_voting_modal.tsx
  packages/commonwealth/client/scripts/views/modals/poll_editor_modal.tsx
  packages/commonwealth/client/scripts/views/modals/update_proposal_status_modal.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/proposal_components.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card_container.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/linked_proposals_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/linked_threads_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/poll_cards.tsx
Labels: React

#2744 Convert misc components
  packages/commonwealth/client/scripts/views/components/breadcrumbs_title_tag.tsx
  packages/commonwealth/client/scripts/views/components/cards_collection.tsx
  packages/commonwealth/client/scripts/views/components/chain_entities_selector.tsx
  packages/commonwealth/client/scripts/views/components/code_block.tsx
  packages/commonwealth/client/scripts/views/components/gov_explainer.tsx
  packages/commonwealth/client/scripts/views/components/proposal_card/index.tsx
  packages/commonwealth/client/scripts/views/components/proposal_card/proposal_tag.tsx
  packages/commonwealth/client/scripts/views/components/proposals/aave_proposal_card_detail.tsx
  packages/commonwealth/client/scripts/views/components/proposals/balance_info.tsx
  packages/commonwealth/client/scripts/views/components/proposals/convictions_chooser.tsx
  packages/commonwealth/client/scripts/views/components/proposals/proposal_extensions.tsx
  packages/commonwealth/client/scripts/views/components/proposals/proposals_explainers.tsx
  packages/commonwealth/client/scripts/views/modals/update_proposal_status_modal.tsx
Labels: React

#2736 Modal replacement galore
  packages/commonwealth/client/scripts/views/components/user/user.tsx
  packages/commonwealth/client/scripts/views/modals/ban_user_modal.tsx
  packages/commonwealth/client/scripts/views/modals/change_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/confirm_snapshot_vote_modal.tsx
  packages/commonwealth/client/scripts/views/modals/edit_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/preview_modal.tsx
  packages/commonwealth/client/scripts/views/modals/update_proposal_status_modal.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/topics_menu.tsx
Labels: React

#2758 Lots of deletions, some type errors
  packages/commonwealth/client/scripts/helpers/index.ts
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/router.ts
  packages/commonwealth/client/scripts/views/components/code_block.tsx
  packages/commonwealth/client/scripts/views/components/collapsible_body_text.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/countdown.tsx
  packages/commonwealth/client/scripts/views/components/edgeware_function_picker.tsx
  packages/commonwealth/client/scripts/views/components/proposals/proposal_extensions.tsx
  packages/commonwealth/client/scripts/views/components/proposals/voting_actions.tsx
  packages/commonwealth/client/scripts/views/components/tx_signing/helpers.ts
  packages/commonwealth/client/scripts/views/components/tx_signing/tx_signing_cli_option.tsx
  packages/commonwealth/client/scripts/views/components/tx_signing/tx_signing_modal_stages.tsx
  packages/commonwealth/client/scripts/views/components/tx_signing/tx_signing_transaction_box.tsx
  packages/commonwealth/client/scripts/views/components/tx_signing/tx_signing_web_wallet_option.tsx
  packages/commonwealth/client/scripts/views/components/tx_signing/types.ts
  packages/commonwealth/client/scripts/views/modals/tx_signing_modal.tsx
  packages/commonwealth/client/scripts/views/pages/admin.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_democracy_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_treasury_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/substrate_treasury_tip_form.tsx
  packages/commonwealth/client/scripts/views/pages/spec_settings.tsx
  packages/commonwealth/client/scripts/views/pages/tip_detail.tsx
  packages/commonwealth/client/scripts/views/pages/tips.tsx
  packages/commonwealth/client/scripts/views/pages/treasury.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/styles/components/code_block.scss
  packages/commonwealth/client/styles/components/tx_signing/tx_signing_cli_option.scss
  packages/commonwealth/client/styles/components/tx_signing/tx_signing_transaction_box.scss
  packages/commonwealth/client/styles/modals/tx_signing_modal.scss
  packages/commonwealth/client/styles/pages/admin.scss
  packages/commonwealth/client/styles/pages/spec_settings.scss
Labels: React

#2763 Conversions 1
  packages/commonwealth/client/scripts/views/components/comments/comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/create_comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/edit_comment.tsx
  packages/commonwealth/client/scripts/views/components/proposals/vote_listing.tsx
  packages/commonwealth/client/scripts/views/components/proposals/voting_actions.tsx
  packages/commonwealth/client/scripts/views/components/proposals/voting_result_components.tsx
  packages/commonwealth/client/scripts/views/components/proposals/voting_results.tsx
  packages/commonwealth/client/scripts/views/components/quill/markdown_formatted_text.tsx
  packages/commonwealth/client/scripts/views/components/quill/quill_formatted_text.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/discussion_section.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/explore_sidebar.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/external_links_module.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/governance_section.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/sidebar_quick_switcher.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/sidebar_section.tsx
Labels: React

#2764 Conversions 2
  packages/commonwealth/client/scripts/views/app_mobile_menus.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_avatar_group.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_popover/cw_popover.tsx
  packages/commonwealth/client/scripts/views/components/user/anonymous_user.tsx
  packages/commonwealth/client/scripts/views/components/user/user_block.tsx
  packages/commonwealth/client/scripts/views/components/user/user_gallery.tsx
  packages/commonwealth/client/scripts/views/footer.tsx
  packages/commonwealth/client/scripts/views/menus/main_menu.tsx
  packages/commonwealth/client/scripts/views/modals/new_thread_modal.tsx
  packages/commonwealth/client/scripts/views/sublayout_banners.tsx
  packages/commonwealth/client/scripts/views/toast.tsx
  packages/commonwealth/client/styles/modals/new_thread_modal.scss
Labels: React

#2766 Conversions 3
  packages/commonwealth/client/scripts/views/layout.tsx
  packages/commonwealth/client/scripts/views/pages/404.tsx
  packages/commonwealth/client/scripts/views/pages/components.tsx
  packages/commonwealth/client/scripts/views/pages/delegate.tsx
  packages/commonwealth/client/scripts/views/pages/discussions_redirect.tsx
  packages/commonwealth/client/scripts/views/pages/error.tsx
  packages/commonwealth/client/scripts/views/pages/finish_near_login.tsx
  packages/commonwealth/client/scripts/views/pages/general_contract/index.tsx
  packages/commonwealth/client/scripts/views/pages/loading.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_thread.tsx
  packages/commonwealth/client/scripts/views/pages/privacy.tsx
  packages/commonwealth/client/scripts/views/pages/proposals.tsx
  packages/commonwealth/client/scripts/views/pages/search/index.tsx
  packages/commonwealth/client/scripts/views/pages/sputnikdaos.tsx
  packages/commonwealth/client/scripts/views/pages/stats.tsx
  packages/commonwealth/client/scripts/views/pages/terms.tsx
  packages/commonwealth/client/scripts/views/pages/tip_detail.tsx
  packages/commonwealth/client/scripts/views/pages/tips.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/scripts/views/pages/web3login.tsx
  packages/commonwealth/client/scripts/views/pages/why_commonwealth.tsx
  packages/commonwealth/client/styles/pages/delegate.scss
Labels: React

#2759 Add virtuoso lib for react virtualization
  packages/commonwealth/client/scripts/views/pages/members.tsx
  packages/commonwealth/client/styles/components/user/user.scss
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#2765 Ensure CET Removal Backwards Compatibility.
  packages/commonwealth/client/scripts/controllers/server/chain_entities.ts
  packages/commonwealth/client/scripts/helpers/getFetch.ts
  packages/commonwealth/client/scripts/helpers/getUrl.ts
  packages/commonwealth/client/scripts/models/DashboardActivityNotification.ts
  packages/commonwealth/client/scripts/views/pages/user_dashboard/helpers.ts
  packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_chain_event_row.tsx
  packages/commonwealth/server.ts
  packages/commonwealth/server/config.ts
  packages/commonwealth/server/util/entitiesProxy.ts
Labels: 1

#2767 React import hot fixes
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/router.ts
  packages/commonwealth/client/scripts/views/pages/profile/index.ts
  packages/commonwealth/client/scripts/views/pages/sputnikdaos.tsx
  packages/commonwealth/client/scripts/views/pages/tips.tsx
Labels: React

#2760 Remove format commands from package level package.json
  packages/common-common/package.json
  packages/commonwealth/package.json
  packages/snapshot-listener/package.json
Labels: bug

#2768 Conversions 4
  packages/commonwealth/client/scripts/controllers/chain/ethereum/aave/proposal.ts
  packages/commonwealth/client/scripts/mithrilInterop/index.ts
  packages/commonwealth/client/scripts/mithrilInterop/mithrilInteropMithril.ts.old
  packages/commonwealth/client/scripts/views/components/proposals/aave_proposal_card_detail.tsx
  packages/commonwealth/client/scripts/views/pages/proposals.tsx
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/index.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_chain_event_row.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_bottom.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_top.tsx
  packages/commonwealth/client/scripts/views/pages/view_multiple_snapshot_spaces/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_multiple_snapshot_spaces/snapshot_space_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/aave_summary.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/linked_proposals_embed.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/proposal_components.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_information_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_votes_table.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/edit_body.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/thread_components.tsx
Labels: React

#2773 Adds styling to analytics page
  packages/commonwealth/client/scripts/views/pages/stats.tsx
  packages/commonwealth/client/styles/pages/stats.scss
Labels: 1

#2778 Refactor members page to eliminate dead code
  packages/commonwealth/client/scripts/views/pages/members.tsx
  packages/commonwealth/client/styles/pages/members.scss
Labels: React

#2770 Conversions 5
  packages/commonwealth/client/scripts/mithrilInterop/index.ts
  packages/commonwealth/client/scripts/views/pages/landing/chains_slider.tsx
  packages/commonwealth/client/scripts/views/pages/landing/creators_card_section.tsx
  packages/commonwealth/client/scripts/views/pages/landing/crowdfunding_card_section.tsx
  packages/commonwealth/client/scripts/views/pages/landing/find_your_community_section.tsx
  packages/commonwealth/client/scripts/views/pages/landing/find_your_token_input.tsx
  packages/commonwealth/client/scripts/views/pages/landing/index.tsx
  packages/commonwealth/client/scripts/views/pages/landing/input_token_option.tsx
  packages/commonwealth/client/scripts/views/pages/landing/input_tokens_lists.tsx
  packages/commonwealth/client/scripts/views/pages/landing/landing_page_pre_footer.tsx
  packages/commonwealth/client/scripts/views/pages/landing/list_container.tsx
  packages/commonwealth/client/scripts/views/pages/landing/list_mapper_with_item.tsx
  packages/commonwealth/client/scripts/views/pages/landing/listed_card_with_image.tsx
  packages/commonwealth/client/scripts/views/pages/landing/tokens_community_hero.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/notification_settings/index.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar_components.tsx
  packages/commonwealth/client/scripts/views/pages/settings/composer_section.tsx
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/index.tsx
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/snapshot_proposal_card.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/dashboard_communities_preview.tsx
Labels: React

#2794 Conversions 6
  packages/commonwealth/client/scripts/views/components/component_kit/cw_avatar.tsx
  packages/commonwealth/client/scripts/views/pages/communities.tsx
  packages/commonwealth/client/scripts/views/pages/discussions_redirect.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/index.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/notification_row.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/notification_row_components.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
  packages/commonwealth/client/styles/pages/notifications/index.scss
  packages/commonwealth/client/styles/pages/notifications/notification_row.scss
Labels: React

#2777 Added infinite loader to discussions page
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/index.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/stages_menu.tsx
  packages/commonwealth/client/styles/pages/discussions/index.scss
  packages/commonwealth/client/styles/sublayout.scss
Labels: React

#2801 Fixed infinite load scroll bar to match prod
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
Labels: React

#2804 React: fix navigation on sidebar and in app logo
  packages/commonwealth/client/scripts/views/components/component_kit/cw_sidebar_menu.tsx
  packages/commonwealth/client/scripts/views/sublayout_header.tsx
Labels: React

#2805 React: reactify login flow components
  packages/commonwealth/client/scripts/helpers/index.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_avatar_username_input.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_wallets_list.tsx
  packages/commonwealth/client/scripts/views/pages/login/helpers.ts
  packages/commonwealth/client/scripts/views/pages/login/login_boilerplate.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_desktop.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_desktop_sidebar.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_eth_alert.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_mobile.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_text.tsx
  packages/commonwealth/client/scripts/views/pages/login/types.ts
Labels: React

#2809 New Snapshot Proposal Page Hotfix
  packages/commonwealth/client/scripts/views/pages/new_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
Labels: React

#2824 Fix redirects in login/logut flow
  packages/commonwealth/client/scripts/hooks/useForceRerender.ts
  packages/commonwealth/client/scripts/views/components/header/login_selector.tsx
  packages/commonwealth/client/scripts/views/modals/login_modal.tsx
  packages/commonwealth/client/scripts/views/pages/landing/index.tsx
  packages/commonwealth/client/scripts/views/pages/landing/landing_page_header.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_wallets_list.scss
  packages/commonwealth/client/styles/index.scss
Labels: bug, React

#2807 Misc errors
  packages/commonwealth/client/scripts/helpers/index.ts
  packages/commonwealth/client/scripts/views/components/countdown.tsx
  packages/commonwealth/client/scripts/views/components/proposal_card/helpers.tsx
  packages/commonwealth/client/scripts/views/components/proposals/proposals_explainers.tsx
  packages/commonwealth/client/scripts/views/components/user/user.tsx
  packages/commonwealth/client/scripts/views/menus/notifications_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/index.tsx
  packages/commonwealth/client/scripts/views/pages/referenda.tsx
  packages/commonwealth/client/scripts/views/pages/treasury.tsx
  packages/commonwealth/client/scripts/views/sublayout_header.tsx
  packages/commonwealth/client/styles/components/header/notifications_menu.scss
  packages/commonwealth/client/styles/components/user/user.scss
  packages/commonwealth/client/styles/pages/snapshot/snapshot_votes_table.scss
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#2814 Get create community flow rendering
  packages/commonwealth/client/scripts/views/components/component_kit/cw_sidebar_menu.tsx
  packages/commonwealth/client/scripts/views/menus/create_content_menu.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/chain_input_rows.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/cosmos_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/erc20_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/erc721_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/eth_dao_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/index.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/spl_token_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/sputnik_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/starter_community_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/substrate_form.tsx
  packages/commonwealth/server/routes/createChain.ts
Labels: React

#2813 Feed Component
  packages/commonwealth/client/scripts/views/components/feed.tsx
  packages/commonwealth/client/scripts/views/pages/feed/index.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
  packages/commonwealth/client/styles/components/feed.scss
  packages/commonwealth/client/styles/pages/feed/index.scss
Labels: React

#2826 Converted ManageCommunitiesPage to a react functional component
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/router.ts
  packages/commonwealth/client/scripts/views/pages/manage_community/ManageCommunityPage.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/index.tsx
Labels: React

#2753 Delete Unused Client Chain Controller Code
  packages/commonwealth/client/scripts/controllers/chain/cosmos/account.ts
  packages/commonwealth/client/scripts/controllers/chain/cosmos/accounts.ts
  packages/commonwealth/client/scripts/controllers/chain/cosmos/governance.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/aave/governance.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/chain.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/compound/chain.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/compound/proposal.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/adapter.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/api.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/chain.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/governance.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/member.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/members.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/moloch/proposal.ts
  packages/commonwealth/client/scripts/controllers/chain/near/chain.ts
  packages/commonwealth/client/scripts/controllers/chain/solana/accounts.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/account.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/democracy.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/democracy_proposals.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/democracy_referendum.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/shared.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/treasury.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/treasury_tip.ts
  packages/commonwealth/client/scripts/controllers/chain/substrate/treasury_tips.ts
  packages/commonwealth/client/scripts/helpers/chain.ts
  packages/commonwealth/client/scripts/views/components/proposal_card/helpers.tsx
  packages/commonwealth/client/scripts/views/components/proposals/helpers.ts
  packages/commonwealth/client/scripts/views/components/proposals/vote_listing.tsx
  packages/commonwealth/client/scripts/views/components/proposals/voting_actions.tsx
  packages/commonwealth/client/scripts/views/components/proposals/voting_results.tsx
  packages/commonwealth/client/scripts/views/pages/proposals.tsx
  packages/commonwealth/client/scripts/views/pages/settings/linked_addresses_section.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/proposal_components.tsx
Labels: enhancement, autoupdate

#2832 Fix proposal page regression in #2753.
  packages/commonwealth/client/scripts/views/components/proposals/voting_results.tsx
Labels: 1

#2791 Snapshot Notifications
  packages/commonwealth/client/scripts/router.ts
  packages/commonwealth/client/scripts/views/components/notification_row.ts
  packages/commonwealth/client/scripts/views/pages/notifications_page.ts
  packages/commonwealth/client/scripts/views/pages/snapshot_proposals/index.tsx
  packages/commonwealth/client/styles/pages/snapshot_proposals.scss
  packages/commonwealth/server/CommonwealthConsumer/messageProcessors/snapshotConsumer.ts
  packages/commonwealth/server/migrations/20230214171859-make-chain-id-nullable.js
  packages/commonwealth/server/routes/subscription/createSubscription.ts
  packages/commonwealth/server/routes/subscription/viewSubscriptions.ts
  packages/commonwealth/server/util/emitNotifications.ts
  packages/commonwealth/shared/types.ts
  packages/snapshot-listener/src/utils/fetchSnapshot.ts
Labels: 2

#2852 Fix doc truncate by bumping marked version.
  packages/commonwealth/package.json
  yarn.lock
Labels: 1

#2834 Use virtuosos dnd in order topics modal
  packages/commonwealth/client/scripts/app.tsx
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/lib/react-beautiful-dnd.tsx
  packages/commonwealth/client/scripts/views/modals/order_topics_modal.tsx
  packages/commonwealth/client/scripts/views/modals/order_topics_modal/draggable_topics_list.tsx
  packages/commonwealth/client/scripts/views/modals/order_topics_modal/index.ts
  packages/commonwealth/client/scripts/views/modals/order_topics_modal/order_topics_modal.tsx
  packages/commonwealth/client/scripts/views/pages/overview/index.tsx
  packages/commonwealth/client/styles/mixins/dragula.scss
  packages/commonwealth/client/styles/modals/order_topics_modal.scss
  packages/commonwealth/client/styles/shared.scss
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#2811 Comments Tree FC'd
  packages/commonwealth/client/scripts/views/components/comments/comments_tree.tsx
  packages/commonwealth/client/scripts/views/components/user/user.tsx
Labels: React

#2850 Convert create community flow to FC
  packages/commonwealth/client/scripts/views/pages/create_community/chain_input_rows.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/cosmos_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/erc20_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/erc721_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/eth_dao_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/hooks.ts
  packages/commonwealth/client/scripts/views/pages/create_community/index.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/spl_token_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/sputnik_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/starter_community_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/substrate_form.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/types.ts
Labels: React

#2808 Dan.fix view proposal
  packages/commonwealth/client/scripts/views/components/collapsible_body_text.tsx
  packages/commonwealth/client/scripts/views/components/proposals/proposal_extensions.tsx
  packages/commonwealth/client/scripts/views/components/proposals/vote_listing.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.tsx
Labels: React

#2858 Conversions 7
  packages/commonwealth/client/scripts/views/components/breadcrumbs_title_tag.tsx
  packages/commonwealth/client/scripts/views/components/collapsible_body_text.tsx
  packages/commonwealth/client/scripts/views/components/load_substrate_modules.tsx
  packages/commonwealth/client/scripts/views/components/new_thread_form/new_thread_form.tsx
  packages/commonwealth/client/scripts/views/components/poll_card.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/admin_section.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/index.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/notification_settings/helper_components.tsx
  packages/commonwealth/client/scripts/views/pages/profile/profile_comment_group.ts
  packages/commonwealth/client/scripts/views/pages/proposals.tsx
  packages/commonwealth/client/scripts/views/pages/referenda.tsx
  packages/commonwealth/client/scripts/views/pages/search/index.tsx
  packages/commonwealth/client/scripts/views/pages/search/search_bar_components.tsx
  packages/commonwealth/client/scripts/views/pages/treasury.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card.tsx
  packages/commonwealth/client/scripts/views/sublayout.tsx
  packages/commonwealth/client/scripts/views/sublayout_header.tsx
  packages/commonwealth/client/styles/pages/discussions/index.scss
  packages/commonwealth/client/styles/pages/discussions/recent_threads_header.scss
  packages/commonwealth/client/styles/pages/discussions/thread_preview.scss
Labels: React

#2859 Conversions 8
  packages/commonwealth/client/scripts/views/components/load_substrate_modules.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/feed/index.tsx
  packages/commonwealth/client/scripts/views/pages/general_contract/index.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/manage_roles.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/upgrade_roles_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract/add_contract_and_abi_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/aave_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/compound_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/cosmos_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_proposal/sputnik_proposal_form.tsx
  packages/commonwealth/client/scripts/views/pages/notification_settings/helper_components.tsx
  packages/commonwealth/client/scripts/views/pages/overview/index.tsx
  packages/commonwealth/client/scripts/views/pages/settings/email_section.tsx
  packages/commonwealth/client/scripts/views/pages/settings/index.tsx
  packages/commonwealth/client/scripts/views/pages/settings/linked_addresses_section.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/proposal_header_links.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/thread_components.tsx
Labels: React

#2902 React: Reactify avatar upload component
  packages/commonwealth/client/scripts/views/components/avatar_upload.tsx
Labels: React

#2908 Fix substrate first render.
  packages/commonwealth/client/scripts/models/IChainAdapter.ts
  packages/commonwealth/client/scripts/views/pages/proposals.tsx
  packages/commonwealth/client/scripts/views/pages/referenda.tsx
  packages/commonwealth/client/scripts/views/pages/tips.tsx
  packages/commonwealth/client/scripts/views/pages/treasury.tsx
Labels: React

#2904 Cleanup Addresses.profile_id.
  packages/commonwealth/server/migrations/20230223012856-cleanup-address-profile-id.js
  packages/commonwealth/server/routes/deleteAddress.ts
  packages/commonwealth/server/routes/linkExistingAddressToChain.ts
  packages/commonwealth/server/util/createAddressHelper.ts
Labels: 1

#2926 Access window prop rather than Terra lib for availability check.
  packages/commonwealth/client/scripts/controllers/app/webWallets/terra_station_web_wallet.ts
Labels: 1

#2921 New Thread Form + React Quill
  packages/commonwealth/client/scripts/views/components/new_thread_form/helpers.ts
  packages/commonwealth/client/scripts/views/components/new_thread_form/helpers/helpers.ts
  packages/commonwealth/client/scripts/views/components/new_thread_form/helpers/index.ts
  packages/commonwealth/client/scripts/views/components/new_thread_form/helpers/useAuthorName.ts
  packages/commonwealth/client/scripts/views/components/new_thread_form/helpers/useNewThreadForm.ts
  packages/commonwealth/client/scripts/views/components/new_thread_form/index.ts
  packages/commonwealth/client/scripts/views/components/new_thread_form/new_thread_form.tsx
  packages/commonwealth/client/scripts/views/components/new_thread_form/types.ts
  packages/commonwealth/client/scripts/views/modals/edit_profile_modal.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#2915 Delete chat code on client
  packages/commonwealth/client/scripts/controllers/server/socket/chatNs.ts
  packages/commonwealth/client/scripts/controllers/server/socket/index.ts
  packages/commonwealth/client/scripts/models/ChatMessage.ts
  packages/commonwealth/client/scripts/models/IChainAdapter.ts
  packages/commonwealth/client/scripts/models/index.ts
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/router.ts
  packages/commonwealth/client/scripts/views/components/chat/admin_modals.tsx
  packages/commonwealth/client/scripts/views/components/chat/chat_section.tsx
  packages/commonwealth/client/scripts/views/components/chat/chat_window.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/index.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/types.ts
  packages/commonwealth/client/scripts/views/pages/chat.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/helpers.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/notification_row.tsx
  packages/commonwealth/client/scripts/views/pages/notifications/notification_row_components.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/helpers.tsx
  packages/commonwealth/client/styles/components/sidebar/index.scss
  packages/commonwealth/client/styles/pages/chat.scss
  packages/commonwealth/client/styles/pages/landing/landing_page_header.scss
  packages/commonwealth/shared/analytics/types.ts
  packages/commonwealth/shared/permissions.ts
  packages/commonwealth/shared/types.ts
Labels: React

#2833 Changed localhost to loopback address for Chain events rmq
  packages/chain-events/services/config.ts
Labels: bug

#2935 Get avatar upload working with react-dropzone
  packages/commonwealth/client/scripts/views/components/avatar_upload.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/modals/edit_profile_modal.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/chain_input_rows.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/chain_metadata_rows.tsx
  packages/commonwealth/client/scripts/views/pages/new_thread.tsx
  packages/commonwealth/client/styles/components/avatar_upload.scss
  packages/commonwealth/package.json
  yarn.lock
Labels: React

#2950 Eliminate more old modal code
  packages/commonwealth/client/scripts/controllers/app/modals.ts
  packages/commonwealth/client/scripts/helpers/constants.ts
  packages/commonwealth/client/scripts/helpers/handleWindowError.ts
  packages/commonwealth/client/scripts/router.ts
  packages/commonwealth/client/scripts/state.ts
  packages/commonwealth/client/scripts/views/app_modals.tsx
  packages/commonwealth/client/scripts/views/components/comments/comment.tsx
  packages/commonwealth/client/scripts/views/components/comments/comments_tree.tsx
  packages/commonwealth/client/scripts/views/components/comments/edit_comment.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_modal.tsx
  packages/commonwealth/client/scripts/views/components/quill/quill_editor_component.tsx
  packages/commonwealth/client/scripts/views/components/quill/quill_editor_internal.ts
  packages/commonwealth/client/scripts/views/layout.tsx
  packages/commonwealth/client/scripts/views/modals/alert_modal.tsx
  packages/commonwealth/client/scripts/views/modals/confirm_modal.tsx
  packages/commonwealth/client/scripts/views/modals/edit_collaborators_modal.tsx
  packages/commonwealth/client/scripts/views/modals/edit_topic_modal.tsx
  packages/commonwealth/client/scripts/views/modals/preview_modal.tsx
  packages/commonwealth/client/scripts/views/modals/select_address_modal.tsx
  packages/commonwealth/client/scripts/views/pages/create_community/eth_dao_form.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview_menu.tsx
  packages/commonwealth/client/scripts/views/pages/manage_community/manage_roles.tsx
  packages/commonwealth/client/scripts/views/pages/profile/profile_banner.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_bio.ts
  packages/commonwealth/client/scripts/views/pages/profile/profile_header.ts
  packages/commonwealth/client/scripts/views/pages/settings/email_section.tsx
  packages/commonwealth/client/scripts/views/pages/settings/linked_addresses_section.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/edit_body.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/helpers.ts
  packages/commonwealth/client/scripts/views/pages/view_thread/index.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_modal.scss
  packages/commonwealth/client/styles/modals/alert_modal.scss
  packages/commonwealth/client/styles/modals/confirm_modal.scss
Labels: React
