Repository hicommonwealth/commonwealth, pull requests merged in 2023-05, with the labels that each got.

#3571 Fixed issue with pre-rendering threads
  packages/commonwealth/client/index.html
  packages/commonwealth/server/models/address.ts
  packages/commonwealth/server/scripts/setupAppRoutes.ts
Labels: React

#3685 Converted layout page to react
  packages/commonwealth/client/scripts/hooks/useNecessaryEffect.ts
  packages/commonwealth/client/scripts/views/layout.tsx
Labels: React

#3727 Switch Rollbar environment to `ROLLBAR_ENV`
  .github/workflows/CI.yml
  packages/chain-events/services/ChainEventsConsumer/chainEventsConsumer.ts
  packages/chain-events/services/ChainSubscriber/chainSubscriber.ts
  packages/chain-events/services/config.ts
  packages/commonwealth/server-test.ts
  packages/commonwealth/server.ts
  packages/commonwealth/server/CommonwealthConsumer/CommonwealthConsumer.ts
  packages/commonwealth/server/config.ts
Labels: bug

#3690 Timestamps on Chain Model
  packages/commonwealth/server/migrations/20230503183808-chain-timestamps.js
  packages/commonwealth/server/models/chain.ts
Labels: 2

#3587 Fix for Redirect on Urls Missing Chain Scope
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/navigation/commonDomainRoutes.tsx
  packages/commonwealth/client/scripts/views/pages/thread_redirect.tsx
  packages/commonwealth/server/routes/getThreads.ts
  packages/commonwealth/server/routing/router.ts
Labels: 2

#3534 Show total threads count in threads view
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/models/IChainAdapter.ts
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
  packages/commonwealth/client/scripts/views/pages/overview/index.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
  packages/commonwealth/server/routes/bulkOffchain.ts
  packages/commonwealth/server/routes/bulkThreads.ts
Labels: React

#3536 Bet1 Fast Follows Pt 2
  packages/commonwealth/client/scripts/controllers/server/contracts.ts
  packages/commonwealth/client/scripts/models/Contract.ts
  packages/commonwealth/client/scripts/views/modals/manage_contract_template_modal.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_card.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_template_card.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract_template/create_contract_template_form.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/index.tsx
  packages/commonwealth/client/styles/pages/contracts/contract_card.scss
  packages/commonwealth/client/styles/pages/contracts/contract_template_card.scss
  packages/commonwealth/server/migrations/20230420155836-update-bet1-models.js
  packages/commonwealth/server/models/community_contract_metadata.ts
  packages/commonwealth/server/models/template.ts
  packages/commonwealth/server/routes/proposalTemplate.ts
  packages/commonwealth/server/routes/templates.ts
Labels: 3, design review

#3311 delete old unused events migration
  packages/chain-events/services/ChainEventsConsumer/ChainEventHandlers/storage.ts
  packages/chain-events/services/database/migrations/20230401055258-delete-unused-events.js
Labels: 3, Performance

#3783 Add stage tag to discussions and overview
  packages/commonwealth/client/scripts/helpers/index.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_tag.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/thread_components.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_tag.scss
Labels: design review

#3678 Bet 1 Fast Follows Pt 3: Template Library
  packages/commonwealth/client/scripts/controllers/server/contracts.ts
  packages/commonwealth/client/scripts/helpers/action_template_helpers.tsx
  packages/commonwealth/client/scripts/models/Template.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_dropdown.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/admin_section.tsx
  packages/commonwealth/client/scripts/views/modals/view_template_modal.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_card.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/contract_template_card.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/index.tsx
  packages/commonwealth/client/scripts/views/pages/contracts/template_display_tab.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract/add_contract_and_abi_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract/index.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract_template/create_contract_template_form.tsx
  packages/commonwealth/client/scripts/views/pages/new_contract_template/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_template/view_template.tsx
  packages/commonwealth/client/styles/components/user/user.scss
  packages/commonwealth/client/styles/modals/view_template_modal.scss
  packages/commonwealth/client/styles/new_contract_template/create_contract_template_form.scss
  packages/commonwealth/client/styles/new_contract_template/new_contract_template_page.scss
  packages/commonwealth/client/styles/pages/contracts/contract_card.scss
  packages/commonwealth/client/styles/pages/contracts/contracts_page.scss
  packages/commonwealth/server/routes/proposalTemplate.ts
  packages/commonwealth/server/routes/templates.ts
  packages/commonwealth/server/routing/router.ts
  packages/commonwealth/shared/validateJson.ts
Labels: 5, design review

#3853 Increase base font size slightly
  packages/commonwealth/client/styles/mixins/text.scss
Labels: design review

#3793 Enforce verify email address before allowing user to add email digest notifications
  packages/commonwealth/client/scripts/views/pages/notification_settings/index.tsx
  packages/commonwealth/client/styles/pages/notification_settings/index.scss
Labels: design review

#3873 Fix token balance failure handling
  packages/commonwealth/client/scripts/controllers/chain/cosmos/adapter.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/tokenAdapter.ts
  packages/commonwealth/client/scripts/controllers/chain/solana/tokenAdapter.ts
Labels: 1

#3869 Anonymous User fix for User Component
  packages/commonwealth/client/scripts/views/components/Comments/CommentAuthor.tsx
  packages/commonwealth/client/scripts/views/components/user/anonymous_user.tsx
  packages/commonwealth/client/scripts/views/components/user/user.tsx
  packages/commonwealth/client/scripts/views/components/user/user_gallery.tsx
Labels: 2

#3905 Unstable Test Fix + CE CI Job Renaming
  .github/workflows/CI.yml
  packages/chain-events/chain-testing/sdk/chainTesting.ts
  packages/chain-events/chain-testing/src/routes/chain.ts
  packages/chain-events/test/integration/service-tests/EVM/aave.spec.ts
  packages/chain-events/test/integration/service-tests/EVM/compoundBravo.spec.ts
  packages/chain-events/test/util.ts
Labels: bug

#3632 Reuse fetched threads when switching b/w threads/topics
  packages/commonwealth/client/scripts/controllers/server/comments.ts
  packages/commonwealth/client/scripts/controllers/server/polls.ts
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/controllers/server/topics.ts
  packages/commonwealth/client/scripts/stores/ProposalStore.ts
  packages/commonwealth/client/scripts/stores/Store.ts
  packages/commonwealth/client/scripts/views/components/Comments/CommentComponent.tsx
  packages/commonwealth/client/scripts/views/components/Comments/CommentsTree.tsx
  packages/commonwealth/client/scripts/views/components/reaction_button/UseReactionButton.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/stages_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/topics_menu.tsx
  packages/commonwealth/client/scripts/views/pages/loading.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/server/models/comment.ts
  packages/commonwealth/server/models/thread.ts
  packages/commonwealth/server/routes/getThreads.ts
  packages/commonwealth/shared/types.ts
Labels: React

#3664 display the date a thread was last edited
  packages/commonwealth/client/scripts/views/components/component_kit/cw_content_page.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/server/migrations/20230501155646-add-last-edited-to-threads.js
  packages/commonwealth/server/models/thread.ts
  packages/commonwealth/server/routes/editThread.ts
Labels: design review, forum improvement

#3954 Fix thread view "cannot read properties of null"
  packages/commonwealth/client/scripts/views/pages/view_thread/linked_proposals_card.tsx
Labels: 1

#3969 Fix new account onboard flow breaking mid way in communities
  packages/commonwealth/client/scripts/controllers/app/login.ts
  packages/commonwealth/client/scripts/controllers/server/newProfiles.ts
  packages/commonwealth/client/scripts/controllers/server/user.ts
  packages/commonwealth/client/scripts/helpers/chain.ts
  packages/commonwealth/client/scripts/hooks/useWallets.tsx
  packages/commonwealth/client/scripts/models/Account.ts
  packages/commonwealth/client/scripts/views/pages/finish_axie_login.tsx
  packages/commonwealth/client/scripts/views/pages/finish_near_login.tsx
Labels: React

#3914 Delete Poll Functionality Fix
  packages/commonwealth/client/scripts/views/components/poll_card.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/poll_cards.tsx
  packages/commonwealth/server/routes/deletePoll.ts
Labels: 2

#3916 refactor /api/status query - for performance, db friendly
  packages/commonwealth/server/routes/status.ts
Labels: Performance

#3997 Social login with magic.link
  packages/commonwealth/client/scripts/controllers/app/login.ts
  packages/commonwealth/client/scripts/controllers/chain/ethereum/accounts.ts
  packages/commonwealth/client/scripts/hooks/useWallets.tsx
  packages/commonwealth/client/scripts/navigation/CommonDomainRoutes.tsx
  packages/commonwealth/client/scripts/navigation/CustomDomainRoutes.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_auth_button.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_custom_icons.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon_lookup.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icons.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_wallet_option_row.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_wallets_list.tsx
  packages/commonwealth/client/scripts/views/modals/login_modal.tsx
  packages/commonwealth/client/scripts/views/modals/session_signin_modal.tsx
  packages/commonwealth/client/scripts/views/pages/finish_social_login.tsx
  packages/commonwealth/client/scripts/views/pages/login/helpers.ts
  packages/commonwealth/client/scripts/views/pages/login/login_desktop.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_desktop_sidebar.tsx
  packages/commonwealth/client/scripts/views/pages/login/login_mobile.tsx
  packages/commonwealth/client/scripts/views/pages/login/types.ts
  packages/commonwealth/client/styles/components/component_kit/cw_auth_button.scss
  packages/commonwealth/client/styles/components/component_kit/cw_wallets_list.scss
  packages/commonwealth/client/styles/pages/login/login_boilerplate.scss
  packages/commonwealth/client/styles/pages/login/login_desktop.scss
  packages/commonwealth/client/styles/pages/login/login_desktop_sidebar.scss
  packages/commonwealth/client/styles/pages/login/login_mobile.scss
  packages/commonwealth/client/styles/pages/login/login_text.scss
  packages/commonwealth/package.json
  packages/commonwealth/server/models/user.ts
  packages/commonwealth/server/passport/magic.ts
  packages/commonwealth/server/routing/router.ts
  yarn.lock
Labels: design review

#4004 Sequelize: unnecessary calls from named getter of included model
  packages/commonwealth/server/routes/getAddressProfile.ts
Labels: cleanup, Performance

#3691 Added new tag to new threads on discussions page
  packages/commonwealth/client/scripts/views/components/component_kit/cw_content_page.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon_lookup.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icons.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_tag.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/NewThreadTag.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/overview/topic_summary_row.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_tag.scss
  packages/commonwealth/client/styles/mixins/border_radius.scss
Labels: design review, forum improvement

#4042 Extend Comment Depth
  packages/commonwealth/client/scripts/views/components/Comments/CommentsTree.tsx
  packages/commonwealth/server/routes/createComment.ts
Labels: 1

#4024 active threads refactor to reduce db queries
  packages/commonwealth/server/routes/activeThreads.ts
Labels: Performance

#3889 Fix Datadog Postgres Integration
  packages/commonwealth/README.md
  packages/commonwealth/datadog/conf.d/postgres.yaml
  packages/commonwealth/datadog/prerun.sh
  packages/commonwealth/scripts/setup-datadog-postgres.sh
Labels: 🐛 bug

#3933 allowing 304 for browser cached resources
  packages/common-common/src/cacheDecorator.ts
Labels: cleanup
