Repository hicommonwealth/commonwealth, pull requests merged in 2023-06, with the labels that each got.

#4019 Thread lock redesign
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/models/Thread.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_content_page.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_popover/cw_tooltip.tsx
  packages/commonwealth/client/scripts/views/components/lock_with_tooltip.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/thread_preview.tsx
  packages/commonwealth/client/scripts/views/pages/view_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/index.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/ViewThreadPage.tsx
  packages/commonwealth/client/scripts/views/pages/view_thread/lock_message.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_popover/cw_tooltip.scss
  packages/commonwealth/client/styles/pages/view_thread/index.scss
  packages/commonwealth/server/migrations/20230524163437-add-threads-lockedat-column.js
  packages/commonwealth/server/models/thread.ts
  packages/commonwealth/server/routes/bulkThreads.ts
  packages/commonwealth/server/routes/updateThreadPrivacy.ts
Labels: design review

#4131 add chromatic workflow
  .github/workflows/chromatic.yml
  package.json
Labels: Design System Update

#3926 New Sort-Implementation + Filter UI for threads
  packages/commonwealth/client/scripts/controllers/server/threads.ts
  packages/commonwealth/client/scripts/models/types.ts
  packages/commonwealth/client/scripts/views/components/Select/Option.scss
  packages/commonwealth/client/scripts/views/components/Select/Option.tsx
  packages/commonwealth/client/scripts/views/components/Select/Select.scss
  packages/commonwealth/client/scripts/views/components/Select/Select.tsx
  packages/commonwealth/client/scripts/views/components/Select/index.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_icon_lookup.ts
  packages/commonwealth/client/scripts/views/components/component_kit/cw_icons/cw_phosphor_icons.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/recent_threads_header.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/stages_menu.tsx
  packages/commonwealth/client/scripts/views/pages/discussions/topics_menu.tsx
  packages/commonwealth/client/styles/mixins/border_radius.scss
  packages/commonwealth/client/styles/mixins/colors.scss
  packages/commonwealth/client/styles/mixins/elevation.scss
  packages/commonwealth/client/styles/pages/discussions/recent_threads_header.scss
  packages/commonwealth/server/routes/bulkThreads.ts
Labels: design review

#4058 Adds Foundations components to Storybook
  packages/commonwealth/.storybook/main.js
  packages/commonwealth/.storybook/preview-head.html
  packages/commonwealth/.storybook/stories/foundations/Border.stories.tsx
  packages/commonwealth/.storybook/stories/foundations/Color.stories.tsx
  packages/commonwealth/.storybook/stories/foundations/Divider.stories.tsx
  packages/commonwealth/.storybook/stories/foundations/Elevation.stories.tsx
  packages/commonwealth/.storybook/stories/foundations/Icon.stories.tsx
  packages/commonwealth/.storybook/stories/foundations/Typography.stories.tsx
  packages/commonwealth/.storybook/stories/phosphor_icon_lookup.ts
  packages/commonwealth/.storybook/stories/styles/border.scss
  packages/commonwealth/.storybook/stories/styles/color.scss
  packages/commonwealth/.storybook/stories/styles/divider.scss
  packages/commonwealth/.storybook/stories/styles/elevation.scss
  packages/commonwealth/.storybook/stories/styles/icon.scss
  packages/commonwealth/client/scripts/views/components/component_kit/cw_card.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_text.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_card.scss
  packages/commonwealth/client/styles/components/component_kit/cw_text.scss
  packages/commonwealth/client/styles/mixins/border.scss
  packages/commonwealth/client/styles/mixins/colors.scss
  packages/commonwealth/client/styles/mixins/elevation.scss
  packages/commonwealth/client/styles/mixins/text.scss
  packages/commonwealth/client/styles/shared.scss
  packages/commonwealth/package.json
  packages/commonwealth/static/fonts/DMMono-Medium.ttf
  packages/commonwealth/static/fonts/DMMono-Regular.ttf
  packages/commonwealth/static/fonts/NeueHaasUnica-Bold.eot
  packages/commonwealth/static/fonts/NeueHaasUnica-Bold.ttf
  packages/commonwealth/static/fonts/NeueHaasUnica-Bold.woff
  packages/commonwealth/static/fonts/NeueHaasUnica-Bold.woff2
  packages/commonwealth/static/fonts/NeueHaasUnica-Italic.eot
  packages/commonwealth/static/fonts/NeueHaasUnica-Italic.ttf
  packages/commonwealth/static/fonts/NeueHaasUnica-Italic.woff
  packages/commonwealth/static/fonts/NeueHaasUnica-Italic.woff2
  packages/commonwealth/static/fonts/NeueHaasUnica-Medium.eot
  packages/commonwealth/static/fonts/NeueHaasUnica-Medium.ttf
  packages/commonwealth/static/fonts/NeueHaasUnica-Medium.woff
  packages/commonwealth/static/fonts/NeueHaasUnica-Medium.woff2
  packages/commonwealth/static/fonts/NeueHaasUnica-Regular.eot
  packages/commonwealth/static/fonts/NeueHaasUnica-Regular.ttf
  packages/commonwealth/static/fonts/NeueHaasUnica-Regular.woff
  packages/commonwealth/static/fonts/NeueHaasUnica-Regular.woff2
Labels: design QA, Design System Update

#4088 Design System: Buttons
  packages/commonwealth/.storybook/stories/components/atoms/Button.stories.tsx
  packages/commonwealth/.storybook/stories/old/atoms/Button.stories.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_button.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/new_designs/cw_button.tsx
  packages/commonwealth/client/styles/components/component_kit/cw_button.scss
  packages/commonwealth/client/styles/components/component_kit/new_designs/cw_button.scss
  packages/commonwealth/client/styles/components/component_kit/new_designs/mixins/buttons.scss
  packages/commonwealth/client/styles/mixins/colors.scss
  packages/commonwealth/client/styles/shared.scss
  packages/commonwealth/static/fonts/fonts.css
  packages/commonwealth/static/fonts/neue-haas-unica-medium.eot
  packages/commonwealth/static/fonts/neue-haas-unica-medium.ttf
  packages/commonwealth/static/fonts/neue-haas-unica-medium.woff
  packages/commonwealth/static/fonts/neue-haas-unica-medium.woff2
Labels: Design System Update
