Repository hicommonwealth/commonwealth, pull requests merged in 2023-08, with the labels that each got.

#4514 Adds new Design System Tooltip component
  packages/commonwealth/.storybook/stories/components/Tooltip.stories.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/cw_popover/cw_tooltip.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/new_designs/CWTooltip.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/types.ts
  packages/commonwealth/client/scripts/views/pages/discussions/CommentCard/CommentCard.scss
  packages/commonwealth/client/scripts/views/pages/discussions/ThreadCard/ThreadOptions/ThreadOptions.scss
  packages/commonwealth/client/styles/components/component_kit/cw_component_showcase.scss
  packages/commonwealth/client/styles/components/component_kit/cw_popover/cw_tooltip.scss
  packages/commonwealth/client/styles/components/component_kit/new_designs/CWTooltip.scss
Labels: design system, Design System Update

#4735 Add extensions to TOC
  wiki/_Table of Contents.md
Labels: 1

#4784 Remove deferChain arguments from CustomRoutes.tsx
  packages/commonwealth/client/scripts/navigation/CustomDomainRoutes.tsx
Labels: 1

#4763 Update App Initialization Flow Documentation
  packages/commonwealth/client/scripts/models/IChainAdapter.ts
  wiki/App-Initialization-Flow.md
  wiki/Initialization-Flow.md
  wiki/Route-Loading-Audit.md
  wiki/_Table of Contents.md
Labels: 5

#4812 Clean up Layout component inline docs, first pass
  packages/commonwealth/client/scripts/views/Layout.tsx
Labels: 1
