Repository hicommonwealth/commonwealth, pull requests merged in 2024-05, with the labels that each got.

#7571 [Docs Improvement] Add Linting Cheatsheet to Linting.md
  knowledge_base/Linting.md
Labels: documentation

#6985 Add Glossary to Knowledge Base
  knowledge_base/ADRs/002-OpenFeature.md
  knowledge_base/App-Initialization-Flow.md
  knowledge_base/Environment-Variables.md
  knowledge_base/Feature-Flags.md
  knowledge_base/Notifications-Refactor.md
  knowledge_base/Notifications.md
  knowledge_base/Ways-Of-Working.md
  knowledge_base/_Glossary.md
  knowledge_base/_Wishlist.md
  packages/commonwealth/README.md
Labels: documentation

#7681 [Docs Improvement] Add Stake Cheatsheet
  knowledge_base/Environment-Variables.md
  knowledge_base/Linting.md
  knowledge_base/Stake.md
  knowledge_base/_TOC.md
Labels: documentation

#7701 [Docs Improvement] Clarify TSDoc Recommendations
  knowledge_base/Code-Style.md
Labels: documentation

#7840 Burton/small knock fixes
  packages/commonwealth/client/scripts/views/components/KnockNotifications/KnockNotifications.tsx
  packages/commonwealth/server/config.ts
  packages/commonwealth/server/routes/status.ts
Labels: 1

#7850 skip tests for now. they don't work anyway.
  packages/commonwealth/test/e2e/e2eRegular/discussionsTest.ts
  packages/commonwealth/test/e2e/mature/discussion.spec.ts
  packages/commonwealth/test/e2e/mature/newDiscussion.spec.ts
Labels: 1

#7833 7810 spl token gating
  libs/model/package.json
  libs/model/src/services/tokenBalanceCache/providers/cacheBalances.ts
  libs/model/src/services/tokenBalanceCache/providers/getSolanaBalances.ts
  libs/model/src/services/tokenBalanceCache/providers/get_spl_balances.ts
  libs/model/src/services/tokenBalanceCache/tokenBalanceCache.ts
  libs/model/src/services/tokenBalanceCache/types.ts
  libs/schemas/src/entities/group.schemas.ts
  libs/shared/src/types/protocol.ts
  packages/commonwealth/client/scripts/views/pages/CommunityGroupsAndMembers/Groups/common/GroupForm/RequirementSubForm/RequirementSubForm.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityGroupsAndMembers/Groups/common/helpers/index.ts
  packages/commonwealth/client/scripts/views/pages/CommunityGroupsAndMembers/common/constants.ts
  packages/commonwealth/client/scripts/views/pages/CommunityGroupsAndMembers/common/helpers.ts
  packages/commonwealth/client/scripts/views/pages/CreateCommunity/steps/CommunityTypeStep/helpers.ts
  packages/commonwealth/server/migrations/20240514145125-add-update-solana-chainnode.js
  packages/commonwealth/server/util/requirementsModule/makeGetBalancesOptions.ts
  packages/commonwealth/server/util/requirementsModule/requirementsSchema_v1.ts
  packages/commonwealth/server/util/requirementsModule/validateGroupMembership.ts
  yarn.lock
Labels: deployment plan

#7667 Launching and funding the contest
  libs/schemas/src/entities/topic.schemas.ts
  libs/shared/src/commonProtocol/chainConfig.ts
  packages/commonwealth/client/scripts/helpers/ContractHelpers/Abi/ContestAbi.ts
  packages/commonwealth/client/scripts/helpers/ContractHelpers/Contest.ts
  packages/commonwealth/client/scripts/helpers/ContractHelpers/ContractBase.ts
  packages/commonwealth/client/scripts/helpers/ContractHelpers/NamespaceFactory.ts
  packages/commonwealth/client/scripts/state/api/config.ts
  packages/commonwealth/client/scripts/state/api/contests/cancelContest.ts
  packages/commonwealth/client/scripts/state/api/contests/createContest.ts
  packages/commonwealth/client/scripts/state/api/contests/deployRecurringContestOnchain.ts
  packages/commonwealth/client/scripts/state/api/contests/deploySingleContestOnchain.ts
  packages/commonwealth/client/scripts/state/api/contests/fundContestOnchain.ts
  packages/commonwealth/client/scripts/state/api/contests/getContestBalance.ts
  packages/commonwealth/client/scripts/state/api/contests/getContests.ts
  packages/commonwealth/client/scripts/state/api/contests/index.ts
  packages/commonwealth/client/scripts/state/api/contests/updateContest.ts
  packages/commonwealth/client/scripts/views/components/AdminOnboardingSlider/AdminOnboardingSlider.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/CWContentPage/CWContentPage.tsx
  packages/commonwealth/client/scripts/views/components/component_kit/new_designs/CWPagination/CWPagination.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/ContestsList/ContestCard/ContestCard.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/ContestsList/ContestsList.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/FundContestDrawer/FundContestDrawer.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/FundContestDrawer/steps/FundContestForm/FundContestForm.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/FundContestDrawer/steps/FundContestSuccess/FundContestSuccess.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/FundContestDrawer/useFundContestForm.ts
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/FundContestDrawer/useUserAddressesForFundForm.ts
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/FundContestDrawer/utils.ts
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/ManageContest/ManageContest.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/ManageContest/steps/ContestLiveStep/ContestLiveStep.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/ManageContest/steps/DetailsFormStep/DetailsFormStep.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/ManageContest/steps/SignTransactionsStep/SignTransactionsStep.tsx
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/mockedContests.ts
  packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/useCommunityContests.ts
  packages/commonwealth/client/scripts/views/pages/discussions/ThreadCard/ThreadCard.tsx
Labels: deployment plan

#7871 Added migration to add tags list to db
  packages/commonwealth/server/migrations/20240517175253-add-tagslist-to-tags-table.js
Labels: deployment plan

#7980 Fix e2e test that broke after pnpm migration.
  packages/commonwealth/test/e2e/e2eRegular/discussionsTest.ts
Labels: 1
