Repository hicommonwealth/commonwealth, pull requests merged in 2025-03, with the labels that each got.

#11183 Twitter commondotxyz mentioned event/xp
  libs/core/src/integration/outbox.schema.ts
  libs/model/src/user/Xp.projection.ts
  libs/schemas/src/entities/quest.schemas.ts
  libs/schemas/src/events/events.schemas.ts
  libs/schemas/src/integrations/twitter.ts
  libs/shared/src/types/types.ts
  packages/commonwealth/deploy/dockerfiles/Dockerfiles.twitter
  packages/commonwealth/server/config.ts
  packages/commonwealth/server/workers/twitterWorker/pollTwitter.ts
  packages/commonwealth/server/workers/twitterWorker/twitterWorker.ts
  packages/commonwealth/server/workers/twitterWorker/utils.ts
Labels: deployment plan

#11163 Fixes an issue where Virtuoso was not initializing correctly
  packages/commonwealth/client/scripts/views/components/sidebar/CommunitySection/CommunitySection.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/SidebarSignInButton/SidebarSignInButton.scss
  packages/commonwealth/client/scripts/views/components/sidebar/SidebarSignInButton/SidebarSignInButton.tsx
  packages/commonwealth/client/scripts/views/components/sidebar/index.tsx
  packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
Labels: upcoming-release

#11160 Refactored ABIs
  libs/evm-protocols/src/abis/communityStakesAbi.ts
  libs/evm-protocols/src/abis/contestAbi.ts
  libs/evm-protocols/src/abis/feeManagerAbi.ts
  libs/evm-protocols/src/abis/index.ts
  libs/evm-protocols/src/abis/launchpadFactoryAbi.ts
  libs/evm-protocols/src/abis/lpBondingCurveAbi.ts
  libs/evm-protocols/src/abis/namespaceAbi.ts
  libs/evm-protocols/src/abis/namespaceFactoryAbi.ts
  libs/evm-protocols/src/abis/recurringContestAbi.ts
  libs/evm-protocols/src/abis/referralFeeManager.ts
  libs/evm-protocols/src/abis/reservationHookAbi.ts
  libs/evm-protocols/src/abis/singleContestAbi.ts
  libs/evm-protocols/src/abis/tokenCommunityManagerAbi.ts
  libs/evm-protocols/src/common-protocol/chainConfig.ts
  libs/evm-protocols/src/common-protocol/contractHelpers/contest.ts
  libs/evm-protocols/src/common-protocol/contractHelpers/launchpad.ts
  libs/evm-protocols/src/common-protocol/contractHelpers/tokens.ts
  libs/evm-protocols/src/event-registry/eventRegistry.ts
  libs/evm-testing/src/utils/contracts.ts
  libs/model/src/bot/LaunchTokenBot.command.ts
  libs/model/src/services/evmChainEvents/chain-event-utils.ts
  package.json
  packages/commonwealth/client/scripts/helpers/ContractHelpers/CommunityStakes.tsx
  packages/commonwealth/client/scripts/helpers/ContractHelpers/Contest.ts
  packages/commonwealth/client/scripts/helpers/ContractHelpers/Launchpad.ts
  packages/commonwealth/client/scripts/helpers/ContractHelpers/NamespaceFactory.ts
  packages/commonwealth/test/devnet/integration/event-processing-lifecycle.spec.ts
  packages/commonwealth/test/util/util.ts
  pnpm-lock.yaml
Labels: high priority, upcoming-release

#11335 Graphile Worker + Quest job scheduling
  libs/core/src/ports/interfaces.ts
  libs/model/package.json
  libs/model/src/config.ts
  libs/model/src/models/quest.ts
  libs/model/src/quest/CancelQuest.command.ts
  libs/model/src/quest/CreateQuest.command.ts
  libs/model/src/quest/DeleteQuest.command.ts
  libs/model/src/quest/UpdateQuest.command.ts
  libs/model/src/services/graphileWorker/graphile.config.ts
  libs/model/src/services/graphileWorker/index.ts
  libs/model/src/services/graphileWorker/types.ts
  libs/model/src/services/graphileWorker/utils.ts
  libs/model/src/services/index.ts
  libs/model/test/quest/quest-lifecycle.spec.ts
  libs/model/test/user/user-lifecycle.spec.ts
  libs/schemas/src/commands/quest.schemas.ts
  libs/schemas/src/entities/quest.schemas.ts
  libs/schemas/src/queries/quest.schemas.ts
  packages/commonwealth/client/scripts/views/pages/CreateQuest/QuestForm/QuestActionSubForm/types.ts
  packages/commonwealth/client/scripts/views/pages/CreateQuest/QuestForm/useQuestForm.ts
  packages/commonwealth/deploy/dockerfiles/Dockerfile.graphile_worker
  packages/commonwealth/package.json
  packages/commonwealth/server.ts
  packages/commonwealth/server/migrations/20250310073517-add-quest-type.js
  packages/commonwealth/server/scripts/cleanDb.ts
  packages/commonwealth/server/util/databaseCleaner.ts
  packages/commonwealth/server/workers/graphileWorker/cronJobs.ts
  packages/commonwealth/server/workers/graphileWorker/graphileWorker.ts
  packages/commonwealth/server/workers/graphileWorker/tasks.ts
  packages/commonwealth/server/workers/graphileWorker/tasks/archiveOutbox.ts
  packages/commonwealth/server/workers/graphileWorker/tasks/awardTwitterQuestXp.ts
  packages/commonwealth/server/workers/graphileWorker/tasks/cleanChainEventXpSources.ts
  packages/commonwealth/server/workers/graphileWorker/tasks/cleanSubscriptions.ts
  packages/commonwealth/server/workers/graphileWorker/tasks/runDbMaintenance.ts
  packages/commonwealth/server/workers/graphileWorker/tasks/sitemap-runner.ts
  packages/commonwealth/test/integration/databaseCleaner.spec.ts
  pnpm-lock.yaml
Labels: deployment plan
